### ISSUE TITLE
sp-application-crypto compiling is error

### ISSUE THREAD

**Issue by ztNozdormu** [paritytech/substrate#7265] opened 2020-10-06 06:48 UTC
![1601966627](https://user-images.githubusercontent.com/17536766/95167805-e7ecef00-07e2-11eb-8721-cfb55170f3ba.jpg)

**Comment by bkchr** [comment] 2020-10-06 07:06
Duplicate of: https://github.com/paritytech/substrate/issues/7256

**Closed by bkchr** 2020-10-06 07:06 UTC
Labels: Z0-unconfirmed
