### ISSUE TITLE
Use a sound off-chain mechanism for selecting next stakers 

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#1571] opened 2019-01-25 12:34 UTC
See 
https://github.com/paritytech/substrate/blob/bbe18168174cadaab8c693dd1f0812a883d150e4/srml/staking/src/lib.rs#L450-L480

**Comment by gavofyork** [comment] 2019-02-13 16:12
Duplicate of #1772

**Closed by gavofyork** 2019-02-13 16:12 UTC
Labels: F8-enhancement 🎁
