### ISSUE TITLE
PartyDb archive node panic

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/substrate#8224] opened 2021-02-28 13:46 UTC
Had an archive node for Kusama on ParityDb that got borked between last exit and this restart:
```
> ./polkadot --no-prometheus --no-telemetry --database=ParityDb --pruning=archive --wasm-execution=Compiled --chain=kusama
2021-02-28 07:46:18  ----------------------------    
2021-02-28 07:46:18  This chain is not in any way    
2021-02-28 07:46:18        endorsed by the           
2021-02-28 07:46:18       KUSAMA FOUNDATION          
2021-02-28 07:46:18  ----------------------------    
2021-02-28 07:46:18  Parity Polkadot    
2021-02-28 07:46:18  ✌️  version 0.8.28-1-99043f78-x86_64-linux-gnu    
2021-02-28 07:46:18  ❤️  by Parity Technologies <admin@parity.io>, 2017-2021    
2021-02-28 07:46:18  📋 Chain specification: Kusama    
2021-02-28 07:46:18  🏷 Node name: joe    
2021-02-28 07:46:18  👤 Role: FULL    
2021-02-28 07:46:18  💾 Database: ParityDb at /home/joe/.local/share/polkadot/chains/ksmcc3/paritydb    
2021-02-28 07:46:18  ⛓  Native runtime: kusama-2028 (parity-kusama-1.tx4.au2)    
2021-02-28 07:46:18  🏷 Local node identity is: 12D3KooWN36C6QjddjxKE66w3K8MHEhMuFWvutdkgQoZbRjNq3b5    
2021-02-28 07:46:18  📦 Highest known block at #6363045    
2021-02-28 07:46:18  Listening for new connections on 127.0.0.1:9944.    
2021-02-28 07:46:18  🔍 Discovered new external address for our node: /ip4/85.2.68.233/tcp/30333/p2p/12D3KooWN36C6QjddjxKE66w3K8MHEhMuFWvutdkgQoZbRjNq3b5    
2021-02-28 07:46:19  🔍 Discovered new external address for our node: /ip4/10.25.17.1/tcp/30333/p2p/12D3KooWN36C6QjddjxKE66w3K8MHEhMuFWvutdkgQoZbRjNq3b5    
2021-02-28 07:46:19  🔍 Discovered new external address for our node: /ip4/10.25.14.1/tcp/30333/p2p/12D3KooWN36C6QjddjxKE66w3K8MHEhMuFWvutdkgQoZbRjNq3b5    
2021-02-28 07:46:19  🔍 Discovered new external address for our node: /ip4/127.0.0.1/tcp/30333/p2p/12D3KooWN36C6QjddjxKE66w3K8MHEhMuFWvutdkgQoZbRjNq3b5    
2021-02-28 07:46:20  🔍 Discovered new external address for our node: /ip4/10.25.16.1/tcp/30333/p2p/12D3KooWN36C6QjddjxKE66w3K8MHEhMuFWvutdkgQoZbRjNq3b5    
2021-02-28 07:46:20  🔍 Discovered new external address for our node: /ip4/10.25.18.1/tcp/30333/p2p/12D3KooWN36C6QjddjxKE66w3K8MHEhMuFWvutdkgQoZbRjNq3b5    
2021-02-28 07:46:20  🔍 Discovered new external address for our node: /ip4/10.25.20.1/tcp/30333/p2p/12D3KooWN36C6QjddjxKE66w3K8MHEhMuFWvutdkgQoZbRjNq3b5    
2021-02-28 07:46:20  🔍 Discovered new external address for our node: /ip4/10.25.11.1/tcp/30333/p2p/12D3KooWN36C6QjddjxKE66w3K8MHEhMuFWvutdkgQoZbRjNq3b5    
2021-02-28 07:46:20  🔍 Discovered new external address for our node: /ip4/10.25.19.1/tcp/30333/p2p/12D3KooWN36C6QjddjxKE66w3K8MHEhMuFWvutdkgQoZbRjNq3b5    
2021-02-28 07:46:20  🔍 Discovered new external address for our node: /ip4/172.17.0.4/tcp/30333/p2p/12D3KooWN36C6QjddjxKE66w3K8MHEhMuFWvutdkgQoZbRjNq3b5    
2021-02-28 07:46:20  🔍 Discovered new external address for our node: /ip4/10.25.13.1/tcp/30333/p2p/12D3KooWN36C6QjddjxKE66w3K8MHEhMuFWvutdkgQoZbRjNq3b5    
2021-02-28 07:46:21  🔍 Discovered new external address for our node: /ip6/2a02:1205:5024:4e90:a9be:e3a3:c9c3:9f3d/tcp/30333/p2p/12D3KooWN36C6QjddjxKE66w3K8MHEhMuFWvutdkgQoZbRjNq3b5    
2021-02-28 07:46:21  🔍 Discovered new external address for our node: /ip4/10.25.15.1/tcp/30333/p2p/12D3KooWN36C6QjddjxKE66w3K8MHEhMuFWvutdkgQoZbRjNq3b5    
2021-02-28 07:46:23  ⚙️  Syncing, target=#6400691 (22 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 834.3kiB/s ⬆ 42.4kiB/s    
2021-02-28 07:46:28  ⚙️  Syncing  0.0 bps, target=#6400692 (22 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 26.8kiB/s ⬆ 6 B/s    
2021-02-28 07:46:33  ⚙️  Syncing  0.0 bps, target=#6400693 (23 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 12.2kiB/s ⬆ 7.5kiB/s    
2021-02-28 07:46:38  ⚙️  Syncing  0.0 bps, target=#6400694 (24 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 5.9kiB/s ⬆ 3.0kiB/s    
2021-02-28 07:46:40  🔍 Discovered new external address for our node: /ip4/172.17.0.1/tcp/30333/p2p/12D3KooWN36C6QjddjxKE66w3K8MHEhMuFWvutdkgQoZbRjNq3b5    
2021-02-28 07:46:43  ⚙️  Syncing  0.0 bps, target=#6400695 (24 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 2.7kiB/s ⬆ 0.3kiB/s    
2021-02-28 07:46:48  ⚙️  Syncing  0.0 bps, target=#6400696 (25 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 2.5kiB/s ⬆ 0.8kiB/s    
2021-02-28 07:46:53  ⚙️  Syncing  0.0 bps, target=#6400696 (26 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 5.2kiB/s ⬆ 2.9kiB/s    
2021-02-28 07:46:58  ⚙️  Syncing  0.0 bps, target=#6400697 (26 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 3.4kiB/s ⬆ 1.1kiB/s    
2021-02-28 07:47:03  ⚙️  Syncing  0.0 bps, target=#6400698 (26 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 3.1kiB/s ⬆ 1.0kiB/s    
2021-02-28 07:47:08  ⚙️  Syncing  0.0 bps, target=#6400699 (26 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 8.4kiB/s ⬆ 2.7kiB/s    
2021-02-28 07:47:13  ⚙️  Syncing  0.0 bps, target=#6400700 (26 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 6.8kiB/s ⬆ 0.3kiB/s    
2021-02-28 07:47:18  ⚙️  Syncing  0.0 bps, target=#6400701 (26 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 5.9kiB/s ⬆ 1.3kiB/s    
2021-02-28 07:47:22  🔍 Discovered new external address for our node: /ip4/10.110.0.5/tcp/30333/p2p/12D3KooWN36C6QjddjxKE66w3K8MHEhMuFWvutdkgQoZbRjNq3b5    
2021-02-28 07:47:23  ⚙️  Syncing  0.0 bps, target=#6400701 (25 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 29.0kiB/s ⬆ 15.2kiB/s    
2021-02-28 07:47:23  🔍 Discovered new external address for our node: /ip4/10.25.12.1/tcp/30333/p2p/12D3KooWN36C6QjddjxKE66w3K8MHEhMuFWvutdkgQoZbRjNq3b5    
2021-02-28 07:47:28  ⚙️  Syncing  0.0 bps, target=#6400702 (25 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 9.8kiB/s ⬆ 5.0kiB/s    
2021-02-28 07:47:33  ⚙️  Syncing  0.0 bps, target=#6400703 (25 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 6.6kiB/s ⬆ 3.9kiB/s    
2021-02-28 07:47:38  ⚙️  Syncing  0.0 bps, target=#6400704 (25 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 4.8kiB/s ⬆ 2.0kiB/s    
2021-02-28 07:47:43  ⚙️  Syncing  0.0 bps, target=#6400705 (25 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 3.6kiB/s ⬆ 0.8kiB/s    
2021-02-28 07:47:48  ⚙️  Syncing  0.0 bps, target=#6400705 (25 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 1.3kiB/s ⬆ 1.2kiB/s    
2021-02-28 07:47:53  ⚙️  Syncing  0.0 bps, target=#6400706 (25 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 3.9kiB/s ⬆ 2.5kiB/s    
2021-02-28 07:47:58  ⚙️  Syncing  0.0 bps, target=#6400707 (25 peers), best: #6363045 (0xd960…84dd), finalized #0 (0xb0a8…dafe), ⬇ 1.8kiB/s ⬆ 0.4kiB/s    

====================

Version: 0.8.28-1-99043f78-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:597
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:499
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495
   5: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92
   6: core::option::expect_none_failed
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:1268
   7: <sp_state_machine::ext::Ext<H,N,B> as sp_externalities::Externalities>::storage
   8: <&mut dyn sp_externalities::Externalities as sp_io::storage::Storage>::get_version_1
   9: std::thread::local::LocalKey<T>::with
  10: sp_io::storage::get_version_1
  11: sp_io::storage::get
  12: frame_support::storage::unhashed::get
  13: <(TupleElement0,TupleElement1) as frame_support::traits::OnInitialize<BlockNumber>>::on_initialize
  14: <(TupleElement0,TupleElement1) as frame_support::traits::OnInitialize<BlockNumber>>::on_initialize
  15: <(TupleElement0,TupleElement1) as frame_support::traits::OnInitialize<BlockNumber>>::on_initialize
  16: <(TupleElement0,TupleElement1) as frame_support::traits::OnInitialize<BlockNumber>>::on_initialize
  17: <(TupleElement0,TupleElement1) as frame_support::traits::OnInitialize<BlockNumber>>::on_initialize
  18: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::initialize_block
  19: sp_api::runtime_decl_for_Core::initialize_block_native_call_generator::{{closure}}
  20: std::thread::local::LocalKey<T>::with
  21: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
  22: sc_executor::wasm_runtime::RuntimeCache::with_instance
  23: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  24: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
  25: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  26: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  27: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  28: sp_api::runtime_decl_for_Core::initialize_block_call_api_at
  29: <kusama_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_initialize_block_runtime_api_impl
  30: sp_api::Core::initialize_block
  31: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  32: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  33: sp_block_builder::runtime_decl_for_BlockBuilder::check_inherents_call_api_at
  34: <sc_consensus_babe::BabeVerifier<Block,Client,SelectChain,CAW> as sp_consensus::import_queue::Verifier<Block>>::verify
  35: sp_consensus::import_queue::import_single_block_metered
  36: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  37: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  38: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  39: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  40: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  41: std::thread::local::LocalKey<T>::with
  42: futures_executor::local_pool::block_on
  43: tokio::runtime::task::core::Core<T,S>::poll
  44: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  45: tokio::runtime::task::harness::Harness<T,S>::poll
  46: tokio::runtime::blocking::pool::Inner::run
  47: tokio::runtime::context::enter
  48: std::sys_common::backtrace::__rust_begin_short_backtrace
  49: core::ops::function::FnOnce::call_once{{vtable.shim}}
  50: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/unix/thread.rs:71
  51: start_thread
  52: clone


Thread 'tokio-runtime-worker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0x715a92e3a0e7cd1adadbd1f2a18982fc73aba7124ede82c8249da04c291fc73d"', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/466ac62/primitives/state-machine/src/ext.rs:203

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new
```

**Comment by bkchr** [comment] 2021-02-28 18:55
Duplicate of: https://github.com/paritytech/polkadot/issues/2529

**Comment by bkchr** [comment] 2021-02-28 18:55
CC @arkpar just to make you aware that there is another one

**Closed by bkchr** 2021-02-28 18:55 UTC
Labels: I2-bug 🐜

**Comment by arkpar** [comment] 2021-02-28 20:44
@joepetrowski Is that database still available to grab a copy?

**Comment by joepetrowski** [comment] 2021-02-28 21:11
Sorry, it's not. I purged chain and started a fresh sync. I might have a way to reproduce it though. Will try this week.
