### ISSUE TITLE
block production took too long when uploading contract code

### ISSUE THREAD

**Issue by kigawas** [paritytech/substrate#4153] opened 2019-11-20 07:15 UTC
Uploading an ERC20 contract around 60kb will get dev node stuck, a workaround is to modify `MILLISECS_PER_BLOCK` to 10000 (i.e. 10s).

After the node stuck, pressing `Ctrl+C` will not work and I can only `kill -9`

**Comment by kigawas** [comment] 2019-11-20 07:16
```
2019-11-20 16:10:45 Idle (0 peers), best: #44 (0x5260…b828), finalized #43 (0xaaf4…4db7), ⬇ 0 ⬆ 0
^C2019-11-20 16:10:47 Prepared block for proposing at 45 [hash: 0x1e41b57813985ff22f36eefe69221e1882684452c28221d613218e202b82533b; parent_hash: 0x5260…b828; extrinsics: [0xfc8d…d9b3, 0xa081…f2f0, 0x686a…e65f]]
2019-11-20 16:10:47 Discarding proposal for slot 524744614; block production took too long
2019-11-20 16:10:47 Starting consensus session on top of parent 0x5260d71efd31a1b19f2d8d377c37c0756b17a0bcba9830a8864daccd75d3b828
2019-11-20 16:10:51 Prepared block for proposing at 45 [hash: 0x40fb8f9c7950b7692655e0f2a48d101b1d67f44cd5cb17e4fa70379025d391ce; parent_hash: 0x5260…b828; extrinsics: [0xec94…3310, 0xa081…f2f0, 0x686a…e65f]]
2019-11-20 16:10:51 Discarding proposal for slot 524744615; block production took too long
2019-11-20 16:10:51 Starting consensus session on top of parent 0x5260d71efd31a1b19f2d8d377c37c0756b17a0bcba9830a8864daccd75d3b828
[1]    22845 killed     ./target/release/substrate --dev
```

**Comment by kigawas** [comment] 2019-11-20 07:20
Maybe #1856 is kind of related

**Comment by bkchr** [comment] 2019-11-20 08:37
CC @pepyakin

**Comment by pepyakin** [comment] 2019-11-20 10:11
Duplicate of #3885

**Closed by pepyakin** 2019-11-20 10:11 UTC
