### ISSUE TITLE
Getting offchain-worker 'canonicalize elem' error on Rococo fork

### ISSUE THREAD

**Issue by bLd75** [paritytech/substrate#13048] opened 2023-01-03 09:04 UTC
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I am getting the error message below on custom relay chain, forked from Rococo wich custom chain specs, runtime is rococo/9310.
The error happens at every block imported, on both archive and full nodes. 
The error is non blocking, the node is still syncing fine.

- Changing offchain indexing as suggested in #12531 doesn't make error disapear.
- Only disabling offchain worker makes the message disapear.

```
offchain-worker runtime::mmr::offchain: Could not canonicalize elem at pos 1571016 using key [12, 109, 109, 114, 200, 248, 23, 0, 0, 0, 0, 0, 205, 224, 155, 51, 228, 136, 22, 253, 163, 126, 202, 74, 161, 246, 254, 237, 111, 67, 51, 108, 127, 168, 102, 5, 104, 222, 99, 72, 216, 169, 63, 75]
```

Below is a larger debug log of the node
```
2023-01-03 08:44:18.033 DEBUG tokio-runtime-worker wasm_overrides: No WASM override available for block BlockId::Hash(0x02c32c12ea7b2509a1b0b6afe7d5f81d236ab6644ad30fe33622e6528b771d31), using onchain code
2023-01-03 08:44:18.032 DEBUG      offchain-worker wasm-heap: allocator dropped: AllocationStats { bytes_allocated: 520, bytes_allocated_peak: 2160, bytes_allocated_sum: 13632, address_space_used: 2848 }
2023-01-03 08:44:18.032 DEBUG      offchain-worker offchain-worker::storage: Clear kind=StorageKind::PERSISTENT key="0c6d6d72caf8170000000000700ba95688504ac51c508e4e8f7ecdabf71981b179051abcbd1c126c234ffe52"
2023-01-03 08:44:18.032 DEBUG      offchain-worker runtime::mmr::offchain: Clear elem at pos 1571018 with key [12, 109, 109, 114, 202, 248, 23, 0, 0, 0, 0, 0, 112, 11, 169, 86, 136, 80, 74, 197, 28, 80, 142, 78, 143, 126, 205, 171, 247, 25, 129, 177, 121, 5, 26, 188, 189, 28, 18, 108, 35, 79, 254, 82]
2023-01-03 08:44:18.032 DEBUG      offchain-worker offchain-worker::storage: Clear kind=StorageKind::PERSISTENT key="0c6d6d72c9f8170000000000700ba95688504ac51c508e4e8f7ecdabf71981b179051abcbd1c126c234ffe52"
2023-01-03 08:44:18.032 DEBUG      offchain-worker runtime::mmr::offchain: Clear elem at pos 1571017 with key [12, 109, 109, 114, 201, 248, 23, 0, 0, 0, 0, 0, 112, 11, 169, 86, 136, 80, 74, 197, 28, 80, 142, 78, 143, 126, 205, 171, 247, 25, 129, 177, 121, 5, 26, 188, 189, 28, 18, 108, 35, 79, 254, 82]
2023-01-03 08:44:18.032 DEBUG      offchain-worker offchain-worker::storage: Clear kind=StorageKind::PERSISTENT key="0c6d6d72c8f8170000000000700ba95688504ac51c508e4e8f7ecdabf71981b179051abcbd1c126c234ffe52"
2023-01-03 08:44:18.032 DEBUG      offchain-worker runtime::mmr::offchain: Clear elem at pos 1571016 with key [12, 109, 109, 114, 200, 248, 23, 0, 0, 0, 0, 0, 112, 11, 169, 86, 136, 80, 74, 197, 28, 80, 142, 78, 143, 126, 205, 171, 247, 25, 129, 177, 121, 5, 26, 188, 189, 28, 18, 108, 35, 79, 254, 82]
2023-01-03 08:44:18.032 DEBUG      offchain-worker offchain-worker::storage: Clear kind=StorageKind::PERSISTENT key="0c6d6d726bfc0b002c7072756e696e675f6d6170"
2023-01-03 08:44:18.032 DEBUG      offchain-worker offchain-worker::storage: Read kind=StorageKind::PERSISTENT key="0c6d6d726bfc0b002c7072756e696e675f6d6170" result=Some("04700ba95688504ac51c508e4e8f7ecdabf71981b179051abcbd1c126c234ffe52")
2023-01-03 08:44:18.032 ERROR      offchain-worker runtime::mmr::offchain: Could not canonicalize elem at pos 1571018 using key [12, 109, 109, 114, 202, 248, 23, 0, 0, 0, 0, 0, 205, 224, 155, 51, 228, 136, 22, 253, 163, 126, 202, 74, 161, 246, 254, 237, 111, 67, 51, 108, 127, 168, 102, 5, 104, 222, 99, 72, 216, 169, 63, 75]
2023-01-03 08:44:18.032 DEBUG      offchain-worker offchain-worker::storage: Read kind=StorageKind::PERSISTENT key="0c6d6d72caf8170000000000cde09b33e48816fda37eca4aa1f6feed6f43336c7fa8660568de6348d8a93f4b" result=None
2023-01-03 08:44:18.032 ERROR      offchain-worker runtime::mmr::offchain: Could not canonicalize elem at pos 1571017 using key [12, 109, 109, 114, 201, 248, 23, 0, 0, 0, 0, 0, 205, 224, 155, 51, 228, 136, 22, 253, 163, 126, 202, 74, 161, 246, 254, 237, 111, 67, 51, 108, 127, 168, 102, 5, 104, 222, 99, 72, 216, 169, 63, 75]
2023-01-03 08:44:18.032 DEBUG      offchain-worker offchain-worker::storage: Read kind=StorageKind::PERSISTENT key="0c6d6d72c9f8170000000000cde09b33e48816fda37eca4aa1f6feed6f43336c7fa8660568de6348d8a93f4b" result=None
2023-01-03 08:44:18.032 ERROR      offchain-worker runtime::mmr::offchain: Could not canonicalize elem at pos 1571016 using key [12, 109, 109, 114, 200, 248, 23, 0, 0, 0, 0, 0, 205, 224, 155, 51, 228, 136, 22, 253, 163, 126, 202, 74, 161, 246, 254, 237, 111, 67, 51, 108, 127, 168, 102, 5, 104, 222, 99, 72, 216, 169, 63, 75]
2023-01-03 08:44:18.032 DEBUG      offchain-worker offchain-worker::storage: Read kind=StorageKind::PERSISTENT key="0c6d6d72c8f8170000000000cde09b33e48816fda37eca4aa1f6feed6f43336c7fa8660568de6348d8a93f4b" result=None
2023-01-03 08:44:18.032 DEBUG      offchain-worker runtime::mmr::offchain: Nodes to canon for leaf 785515: [1571016, 1571017, 1571018]
2023-01-03 08:44:18.032 DEBUG      offchain-worker offchain-worker::storage: Write kind=StorageKind::PERSISTENT key="0c6d6d726a0c0c002c7072756e696e675f6d6170" value="042fb7b2bfc5f81290725a546c77a6b0fc8248cf3a0ad7f7dbc95b041269cd85c6"
2023-01-03 08:44:18.032 DEBUG      offchain-worker offchain-worker::storage: Read kind=StorageKind::PERSISTENT key="0c6d6d726a0c0c002c7072756e696e675f6d6170" result=None
2023-01-03 08:44:18.032 DEBUG      offchain-worker wasm_overrides: No WASM override available for block BlockId::Hash(0x02c32c12ea7b2509a1b0b6afe7d5f81d236ab6644ad30fe33622e6528b771d31), using onchain code
2023-01-03 08:44:18.032 DEBUG      offchain-worker offchain-worker: Running offchain workers at BlockId::Hash(0x02c32c12ea7b2509a1b0b6afe7d5f81d236ab6644ad30fe33622e6528b771d31)
```

### Steps to reproduce

- Download Tokyo network [custom chain specs](https://github.com/AstarNetwork/Astar/blob/master/bin/collator/res/tokyo.raw.json)
- Spin up a Polkadot node using Tokyo chain specs

**Comment by bkchr** [comment] 2023-01-03 09:20
CC @acatangiu

**Comment by acatangiu** [comment] 2023-01-03 09:30
The issue is fixed starting with runtime `rococo/9340`.

(fixed in https://github.com/paritytech/polkadot/commit/3f288d36554fb49715eabfe880b5c19e5c59e235)

**Closed by acatangiu** 2023-01-03 09:30 UTC
Labels: Z0-unconfirmed

**Comment by bLd75** [comment] 2023-01-03 11:18
Thanks for the heads up, we'll just have to upgrade runtime then.
