### ISSUE TITLE
Failing to start substrate node after implementing the staking pallet

### ISSUE THREAD

**Issue by RecrafterH** [paritytech/substrate#14439] opened 2023-06-22 08:52 UTC
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Version: 4.0.0-dev-d962e431d87

   0: sp_panic_handler::set::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panicking.rs:692:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panicking.rs:579:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/sys_common/backtrace.rs:137:18
   4: rust_begin_unwind
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panicking.rs:575:5
   5: core::panicking::panic_fmt
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/core/src/panicking.rs:64:14
   6: <pallet_staking::pallet::pallet::GenesisConfig<T> as frame_support::traits::hooks::GenesisBuild<T>>::build
   7: environmental::using
   8: sp_state_machine::basic::BasicExternalities::execute_with_storage
   9: <node_template_runtime::GenesisConfig as sp_runtime::BuildStorage>::assimilate_storage
  10: <sc_chain_spec::chain_spec::ChainSpec<G,E> as sp_runtime::BuildStorage>::assimilate_storage
  11: sp_runtime::BuildStorage::build_storage
  12: sc_chain_spec::genesis::GenesisBlockBuilder<Block,B,E>::new
  13: sc_service::builder::new_full_parts
  14: node_template::service::new_partial
  15: node_template::service::new_full
  16: tokio::runtime::park::CachedParkThread::block_on
  17: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  18: tokio::runtime::runtime::Runtime::block_on
  19: sc_cli::runner::Runner<C>::run_node_until_exit
  20: node_template::command::run
  21: node_template::main
  22: std::sys_common::backtrace::__rust_begin_short_backtrace
  23: std::rt::lang_start::{{closure}}
  24: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/core/src/ops/function.rs:287:13
      std::panicking::try::do_call
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/rt.rs:148:20
  25: main
  26: <unknown>
  27: __libc_start_main
  28: _start

Thread 'main' panicked at 'Expected Ok(_). Got Err(
    Module(
        ModuleError {
            index: 22,
            error: [
                4,
                0,
                0,
                0,
            ],
            message: Some(
                "EmptyTargets",
            ),
        },
    ),
)', /home/recrafter/.cargo/git/checkouts/substrate-7e08433d4c370a21/98f2e34/frame/staking/src/pallet/mod.rs:652

This is a bug. Please report it at:

        support.anonymous.an

### Steps to reproduce

It was building properly with: cargo build --release

And the error occured at: ./target/release/node-template --dev

**Comment by thiolliere** [comment] 2023-07-01 03:16
> Version: 4.0.0-dev-d962e431d87

how can I get this version ? d962e431d87  doesn't seem to appear in the git repository.
I can't reproduce on master

**Comment by ganesh1233456** [comment] 2023-07-01 04:54
> > Version: 4.0.0-dev-d962e431d87
> 
> how can I get this version ? d962e431d87 doesn't seem to appear in the git repository. I can't reproduce on master

hey @thiolliere thanks for response. This is our [github repo](https://github.com/XcavateBlockchain/MarketplaceMVP_Substrate/tree/staking-pallet-testing) for this specific issue.

**Comment by thiolliere** [comment] 2023-07-01 06:18
I couldn't compile (because wasm-sys-opt need to be update to compile with gcc 13.1.1). but in this code:

https://github.com/XcavateBlockchain/MarketplaceMVP_Substrate/blob/d962e431d87d43faa90912600b1874c546b01735/node/src/chain_spec.rs#L182-L197

I think there is a mistake: 
```diff
diff --git a/node/src/chain_spec.rs b/node/src/chain_spec.rs
index 034d74c..da65c51 100644
--- a/node/src/chain_spec.rs
+++ b/node/src/chain_spec.rs
@@ -182,7 +182,7 @@ fn testnet_genesis(
        let stakers = initial_authorities
                .iter()
                .map(|x| (x.0.clone(), x.0.clone(), STASH, StakerStatus::Validator))
-               .chain(endowed_accounts.iter().map(|x| {
+               .chain(initial_nominators.iter().map(|x| {
                        use rand::{seq::SliceRandom, Rng};
                        let limit = (MaxNominations::get() as usize).min(initial_authorities.len());
                        let count = rng.gen::<usize>() % limit;
```

Anyway that doesn't explain why the assert is failing in staking.

**Comment by ganesh1233456** [comment] 2023-07-01 07:28
thanks @thiolliere that issue was fixed but now I face different issue. No blocks are producing and finalizing 

```
ganesholi@Ganeshs-MacBook-Air MarketplaceMVP_Substrate % ./target/release/node-template --dev
2023-07-01 13:10:07 Substrate Node    
2023-07-01 13:10:07 ✌️  version 4.0.0-dev-d962e431d87    
2023-07-01 13:10:07 ❤️  by Substrate DevHub <https://github.com/substrate-developer-hub>, 2017-2023    
2023-07-01 13:10:07 📋 Chain specification: Development    
2023-07-01 13:10:07 🏷  Node name: flawless-plant-1363    
2023-07-01 13:10:07 👤 Role: AUTHORITY    
2023-07-01 13:10:07 💾 Database: RocksDb at /var/folders/q3/d699hkpx49xfy236ph7sltr40000gn/T/substratewpatGD/chains/dev/db/full    
2023-07-01 13:10:07 ⛓  Native runtime: node-template-100 (node-template-1.tx1.au1)    
2023-07-01 13:10:07 [0] 💸 generated 0 npos voters, 0 from validators and 0 nominators    
2023-07-01 13:10:07 [0] 💸 generated 0 npos targets    
2023-07-01 13:10:09 🔨 Initializing Genesis block/state (state: 0x5974…be17, header-hash: 0x35c3…43f4)    
2023-07-01 13:10:09 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.    
2023-07-01 13:10:10 Using default protocol ID "sup" because none is configured in the chain specs    
2023-07-01 13:10:10 🏷  Local node identity is: 12D3KooWCVB5z8iubsKFkPCchxhnnpnBYJRq6DA1NPvCXc5QGBYf    
2023-07-01 13:10:10 💻 Operating system: macos    
2023-07-01 13:10:10 💻 CPU architecture: aarch64    
2023-07-01 13:10:10 📦 Highest known block at #0    
2023-07-01 13:10:10 〽️ Prometheus exporter started at 127.0.0.1:9615    
2023-07-01 13:10:10 Running JSON-RPC HTTP server: addr=127.0.0.1:9933, allowed origins=["*"]    
2023-07-01 13:10:10 Running JSON-RPC WS server: addr=127.0.0.1:9944, allowed origins=["*"]    
2023-07-01 13:10:15 💤 Idle (0 peers), best: #0 (0x35c3…43f4), finalized #0 (0x35c3…43f4), ⬇ 0 ⬆ 0    
2023-07-01 13:10:20 💤 Idle (0 peers), best: #0 (0x35c3…43f4), finalized #0 (0x35c3…43f4), ⬇ 0 ⬆ 0    
2023-07-01 13:10:25 💤 Idle (0 peers), best: #0 (0x35c3…43f4), finalized #0 (0x35c3…43f4), ⬇ 0 ⬆ 0    
2023-07-01 13:10:30 💤 Idle (0 peers), best: #0 (0x35c3…43f4), finalized #0 (0x35c3…43f4), ⬇ 0 ⬆ 0    
```

<img width="1439" alt="Screenshot 2023-07-01 at 13 10 32" src="https://github.com/paritytech/substrate/assets/42571338/70979de1-befd-4f6a-bc65-6fd412d42f8f">

Can you please help me why I am getting this issue now?

**Comment by thiolliere** [comment] 2023-07-02 03:38
if alice is the validator, then you need to run alice in the network, is it the case ?

**Comment by ganesh1233456** [comment] 2023-07-02 16:52
hey @thiolliere the issue is resolved now. Basically, there is conflict between two consensus aura and babe.

**Comment by ganesh1233456** [comment] 2023-07-02 16:53
@RecrafterH can you please close this issue.

**Closed** 2023-07-10 12:21 UTC
Labels: J2-unconfirmed
