### ISSUE TITLE
Cannot sync chain from scratch due to block import error

### ISSUE THREAD

**Issue by Dinonard** [paritytech/substrate#11891] opened 2022-07-22 15:13 UTC
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

## Description

Since we've upgraded from `polkadot-v0.9.19` to `polkadot-v0.9.24`, we cannot sync a node from scratch.
It always get stuck trying to import block **1086612** but it fails due to WASM call stack exhaustion.

If we downgrade to latest client before `polkadot-v0.9.24` upgrade, the block is imported successfully.
We've upgraded to `polkadot-v0.9.26` but error still persists.

## Log
Here is the log from one of our collators (about 2 weeks old):
[collator_20220707.txt](https://github.com/paritytech/substrate/files/9168759/collator_20220707.txt)

## What Was Investigated So Far

From what I can see in the log, an EVM-related call is being executed and it ends up with `call stack exhausted` error.
I followed the stacktrace and my guess is that it's some contract that perhaps has infinite recursion (or calls lots of functions) and used to fail due to gas limit. I cannot confirm that but according to [blockscout](https://blockscout.com/astar/block/1086612/transactions), 1 EVM transaction is marked as failed.

In the `evm` repo I found this:
```
Opcode::CALL => system::call(state, CallScheme::Call, handler),
Opcode::CALLCODE => system::call(state, CallScheme::CallCode, handler),
Opcode::DELEGATECALL => system::call(state, CallScheme::DelegateCall, handler),
Opcode::STATICCALL => system::call(state, CallScheme::StaticCall, handler),
```
hence my guess it's a recursive call (this part constantly repeats itself in the stacktrace).

My guess is that with latest upgrade(s), the callstack depth was reduced for wasmi and that's why it fails with new but works with old client. I haven't been able to verify this since I haven't managed to find where this is configured. (might be totally wrong, of course).

I did find this, although it relates to wasmtime:
https://bytemeta.vip/repo/bytecodealliance/wasmtime/issues/4214
We also have `regalloc2` as dependency, not sure if it is relevant though.

## Zoomed Part of the Log
The following is taken from the provided log to point out repeated calls:
```
2022-07-07 20:10:15 [Parachain] ⚙️  Syncing, target=#1389107 (7 peers), best: #1086611 (0x1c8b…6b8f), finalized #0 (0x9eb7…29c6), ⬇ 3.9MiB/s ⬆ 17.1kiB/s
2022-07-07 20:10:16 [Parachain] 330 storage transactions are left open by the runtime. Those will be rolled back.
2022-07-07 20:10:16 [Parachain] 330 storage transactions are left open by the runtime. Those will be rolled back.
2022-07-07 20:10:16 [Parachain] Block prepare storage changes error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: call stack exhausted
  WASM backtrace:
  0: <unknown>!evm_runtime::Runtime::run::h9658b50101d9a1f1
  1: 0x11a23f - <unknown>!evm::executor::stack::executor::StackExecutor<S,P>::call_inner::hdfd6092bf3da0b18
  2: 0x11d364 - <unknown>!<evm::executor::stack::executor::StackExecutor<S,P> as evm_runtime::handler::Handler>::call::h69ec87fd06dc45ef
  3: 0xb3968 - <unknown>!evm_runtime::eval::system::call::h87659850f0b00992
  4: 0x2300be - <unknown>!evm_runtime::eval::eval::hc1a492a7d69a6d92
  5: 0xe9d05 - <unknown>!evm_runtime::Runtime::run::h9658b50101d9a1f1
  6: 0x11a23f - <unknown>!evm::executor::stack::executor::StackExecutor<S,P>::call_inner::hdfd6092bf3da0b18
  7: 0x11d364 - <unknown>!<evm::executor::stack::executor::StackExecutor<S,P> as evm_runtime::handler::Handler>::call::h69ec87fd06dc45ef
  8: 0xb3968 - <unknown>!evm_runtime::eval::system::call::h87659850f0b00992
  9: 0x2300be - <unknown>!evm_runtime::eval::eval::hc1a492a7d69a6d92
 10: 0xe9d05 - <unknown>!evm_runtime::Runtime::run::h9658b50101d9a1f1
 11: 0x11a23f - <unknown>!evm::executor::stack::executor::StackExecutor<S,P>::call_inner::hdfd6092bf3da0b18
 12: 0x11d364 - <unknown>!<evm::executor::stack::executor::StackExecutor<S,P> as evm_runtime::handler::Handler>::call::h69ec87fd06dc45ef
 13: 0xb3968 - <unknown>!evm_runtime::eval::system::call::h87659850f0b00992
 14: 0x2300be - <unknown>!evm_runtime::eval::eval::hc1a492a7d69a6d92
...
...
...
1634: 0x2300be - <unknown>!evm_runtime::eval::eval::hc1a492a7d69a6d92
1635: 0xe9d05 - <unknown>!evm_runtime::Runtime::run::h9658b50101d9a1f1
1636: 0x11a23f - <unknown>!evm::executor::stack::executor::StackExecutor<S,P>::call_inner::hdfd6092bf3da0b18
1637: 0x11d364 - <unknown>!<evm::executor::stack::executor::StackExecutor<S,P> as evm_runtime::handler::Handler>::call::h69ec87fd06dc45ef
1638: 0xb3968 - <unknown>!evm_runtime::eval::system::call::h87659850f0b00992
1639: 0x2300be - <unknown>!evm_runtime::eval::eval::hc1a492a7d69a6d92
1640: 0xe9d05 - <unknown>!evm_runtime::Runtime::run::h9658b50101d9a1f1
1641: 0x11a23f - <unknown>!evm::executor::stack::executor::StackExecutor<S,P>::call_inner::hdfd6092bf3da0b18
1642: 0x11d364 - <unknown>!<evm::executor::stack::executor::StackExecutor<S,P> as evm_runtime::handler::Handler>::call::h69ec87fd06dc45ef
1643: 0xb3968 - <unknown>!evm_runtime::eval::system::call::h87659850f0b00992
1644: 0x2300be - <unknown>!evm_runtime::eval::eval::hc1a492a7d69a6d92
1645: 0xe9d05 - <unknown>!evm_runtime::Runtime::run::h9658b50101d9a1f1
1646: 0x11a23f - <unknown>!evm::executor::stack::executor::StackExecutor<S,P>::call_inner::hdfd6092bf3da0b18
1647: 0x119716 - <unknown>!evm::executor::stack::executor::StackExecutor<S,P>::transact_call::habd7cd23fb2ca77f
1648: 0xdb284 - <unknown>!<pallet_evm::runner::stack::Runner<T> as pallet_evm::runner::Runner<T>>::call::hce6b1473ecdc4939
1649: 0xe5235 - <unknown>!pallet_ethereum::<impl pallet_ethereum::pallet::Pallet<T>>::apply_validated_transaction::heb98eb14d23df8cc
1650: 0xecd87 - <unknown>!<pallet_ethereum::pallet::Call<T> as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::h747abd25cb98a9d2
1651: 0x9f7ff - <unknown>!<astar_runtime::Call as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::h77ff5d2bdf975aed
1652: 0x9cac5 - <unknown>!<astar_runtime::Call as sp_runtime::traits::Dispatchable>::dispatch::h0b11be2c27055c06
1653: 0x9ca2f - <unknown>!<astar_runtime::Call as fp_self_contained::SelfContainedCall>::apply_self_contained::he16e52be80a30fbe
1654: 0x22ce7f - <unknown>!<fp_self_contained::checked_extrinsic::CheckedExtrinsic<AccountId,Call,Extra,SelfContainedSignedInfo> as sp_runtime::traits::Applyable>::apply::h1c69cda9a66cc589
1655: 0x547e5 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::apply_extrinsic::h775d70717e8f3dba
1656: 0x52d76 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::h019662ea5c7bf877
1657: 0x175ca8 - <unknown>!Core_execute_block
```

### Steps to reproduce

Issue can be reproduced by downloading latest client from [here](https://github.com/AstarNetwork/Astar/releases).
To be on the safe side, the issue was first reported with the `v4.7.0` client so I recommend to try out with that one.

Use the following command to start the node:
```
astar-collator --chain astar --parachain-id 2006 --name "CannotImport" --execution wasm --prometheus-external --ws-port 9944 --port 33333 --state-cache-size 1 --rpc-port 29933 --prometheus-port 39616
```

**Comment by koute** [comment] 2022-07-25 09:47
It shouldn't be related to anything `wasmi`, since that's compiled into the runtime AFAIK, so any change to its maximum callstack length limit wouldn't affect historical blocks.

It's probably due to a new version of `wasmtime`, and their new register allocator being the culprit is a good guess considering how deep the stack trace is.

I'll take a look at this. It shouldn't be too hard to verify what exactly makes this explode if I'd just roll back to a previous version of `wasmtime` and try again. Even so, I'm not entirely sure what we could do to actually fix this, hm.... The EVM pallet should probably be fixed to *not* have this kind of unbound recursion, but that won't fix the issue for any of the historical blocks.

cc @pepyakin

**Comment by pepyakin** [comment] 2022-07-25 10:14
> The EVM pallet should probably be fixed to not have this kind of unbound recursion, but that won't fix the issue for any of the historical blocks.

Oh, absolutely.

**Comment by koute** [comment] 2022-07-28 11:42
Okay, I can confirm that the issue is due to a `wasmtime` upgrade. From what I can see the `wasmtime` 0.34 does **not** exhibit this issue, while `wasmtime` 0.35 **does**. If we look at `wasmtime`'s changelog we can see this:

> The native stack size allowed for WebAssembly has been decreased from 1 MiB to 512 KiB on all platforms to better accomodate running wasm on the main thread on Windows.

I've restored the original maximum stack size and I can confirm that it fixes this issue.

So the culprit here is **not** a different register allocator, but just simply a reduced default native stack size.

While I'm in general against increasing the stack size limit any further (and if the cause of this issue were due to the register allocator I would advocate for alternative measures) in this case I think we might as well just restore it to what it was originally, especially since it can potentially brick syncing for existing chains like we see here. @pepyakin Does this sound good to you?

(Note: this does **not** mean that the EVM pallet shouldn't be fixed to not have such deep recursion; it still *should*, and that's something I also intend to look into)

**Comment by koute** [comment] 2022-07-28 13:08
> Given all of that, I'd approach increasing the stack limit for wasm cautiously.

Agreed. This is precisely why I'd rather not increase it any further, but since we already implicitly guaranteed a stack size of 1MB and then accidentally reduced it to 512KB it'd make sense to me to just restore the original status quo, especially since (as we can see here) some people actually depended on it.

Although if there's a good reason to stay at the 512KB stack size I'm willing to be convinced. Technically an alternative fix to this would look like this:

1. Fix the EVM pallet so that it doesn't recurse, but that the results are still the same.
2. Recompile the affected runtime.
3. Use the code substitutes hack to replace the runtime during sync with the fixed version. (We do this ourselves on polkadot.)

So it's obviously a lot more involved, and if any other chain encounters this issue it'll have to be done separately for them.

**Comment by pepyakin** [comment] 2022-07-28 13:44
> Technically an alternative fix to this would look like this:

If going this way, I think a better way would be instead of adding code subs, just allowing to tweak executor parameters for particular blocks.

I am leaning toward fixing this on our side though.

When I said cautiously, I meant that we should inspect the code on having any host functions that do recursive calls or consume stack space excessively, with a feeling that it's probably alright. Also, potentially, employ the same fix that was done on the PVF side: increase the stack space allocated for the thread that enters into wasmtime.

**Comment by koute** [comment] 2022-07-28 13:49
> Also, potentially, employ the same fix that was done on the PVF side: increase the stack space allocated for the thread that enters into wasmtime.

Currently the runtime calls are made on whatever threads they incidentally end up being made, but I do want to refactor how we call into the runtime anyway to support async calls + QoS prioritization and that will entail running the executor on its own thread pool anyway, so yeah, that's something we definitely can do to have full control over the stack size.

**Comment by Dinonard** [comment] 2022-08-02 13:15
Hi @koute, thanks for looking into this!

Can you perhaps share when will the revert/fix for stack size be merged into substrate?

This is making lives of our node operators quite messy (they have to switch between old and new node to bypass the problematic block). If this cannot be done soon, we can look into forking `wasmtime` and increasing the stack size to what it was before, just to fix Astar/Shiden (we'd switch to your solution once it's merged).

From the discussion above, I don't believe this should be problematic, but we'd prefer to avoid messing with that repo if possible :sweat_smile:

**Comment by koute** [comment] 2022-08-03 11:04
@Dinonard Sorry for the inconvenience. Fixing this won't require forking `wasmtime` and can be easily patched on Substrate's side. I will have a PR ready next week.

**Comment by Dinonard** [comment] 2022-08-03 11:10
@koute no inconvenience, thanks for looking into it!

Will it be possible to backport this fix into `polkadot-v0.9.26` or `polkadot-v0.9.27` perhaps?

**Comment by koute** [comment] 2022-08-08 06:31
@Dinonard Well, I suppose we could backport it, but unless it's a more widespread issue it might not actually be necessary? The fix's not going to be anything complex, and it should be trivial to even just make your own temporary fork of `polkadot-v0.9.26` and apply it there (I could even prepare it for you if necessary).

Anyway, I'll ping you again once I push the PR with the fix.

**Comment by Dinonard** [comment] 2022-08-08 06:50
Sure, we can do that, it's not a problem if fix won't be complex.
Atm we're at `polkadot-v0.9.27` so I doubt there will have been any major changes since that branch released.

**Comment by koute** [comment] 2022-08-08 13:48
@Dinonard PR's available here: https://github.com/paritytech/substrate/pull/11993

**Comment by Dinonard** [comment] 2022-08-08 14:11
Awesome!
I'll prepare a fork, apply your PR and test just to confirm this particular issue is gone.

Thanks!

**Closed** 2022-08-09 11:04 UTC
Labels: Z0-unconfirmed

**Comment by Dinonard** [comment] 2022-08-09 11:18
I can confirm that the issue is gone :+1:
