### ISSUE TITLE
Windows client fail to connect to network

### ISSUE THREAD

**Issue by kenhuang** [paritytech/substrate#1788] opened 2019-02-13 20:48 UTC
latest master branch(c5077d1e4526e8290090cad54d8c18eb819a8cfe) fails connect to charred-cherry network.

![screen shot 2019-02-14 at 9 47 16 am](https://user-images.githubusercontent.com/205194/52742838-88eecb00-303d-11e9-9a0e-0d69cb27dbb6.png)

**Comment by gavofyork** [comment] 2019-02-15 14:01
Master won't connect any more as there have been breaking changes. `v0.9` branch should still connect though.

**Comment by kenhuang** [comment] 2019-02-19 22:38
When running from mac, it is able to sync block without issue. On windows is not able to start the sync process.
```
➜  substrate git:(c5077d1e) ✗ ./target/release/substrate --chain ~/Downloads/charred-cherry.json
2019-02-20 11:35:37 Substrate Node
2019-02-20 11:35:37   version 0.10.0-c5077d1e-x86_64-macos
2019-02-20 11:35:37   by Parity Technologies, 2017-2019
2019-02-20 11:35:37 Chain specification: Charred Cherry
2019-02-20 11:35:37 Node name: tangible-sidewalk-9781
2019-02-20 11:35:37 Roles: FULL
2019-02-20 11:35:37 Best block: #1559
2019-02-20 11:35:37 Local node address is: /ip4/0.0.0.0/tcp/30333/p2p/Qmc5Yj42JWYG3e5W5JLF6HMmWMQU3pmsmaYWbpP2JDxzh8
2019-02-20 11:35:37 Kademlia random query has yielded empty results
2019-02-20 11:35:37 Listening for new connections on 127.0.0.1:9944.
2019-02-20 11:35:37 Idle (0 peers), best: #1559 (0xe30d…3722), finalized #0 (0x7e22…f3c3), ⬇ 0 ⬆ 0
2019-02-20 11:35:38 Kademlia random query has yielded empty results
2019-02-20 11:35:42 Syncing 46.8 bps, target=#447398 (2 peers), best: #1793 (0x0402…a557), finalized #0 (0x7e22…f3c3), ⬇ 23.1kiB/s ⬆ 0.8kiB/s
2019-02-20 11:35:43 Network misbehaviour from PeerId(QmYHdf5E3Deq64KsPFWPfaX6cR37CgGDatFjFDsW6bhxDb) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-02-20 11:35:44 Network misbehaviour from PeerId(QmYWrEtg4iQYwV9PG37PhfLHLATQJUTYiZRyoUvSYny9ba) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-02-20 11:35:47 Network misbehaviour from PeerId(QmYaCKQgKJ68YDv6BraM4vTh1rUz6v2D3m72hYuT2ra57H) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-02-20 11:35:47 Syncing 172.6 bps, target=#447398 (2 peers), best: #2656 (0x8a44…a2c0), finalized #0 (0x7e22…f3c3), ⬇ 64.6kiB/s ⬆ 1.1kiB/s
2019-02-20 11:35:52 Syncing 174.6 bps, target=#447398 (2 peers), best: #3529 (0x241f…774a), finalized #0 (0x7e22…f3c3), ⬇ 52.2kiB/s ⬆ 0.1kiB/s
2019-02-20 11:35:57 Syncing 168.8 bps, target=#447398 (2 peers), best: #4373 (0xca26…8174), finalized #0 (0x7e22…f3c3), ⬇ 33.1kiB/s ⬆ 0.3kiB/s
2019-02-20 11:36:02 Syncing 162.6 bps, target=#447398 (2 peers), best: #5186 (0xedd2…dd2b), finalized #0 (0x7e22…f3c3), ⬇ 22.0kiB/s ⬆ 90 B/s
2019-02-20 11:36:07 Syncing 171.0 bps, target=#447399 (2 peers), best: #6041 (0x12bf…6a4c), finalized #0 (0x7e22…f3c3), ⬇ 38.2kiB/s ⬆ 75 B/s
2019-02-20 11:36:12 Syncing 159.0 bps, target=#447399 (2 peers), best: #6836 (0x283b…e6b7), finalized #0 (0x7e22…f3c3), ⬇ 33.1kiB/s ⬆ 0.2kiB/s
```

**Comment by bkchr** [comment] 2019-02-25 12:53
We can not reproduce this on windows on a local machine. Maybe you could try latest master and just run the node. (it will pick automatically the latest test net)

**Comment by tomaka** [comment] 2019-02-25 12:56
I've compiled Substrate on a Windows machine and ran it, and it seems to sync just fine.
Do you still see the issue @kenhuang ?

**Comment by shawntabrizi** [comment] 2019-02-25 20:59
@xlc are you still facing the issue?

**Comment by kenhuang** [comment] 2019-02-27 10:04
Still having network issue on the latest master branch.
```
$ ./target/release/substrate.exe
2019-02-27 22:59:18 Substrate Node
2019-02-27 22:59:18   version 0.10.0-cf46d62d-x86_64-windows-msvc
2019-02-27 22:59:18   by Parity Technologies, 2017-2019
2019-02-27 22:59:18 Chain specification: Dried Danta
2019-02-27 22:59:18 Node name: cagey-tank-7866
2019-02-27 22:59:18 Roles: FULL
2019-02-27 22:59:18 Generated a new keypair: 046617c2a396d7675287c9b804ffa0d542e73f867a7a60afa9fc70e21855f75f (5CAUNo8n...)
2019-02-27 22:59:19 Initialising Genesis block/state (state: 0x29bb…8986, header-hash: 0xfc0f…8777)
2019-02-27 22:59:19 Loaded block-time = 6 seconds from genesis on first-launch
2019-02-27 22:59:19 Loading GRANDPA authorities from genesis on what appears to be first startup.
2019-02-27 22:59:19 Best block: #0
2019-02-27 22:59:19 Local node address is: /ip4/0.0.0.0/tcp/30333/p2p/QmWiXq6JTi79NHs5CeHv8svdryj2QqnPTf4hz1n1RawhJP
2019-02-27 22:59:19 Multi-threaded server is not available on Windows. Falling back to single thread.
2019-02-27 22:59:19 Listening for new connections on 127.0.0.1:9944.
2019-02-27 22:59:20 Kademlia random query has yielded empty results
2019-02-27 22:59:31 Network misbehaviour from PeerId(QmYHdf5E3Deq64KsPFWPfaX6cR37CgGDatFjFDsW6bhxDb) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-02-27 22:59:31 Network misbehaviour from PeerId(QmZuDX6HSeXY4FVHwrEQ5SzKQGaGm443ZtYpk1rxkvpHP6) with protocol [115, 117, 112]: Upgrade(Select(MultistreamSelectError(IoError(Custom { kind: WriteZero, error: StringError("connection is closed") }))))
2019-02-27 22:59:32 Network misbehaviour from PeerId(QmYT3p4qGj1jwb7hDx1A6cDzAPtaHp3VR34vmw5BsXXB8D) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-02-27 22:59:37 Network misbehaviour from PeerId(QmV87bak5PD98CBJ1LxqwtyzuAL6X1gpQPtyWWgn7u4gPj) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-02-27 22:59:40 Network misbehaviour from PeerId(QmePFHyN1kNNdKCQ77Yxdf2bB4dnt2eummzAowoPuVc1y8) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-02-27 22:59:40 Network misbehaviour from PeerId(QmPEzArHGw29rhbhKPoK2Lc2XVxG1hGwdtp8rsAV1XhvPi) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-02-27 22:59:52 Network misbehaviour from PeerId(QmUMDwv88QrtFBkYzjLSgrBxxzz2wCG58byJCA1za7rkbb) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-02-27 22:59:52 Network misbehaviour from PeerId(QmRX3imcmrwHSNzAr92VMozzBRVpE6t4vFbEEPUw4awxZB) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-02-27 22:59:53 Network misbehaviour from PeerId(QmPkRr3X5QuMNoyC9j4UWDvxeVJb51oW87neMZcYJGNwwK) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-02-27 22:59:55 connection error: decode error: i/o error: I/O error: An established connection was aborted by the software in your host machine. (os error 10053)
```

**Comment by tomaka** [comment] 2019-02-27 10:33
I could indeed reproduce, but only from time to time.

**Comment by tomaka** [comment] 2019-02-27 10:40
The node looks stuck, but I think it's more that it's extremely slow.
The`ImportQueueWorker` thread runs at full speed, but the other threads are asleep most of the time.

I don't really understand where this line comes from:

> Multi-threaded server is not available on Windows. Falling back to single thread.

**Comment by kenhuang** [comment] 2019-02-27 11:34
Switch to a more powerful machine (iMac 27" with i7 CPU) same issue, CPU for the substrate process is around 15%.

Logs from the new machine:
```
$ ~/Downloads/substrate.exe
2019-02-28 00:30:22 Substrate Node
2019-02-28 00:30:22   version 0.10.0-cf46d62d-x86_64-windows-msvc
2019-02-28 00:30:22   by Parity Technologies, 2017-2019
2019-02-28 00:30:22 Chain specification: Dried Danta
2019-02-28 00:30:22 Node name: overconfident-test-4394
2019-02-28 00:30:22 Roles: FULL
2019-02-28 00:30:29 Best block: #0
2019-02-28 00:30:29 Local node address is: /ip4/0.0.0.0/tcp/30333/p2p/QmSesHsxv1rREqsxjDh31USuv4REvhstQ1C11pFeLWpzcm
2019-02-28 00:30:29 Multi-threaded server is not available on Windows. Falling back to single thread.
2019-02-28 00:30:29 Listening for new connections on 127.0.0.1:9944.
2019-02-28 00:30:29 Kademlia random query has yielded empty results
2019-02-28 00:30:32 Network misbehaviour from PeerId(QmPkRr3X5QuMNoyC9j4UWDvxeVJb51oW87neMZcYJGNwwK) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-02-28 00:30:32 Network misbehaviour from PeerId(QmYT3p4qGj1jwb7hDx1A6cDzAPtaHp3VR34vmw5BsXXB8D) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-02-28 00:30:32 Network misbehaviour from PeerId(QmPEzArHGw29rhbhKPoK2Lc2XVxG1hGwdtp8rsAV1XhvPi) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-02-28 00:30:33 Network misbehaviour from PeerId(QmYHdf5E3Deq64KsPFWPfaX6cR37CgGDatFjFDsW6bhxDb) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-02-28 00:30:33 Network misbehaviour from PeerId(QmV87bak5PD98CBJ1LxqwtyzuAL6X1gpQPtyWWgn7u4gPj) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-02-28 00:30:34 Network misbehaviour from PeerId(QmePFHyN1kNNdKCQ77Yxdf2bB4dnt2eummzAowoPuVc1y8) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-02-28 00:30:35 Network misbehaviour from PeerId(QmRX3imcmrwHSNzAr92VMozzBRVpE6t4vFbEEPUw4awxZB) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-02-28 00:30:38 Network misbehaviour from PeerId(QmZuDX6HSeXY4FVHwrEQ5SzKQGaGm443ZtYpk1rxkvpHP6) with protocol [115, 117, 112]: Upgrade(Select(MultistreamSelectError(IoError(Custom { kind: WriteZero, error: StringError("connection is closed") }))))
```

**Comment by tomaka** [comment] 2019-02-27 14:40
Nevermind, the slowness also happens on Linux and is caused by the latest master.
I don't think I am able to reproduce.

**Comment by bkchr** [comment] 2019-02-27 15:48
@kenhuang could you please run `~/Downloads/substrate.exe -ldebug`? Maybe that gives use some better insights.

**Comment by kenhuang** [comment] 2019-02-27 19:06
Here is the debug logs:
[debug.log](https://github.com/paritytech/substrate/files/2911883/debug.log)

**Comment by bkchr** [comment] 2019-02-27 20:34
@kenhuang ty, lets wait for @tomaka as he probably is the best for interpreting this libp2p logs :)

**Comment by tomaka** [comment] 2019-02-27 23:57
Hmm... That's a bit random but maybe the Windows firewall is blocking Substrate?

**Comment by kenhuang** [comment] 2019-02-28 21:34
Turn offed windows firewall seems still have the same issue. 

<img width="1163" alt="screen shot 2019-03-01 at 10 31 58 am" src="https://user-images.githubusercontent.com/205194/53599998-546a3a00-3c0d-11e9-9c3a-a06c4110e1be.png">

**Comment by tomaka** [comment] 2019-03-01 07:42
Do you see the node using a lot of CPU while it's stuck?

**Comment by kenhuang** [comment] 2019-03-01 08:32
Using around 15% of the CPU.

**Comment by shawntabrizi** [comment] 2019-03-13 23:21
I seem to also run into this issue with substrate on my Windows Machine:

```
shawn@DESKTOP-9EGNR6V MINGW64 ~/Documents/GitHub/substrate (master)
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 2.15s
     Running `target\debug\substrate.exe`
2019-03-14 00:19:49 Substrate Node
2019-03-14 00:19:49   version 0.10.0-8930f297-x86_64-windows-msvc
2019-03-14 00:19:49   by Parity Technologies, 2017-2019
2019-03-14 00:19:49 Chain specification: Dried Danta
2019-03-14 00:19:49 Node name: stereotyped-icicle-4914
2019-03-14 00:19:49 Roles: FULL
2019-03-14 00:19:50 Generated a new keypair: bb7b9dc71bf5aec2172badf2b06cc708fbcf65743d325e3b39e32cd5f68bce89 (5GJXXtLG...)
2019-03-14 00:19:51 Initialising Genesis block/state (state: 0x29bb…8986, header-hash: 0xfc0f…8777)
2019-03-14 00:19:51 Loaded block-time = 6 seconds from genesis on first-launch
2019-03-14 00:19:51 Loading GRANDPA authority set from genesis on what appears to be first startup.
2019-03-14 00:19:51 Best block: #0
2019-03-14 00:19:51 Local node address is: /ip4/0.0.0.0/tcp/30333/p2p/QmQwSq5HJTdcywpL2hcgk7wVsVTr2AekgmoqV8no3BVX3k
2019-03-14 00:19:51 Multi-threaded server is not available on Windows. Falling back to single thread.
2019-03-14 00:19:51 Listening for new connections on 127.0.0.1:9944.
2019-03-14 00:19:52 Kademlia random query has yielded empty results
2019-03-14 00:19:54 Network misbehaviour from PeerId(QmRn8yqn6LPTcM7fc2Wo76u9wgqw2WKU9Ysmegm9NCSrwU) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-03-14 00:19:54 Network misbehaviour from PeerId(QmUk6BtZNLC5TdZH31ZKvSpbvQaUomd2ZG7wjYHgGWrLuB) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-03-14 00:19:58 Handler initialization process is too long
2019-03-14 00:20:08 Network misbehaviour from PeerId(QmPiGU1jwL9UDw2FMyMQFr9FdpF9hURKxkfy6PWw6aLsur) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-03-14 00:20:08 Syncing, target=#300553 (5 peers), best: #128 (0x317a…b98a), finalized #0 (0xfc0f…8777), ⬇ 0.9kiB/s ⬆ 0.2kiB/s
2019-03-14 00:20:23 Syncing  8.6 bps, target=#300554 (5 peers), best: #256 (0xed97…dded), finalized #0 (0xfc0f…8777), ⬇ 0.9kiB/s ⬆ 0
2019-03-14 00:20:23 Network misbehaviour from PeerId(QmQmfm7XXXf5qLd8qANhMJ34rR1XyRYDndLnMpe8RK2LHF) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-03-14 00:20:23 Handler initialization process is too long
2019-03-14 00:20:23 Handler initialization process is too long
2019-03-14 00:20:23 Handler initialization process is too long
2019-03-14 00:20:24 Network misbehaviour from PeerId(QmVGwAmgrS4HTi8Qka6aVAdG3uS7u7nEzcdE1qdbgSttiw) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-03-14 00:20:24 Network misbehaviour from PeerId(QmUghPWmHR8pQbZyBMeYzvPcH7VRcTiBibcyBG7wMKHaSZ) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
```

These were the steps (in order) to install substrate dependencies:
```
Install Substrate on Windows
===

1. https://aka.ms/buildtools
    vs_buildtools.exe
    > Please ensure the Windows 10 SDK component is included when installing the Visual C++ Build Tools.

    ![](https://i.imgur.com/zayVLmu.png)

    Requires Restart
2. rustup-init.exe
    Did not ask me to install vs_buildtools
    Default installation
    > To get started you need Cargo's bin directory (%USERPROFILE%\.cargo\bin) in your PATH environment variable. Future applications will automatically have the correct environment, but you may need to restart your current shell.

3. Commands in CMD
    ```
    rustup update nightly
    rustup target add wasm32-unknown-unknown --toolchain nightly
    rustup update stable

    ```

4. Install wasm-gc
    ```
    cargo install --git https://github.com/alexcrichton/wasm-gc
    ```

5. Install LLVM
    https://releases.llvm.org/download.html
    Did not install into System PATH

6. Install OpenSSL (through vcpkg)
    ```
    mkdir \Tools
    cd \Tools
    git clone https://github.com/Microsoft/vcpkg.git
    cd vcpkg
    .\bootstrap-vcpkg.bat
    .\vcpkg.exe install openssl:x64-windows-static
    ```

7. Add OpenSSL to System Variables

    ```
    $env:OPENSSL_DIR = 'C:\Tools\vcpkg\installed\x64-windows-static'
    $env:OPENSSL_STATIC = 'Yes'
    [System.Environment]::SetEnvironmentVariable('OPENSSL_DIR', $env:OPENSSL_DIR, [System.EnvironmentVariableTarget]::User)
    [System.Environment]::SetEnvironmentVariable('OPENSSL_STATIC', $env:OPENSSL_STATIC, [System.EnvironmentVariableTarget]::User)
    ```

8. Install cmake
    https://cmake.org/download/
```

**Comment by tomaka** [comment] 2019-03-14 10:51
@shawntabrizi Yes

**Comment by mnaamani** [comment] 2019-04-16 07:05
I recently had similar issues with windows node not connecting successfully on our own chain, while the linux and mac nodes seemed to be working fine.

All platforms were built with stable rustc v1.34.0. 

I reverted windows build to compile with v1.33.0 and the node now successfully connects and syncs with its peers.

**Comment by tomaka** [comment] 2019-07-24 13:40
Triage.
This issue has been opened a long time ago, and *a lot* of code has changed in the networking since then.
Would need testing again.

**Comment by bkchr** [comment] 2019-08-12 11:15
I think we can close this for now. No reaction in the last months, so it is probably fixed.

**Closed by bkchr** 2019-08-12 11:15 UTC
Labels: Z1-question
