### ISSUE TITLE
decl_module+structs macro weirdness with deriving serialize traits

### ISSUE THREAD

**Issue by Ivshti** [paritytech/substrate#1050] opened 2018-11-01 13:00 UTC
This is how my `decl_module` block looks like:

```rust
 decl_module! {
        pub struct Module<T: Trait> for enum Call where origin: T::Origin {
               fn commitment_start(origin, bid: Bid<T::AccountId, T::Balance>) -> Result;
        }
}
```

Bid is defined as:
```rust
#[cfg_attr(feature = "std", derive(Serialize, Deserialize, Debug))]
#[derive(Encode, Decode, Clone, PartialEq, Eq)]
pub struct Bid<AccountId, Balance> {
    advertiser: AccountId,
    total_reward: Balance,
}
```

And Balance is:
```rust
pub type Balance = u128;

impl balances::Trait for Runtime {
    /// The type for recording an account's balance.
    type Balance = Balance;
```

The error I get compiling this is:

```
^ the trait `_IMPL_DESERIALIZE_FOR_Runtime::_serde::Deserialize<'_>` is not implemented for `<T as balances::Trait>::Balance`
```

**The weird thing is that when it's changed to:**

```rust
       fn commitment_start(origin: T::Origin, bid: Bid<T::AccountId, T::Balance>, bal: T::Balance) -> Result {
```

**it compiles normally**

**Comment by bkchr** [comment] 2018-11-01 13:13
Hey, could you give me access to the full source code? It clearly looks somehow weird.
In your last line, there is a new third parameter `bal`, is that by intention or is it just missing from your former declaration?

**Comment by Ivshti** [comment] 2018-11-01 16:11
@bkchr that's my point, when I add the `bal` as a third argument it compiles; somehow, that makes the first error go away

this is the repo: https://github.com/AdExNetwork/adex-protocol-substrate, I invited you

i've also made a branch https://github.com/AdExNetwork/adex-protocol-substrate/tree/does_not_compile and you can check https://github.com/AdExNetwork/adex-protocol-substrate/compare/master...does_not_compile

**Comment by bkchr** [comment] 2018-11-01 19:49
I will look into it. Thanks for sharing your code!

**Comment by bkchr** [comment] 2018-11-02 08:41
@Ivshti I pushed a commit to your branch. Essentially it was a problem with `serde`, because it did not added the correct trait bounds. 
I updated all your `Cargo.toml` files to use the master branch. I would recommend that you also push your `Cargo.lock` to always work against a fixed version of `substrate` as the project is evolving fast and stuff tends to break. 
The fix I pushed is just temporary, I will create a pull request for `substrate` and after that is merged, you can use `Bid` with `T::Balance` again.

**Comment by bkchr** [comment] 2018-11-02 08:50
Will be fixed by: https://github.com/paritytech/substrate/pull/1057

**Comment by Ivshti** [comment] 2018-11-06 23:59
@bkchr after the last commit that you pushed, I get this:

```
error[E0603]: module `rand` is private                                                                                                                                                                             
   --> /home/ivo/.cargo/git/checkouts/rust-libp2p-98135dbcf5b63918/9d91217/protocols/secio/src/lib.rs:258:55                                                                                                       
    |                                                                                                                                                                                                              
258 |         let (private, _) = secp.generate_keypair(&mut secp256k1::rand::thread_rng())                                                                                                                         
    |                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                            
                                                                                                                                                                                                                   
error: aborting due to previous error                                                                                                                                                                              
                                               
```


I tried `cargo clean` too

any ideas?

**Comment by bkchr** [comment] 2018-11-07 08:39
@Ivshti did you get the build error on your own project or on building substrate directly? I can not reproduce this error locally. If this error is happening in your project, that links to substrate, I would try a `cargo update`.

Nevertheless @tomaka do you have seen this build error with `libp2p`?

**Comment by Ivshti** [comment] 2018-11-07 09:40
@bkchr yeah, it just required a `cargo update`; it's fine now

anyway, any ideas on how to do `Vec<AccountId>` ? I checked out https://github.com/serde-rs/serde/issues/723, there seems to be no elegant way to do it

**Comment by bkchr** [comment] 2018-11-07 09:42
No sorry, I don't have a better solution either at the moment.

**Closed by bkchr** 2018-11-07 09:42 UTC
Labels: F2-bug
