### ISSUE TITLE
Parallelize block import from verification

### ISSUE THREAD

**Issue by gterzian** [paritytech/substrate#1816] opened 2019-02-18 04:25 UTC
> Ideally we want the block import pipeline to call `verify` and `import_block` in parallel threads.
@arkpar https://github.com/paritytech/substrate/pull/1327#issuecomment-463180005

verification is at https://github.com/paritytech/substrate/blob/ed2faf445f8849e8d90ddadc684ac2658819e55f/core/consensus/common/src/import_queue.rs#L635

import is at https://github.com/paritytech/substrate/blob/ed2faf445f8849e8d90ddadc684ac2658819e55f/core/consensus/common/src/import_queue.rs#L645

Possible solution:

Have the [BlockImportWorker](https://github.com/paritytech/substrate/blob/ed2faf445f8849e8d90ddadc684ac2658819e55f/core/consensus/common/src/import_queue.rs#L445) own a [rayon thread-pool](https://docs.rs/rayon/*/rayon/struct.ThreadPool.html) and then [join](https://docs.rs/rayon/*/rayon/struct.ThreadPool.html#method.join) "import" and "verify" as two separate parallel operation, and returning the appropriate "joined" result at https://github.com/paritytech/substrate/blob/ed2faf445f8849e8d90ddadc684ac2658819e55f/core/consensus/common/src/import_queue.rs#L579

This setup still guarantees the sequential nature of the basic import queue, since only one block is handled at a time, yet the verification and import of one block will be parallelized. This is what you meant, @arkpar  right?

**Comment by arkpar** [comment] 2019-02-18 16:09
Verification may be performed on several blocks simultaneously. Import should be synchronised indeed. Though currently it may not be worth it to have more than one verification thread since import is probably more heavy anyway, at least for WASM runtime. 

We need to be careful on what careful on what can be parallelised though. Ideally verification does not depend on the state of the previous block, but we have dependencies on the runtime code and authority set. So parallelization should stop when these change.
Aura verification also calls `check_inherents` but I believe it is pure and does not really access state. 
Perhaps @rphmeier or @gavofyork will correct me here.

**Comment by rphmeier** [comment] 2019-02-18 17:14
The way I've designed the pluggable consensus system is so every consensus mechanism can design its own parallel verification queue. Some aspects are likely to be common and reusable but they may also differ. We should keep this in mind when building a parallel verification queue.

For Aura and aura-like, for instance, you can theoretically queue up verifications until the next authority set change. This is unfortunately complicated by `check_inherents`. `check_inherents` is pure for a given runtime but authority set changes can be interleaved with runtime upgrades.

One thing I've wanted for a while (which would make things a bit easier for certain light-client use cases) is to have a digest item for runtime code changes. Then we could verify parallel up to the next authority set change signal or runtime upgrade signal, wait for the queue to drain, and then continue with the new runtime/authorities parameters.

**Comment by rphmeier** [comment] 2019-02-18 17:14
Related to #1210

**Comment by gterzian** [comment] 2019-02-19 13:42
If import is heavier than verification, and since we import blocks by batches of 128, I can imagine it could be useful to verify all 128 of them, and not bother with the import if there is any that doesn't check out. 

It could be as easy as initializing the current `has_error`[https://github.com/paritytech/substrate/blob/edf2a8fcdfec15f24bdbc0e73f65af8efcdc9c48/core/consensus/common/src/import_queue.rs#L497] to the result of verifying all blocks in that batch. 

This doesn't make it parallel, more like an early break in case anything is wrong...

The "parallel" version of this could be starting the import, and stopping as soon as you run into an error in the verification.

**Comment by gavofyork** [comment] 2019-11-28 09:01
Dupe of #1210

**Closed by gavofyork** 2019-11-28 09:01 UTC
Labels: F7-optimisation ⏱, M4-core
