### ISSUE TITLE
Thread 'main-tokio-1' panicked at 'applying the snapshot can only fail if the passed instance is different

### ISSUE THREAD

**Issue by iammelea** [paritytech/substrate#3837] opened 2019-10-17 01:37 UTC
```
   3: rust_begin_unwind
             at src/libstd/panicking.rs:311
   4: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed
   6: <substrate_executor::native_executor::NativeExecutor<D> as substrate_primitives::traits::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call
   7: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_aux
   8: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_using_consensus_failure_handler
   9: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call
  10: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at
  11: <node_runtime::RuntimeApiImpl<RuntimeApiImplCall> as substrate_client::runtime_api::Core<<node_runtime::Runtime as sr_primitives::traits::GetNodeBlockType>::NodeBlock>>::Core_initialize_block_runtime_api_impl
  12: substrate_client::runtime_api::Core::initialize_block_with_context
  13: substrate_client::block_builder::block_builder::BlockBuilder<Block,A>::at_block
  14: <substrate_basic_authorship::basic_authorship::Proposer<Block,substrate_client::client::Client<B,E,Block,RA>,A> as substrate_consensus_common::Proposer<Block>>::propose
  15: <substrate_consensus_babe::BabeWorker<C,E,I,SO> as substrate_consensus_slots::SlotWorker<B>>::on_slot
  16: <futures_util::try_stream::try_for_each::TryForEach<St,Fut,F> as core::future::future::Future>::poll
  17: <futures_util::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
  18: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  19: <futures::future::select::Select<A,B> as futures::future::Future>::poll
  20: futures::future::chain::Chain<A,B,C>::poll
  21: futures::task_impl::std::set
  22: std::panicking::try::do_call
  23: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  24: tokio_threadpool::task::Task::run
  25: tokio_threadpool::worker::Worker::run_task
  26: tokio_threadpool::worker::Worker::run
  27: std::thread::local::LocalKey<T>::with
  28: std::thread::local::LocalKey<T>::with
  29: tokio_reactor::with_default
  30: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  31: std::thread::local::LocalKey<T>::with
  32: std::thread::local::LocalKey<T>::with
  33: std::sys_common::backtrace::__rust_begin_short_backtrace
  34: std::panicking::try::do_call
  35: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  36: core::ops::function::FnOnce::call_once{{vtable.shim}}
  37: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  38: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  39: start_thread
  40: clone


Thread 'main-tokio-1' panicked at 'applying the snapshot can only fail if the passed instance is different
                        from the one that was used for creation of the snapshot;
                        we use the snapshot that is directly associated with the instance;
                        thus the snapshot was created using the instance;
                        qed: ApplySnapshotFailed', src/libcore/result.rs:999

This is a bug. Please report it at:

        https://github.com/paritytech/substrate/issues/new

```
Validator crash testing substrate in private testnet
```
substrate --version
substrate 2.0.0-4117bb9-x86_64-linux-gnu
```

**Comment by bkchr** [comment] 2019-10-17 04:41
PLease use the search.

Duplicate of https://github.com/paritytech/substrate/issues/3780

**Closed by bkchr** 2019-10-17 04:41 UTC
