### ISSUE TITLE
How to deploy a rust base smart contract on substrate?

### ISSUE THREAD

**Issue by hliu4atomos** [paritytech/substrate#2023] opened 2019-03-17 07:44 UTC
From the public article, we knew that developers can start deploying Rust-based smart contracts to the testnet in this early stage. 

We tried a lot, but still didn't make it work.

One guy pointed out there was a good document: https://github.com/paritytech/substrate/issues/1607
Could you please share this document to us?

**Comment by bkchr** [comment] 2019-03-18 08:55
@pepyakin should be able to help here :)

**Comment by pepyakin** [comment] 2019-03-18 10:56
Tbh I don't know where the doc have gone, but I know for sure that this document would be outdated by now.

Duplicate of #1607

**Closed by pepyakin** 2019-03-18 10:56 UTC

**Comment by hliu4atomos** [comment] 2019-03-18 22:23
Could you give us some examples about the substrate smart contract if the document is not available?
Actually, even a outdated doc will be helpful.
We need some help on substrate smart contract and I don't know why you just duplicate this bug?

**Comment by pepyakin** [comment] 2019-03-19 11:29
Yeah, I will try to look for that doc. I think the example/tutorial is also will be available in the foreable future.

**Comment by hliu4atomos** [comment] 2019-03-19 17:46
This is a not a touch question for parity team I think, just some sample code is enough for us. Could you please kindly share?

**Comment by pepyakin** [comment] 2019-03-19 17:53
If you feel brave, you can take a look on these:

- https://github.com/pepyakin/substrate-contracts-adder , a raw prototype contract
- https://github.com/Robbepop/pdsl , a suite of libraries which contains some examples

you can spin up a node locally (with a --dev flag), and then using https://polkadot.js.org/apps/ you can send extrinsics to the contract module, including `put_code` which deploy code on the chain, as well, as `instantiate` which is used for instantiating a contract with the given code hash.

This is all I can give you. Hope that'll help.

**Comment by hliu4atomos** [comment] 2019-03-20 03:36
Yes sir! We are brave enough.

**Comment by pepyakin** [comment] 2019-04-29 09:36
Hey @hliu4atomos , this might help you [Substrate Contracts Workshop](https://shawntabrizi.github.io/substrate-contracts-workshop/#/)
