### ISSUE TITLE
Node CLI Won't Accept Multiple Key Types

### ISSUE THREAD

**Issue by danforbes** [paritytech/substrate#5817] opened 2020-04-28 16:39 UTC
This issue is being forked from substrate-developer-hub/tutorials#21. @DemiMarie-parity suggested that [this tutorial should instruct users to pass keys to the Substrate node by way of CLI parameters](https://github.com/substrate-developer-hub/tutorials/issues/21#issuecomment-619257258). However, the tutorial in question requires that users add two keys to the node, but as far as I can tell the command line parameters can only be used to add a single key (because of the relationship of the `--node-key-file` and `--node-key-type` parameters). I ran this interpretation by Demi and she concurred and suggested I open this issue.

**Comment by JoshOrndorff** [comment] 2020-04-28 20:02
The flags you mentioned are for your node's libp2p key. It is the key responsible for generating the node id. It is different than the session keys that the tutorial inserts via the `author_insertKey` rpc. RPC is the correct way to insert session keys.

**Comment by danforbes** [comment] 2020-04-28 20:08
Thanks for that context, Joshy :+1: In light of what @DemiMarie-parity said, I wonder if the node should support CLI parameters for the session keys. Reopening this issue after a brief offline discussion with Joshy.

**Comment by burdges** [comment] 2020-04-28 20:31
Almost all slashing in other networks results from operators miss-handling keys.  We designed this architecture with the controller key certifying the session keys partially so that operators only certified the public session keys, while nodes created and managed the private session keys entirely automatically.  There are various reasons why people want to do other things sometimes, but we should've a simplified work flow in which operators never really touch those private session keys directly.

**Comment by DemiMarie-parity** [comment] 2020-04-28 21:03
To elaborate on what @burdges stated:

* Session keys are ephemeral by design.  They should not (and do not need to) be backed up, for example.  Losing a session key can only happen when a node is offline, and when it does happen, the correct response is to generate a new session key and sign it with the controller key.
* Controller keys should be stored semi-offline in a hardware device, where they are protected from being leaked.  Using them should generally require manual intervention, but this should be possible on short notice.
* Using cURL to make an RPC call is an anti-pattern and very fragile.  A much better approach would be to have a command-line tool that handles the communication between the hardware wallet (which stores the secret controller keys) and the node itself.  Such a tool is already under development by me and @kirushik.

**Comment by JoshOrndorff** [comment] 2020-04-29 12:51
I also think that changing the CLI in this situation is the wrong thing to do. But we should at least all understand the context being discussed. Dan's question arose in the context of the "**Start** a private network" tutorial. Specifically the [Add keys to keystore setion](https://www.substrate.io/tutorials/start-a-private-network/v2.0.0-alpha.6/customchain#add-keys-to-keystore).

So while everything @burdges and @DemiMarie-parity said is correct in general, it is mostly not addressing @danforbes concern. It specifically misses two important points.

1. This is not about rotating session keys it's about inserting keys to author the first few blocks of a new chain.
2. Not all nodes use the staking pallet and its controller configuration. The node template, which the tutorial in question is about, does not use either. It is simple Proof of Authority.

**Comment by bkchr** [comment] 2020-04-29 14:19
@JoshOrndorff I still don't understand what the exact question is? :D

**Comment by danforbes** [comment] 2020-04-29 15:26
The question is: what capabilities currently exist within Substrate to obviate [the security concern that @DemiMarie-parity brought up](https://github.com/substrate-developer-hub/tutorials/issues/21); how can these capabilities be composed to address Demi's concern?

**Comment by bkchr** [comment] 2020-04-29 15:58
The point is, that besides genesis you never need `insertKey`. You are always advised to use `rotateKeys`, as this is much easier. 

You can also insert the data directly into the keystore, if you like.

You can also make curl read the data from a file before sending it or use `subkey` to send the key.

But we are talking about a tutorial, that should be easy, aka showing a curl command. It should not be over complicated because of some very unlikely attack. 

Given that this is an issue that will not be solved by Substrate, I close it.

**Closed by bkchr** 2020-04-29 15:58 UTC
