### ISSUE TITLE
Openai support

### ISSUE THREAD

**Issue by DaviRain-Su** [paritytech/substrate#11283] opened 2022-04-25 15:20 UTC
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Whether openai can be supported to expose rpc methods

**Comment by ggwpez** [comment] 2022-04-25 17:10
This is not a bug.  
What would OpenAI do in the context of Substrate?

**Comment by bkchr** [comment] 2022-04-25 18:30
You can expose whatever rpc methods you like. However, we will not add openai to Substrate directly. Thus, I'm going to close this issue.

**Closed by bkchr** 2022-04-25 18:30 UTC
Labels: Z0-unconfirmed

**Comment by DaviRain-Su** [comment] 2022-04-25 18:49
> 
oh, thx.
