### ISSUE TITLE
Nodes not sustaining connections

### ISSUE THREAD

**Issue by maxsam4** [paritytech/substrate#2420] opened 2019-04-29 15:49 UTC
When using grandpa with multiple validators, the validator nodes fail to sustain connections with other nodes.

Step to produce
1) Run 2+ validator nodes
2) Run 1 full node
3) Run another full node
4) Restart the first full node
```
substrate --chain=local --alice --validator -d ./a1 --port 20000
substrate --chain=local --bob --validator -d ./b1 --port 20001
substrate --chain=local -d ./c1 --port 20002
substrate --chain=local -d ./d1 --port 20003
```

Result
The validator nodes will not be able to sustain a connection with full nodes anymore. The validator nodes will connect for a few seconds (this means they are discoverable) and then disconnect from full nodes. The chain will keep progressing as the validator nodes will keep in sync with each other (most of the time) but no other node will be able to keep in sync.

**Comment by gavofyork** [comment] 2019-04-29 15:57
I think this is probably a dupe of #2411

**Closed** 2019-04-29 15:57 UTC
