### ISSUE TITLE
failed to run custom build command for `node-runtime`

### ISSUE THREAD

**Issue by mattrutherford** [paritytech/substrate#3278] opened 2019-07-31 17:50 UTC
After making changes to the runtime, substrate fails to build. Cargo clean will fix the issue. Upgrading nightly will negate the need to `cargo clean`, but only works for the first build after upgrade.

```
error: failed to run custom build command for `node-runtime v2.0.0 (/projects/parity/substrate/node/runtime)`

Caused by:
  process didn't exit successfully: `/projects/parity/substrate/target/release/build/node-runtime-f3eae89ffabb66e7/build-script-build` (exit code: 1)
--- stdout
Executing build command: "rustup" "run" "nightly" "cargo" "build" "--target=wasm32-unknown-unknown" "--manifest-path=/projects/parity/substrate/target/release/wbuild/node-runtime/Cargo.toml" "--release"

--- stderr
   Compiling wasm-build-runner-impl v1.0.0 (/projects/parity/substrate/target/release/build/node-runtime-2e02e1c563741531/out/wasm_build_runner)
    Finished release [optimized] target(s) in 0.82s
     Running `/projects/parity/substrate/target/release/build/node-runtime-2e02e1c563741531/out/wasm_build_runner/target/release/wasm-build-runner-impl`
   Compiling node-runtime-wasm v1.0.0 (/projects/parity/substrate/target/release/build/node-runtime)
thread '<unnamed>' panicked at 'must have at least one serialized module', src/libcore/option.rs:1166:5
stack backtrace:
   0:        0x10a1990f2 - std::panicking::default_hook::{{closure}}::hcedd49a6d4e80532
   1:        0x10a198dbd - std::panicking::default_hook::h8812e129f0beb8fb
   2:        0x108dee3d3 - rustc::util::common::panic_hook::hf84fcb985b491fb6
   3:        0x10a1999b1 - std::panicking::rust_panic_with_hook::h618b31e9e38cad59
   4:        0x10a19940d - std::panicking::continue_panic_fmt::h1a98c0f5b25de6c7
   5:        0x10a1992f9 - rust_begin_unwind
   6:        0x10a1c5022 - core::panicking::panic_fmt::h1a8832c7515fdc7d
   7:        0x10a1c513e - core::option::expect_failed::hf0a65cb730c9f88a
   8:        0x10ac78f98 - rustc_codegen_llvm::back::lto::run_fat::hbcd0875256947d2f
   9:        0x10acf4da8 - rustc_codegen_ssa::back::write::start_executing_work::{{closure}}::heac93b8d0bd7b9cf
  10:        0x10acfdbb0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h994c13b11821ca23
  11:        0x10ac466fc - std::panicking::try::do_call::h1fef0680a7be2fca
  12:        0x10a1a8d2f - __rust_maybe_catch_panic
  13:        0x10ac46ad6 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h06306e306ac3ceb4
  14:        0x10a17ccfe - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hacc9598ae4aad64e
  15:        0x10a1a7b3e - std::sys::unix::thread::Thread::new::thread_start::ha775066dcca59bc1
  16:     0x7fff7c8392eb - _pthread_body
  17:     0x7fff7c83c249 - _pthread_start
query stack during panic:
end of query stack
thread 'rustc' panicked at 'src/librustc_codegen_ssa/back/write.rs:1826: panic during codegen/LLVM phase', src/librustc/util/bug.rs:37:26
stack backtrace:
   0:        0x10a1990f2 - std::panicking::default_hook::{{closure}}::hcedd49a6d4e80532
   1:        0x10a198dbd - std::panicking::default_hook::h8812e129f0beb8fb
   2:        0x108dee3d3 - rustc::util::common::panic_hook::hf84fcb985b491fb6
   3:        0x10a1999b1 - std::panicking::rust_panic_with_hook::h618b31e9e38cad59
   4:        0x108e3a985 - std::panicking::begin_panic::h22e97f03c0723d7e
   5:        0x108b9e384 - rustc::util::bug::opt_span_bug_fmt::{{closure}}::h7f316e34ad7976ab
   6:        0x108b8d2aa - rustc::ty::context::tls::with_opt::{{closure}}::h042125561f310776
   7:        0x108b8d227 - rustc::ty::context::tls::with_context_opt::hbecad2ded6500d82
   8:        0x108b8d272 - rustc::ty::context::tls::with_opt::h822fc12416d695ff
   9:        0x108b9e2c8 - rustc::util::bug::opt_span_bug_fmt::h92b7807b92333fcd
  10:        0x108b9e21b - rustc::util::bug::bug_fmt::hc5e189b6fff58e45
  11:        0x10acf9f35 - rustc_codegen_ssa::back::write::OngoingCodegen<B>::join::h53b4242b79f084c6
  12:        0x10ad334b8 - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::join_codegen_and_link::h77646acf179f0157
  13:        0x10787d412 - rustc_interface::queries::Query<T>::compute::hcdd982c847826dfb
  14:        0x10793b60c - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::link::h7f38e8cb9157a4c4
  15:        0x1077affb4 - rustc_interface::interface::run_compiler_in_existing_thread_pool::hb34e03551dcdb203
  16:        0x1077e4794 - std::thread::local::LocalKey<T>::with::h53a41a5c8d10a0cc
  17:        0x1077fa6a8 - syntax::with_globals::hfd9982c3b8670378
  18:        0x10778b5d7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h85d75ba65de8ba19
  19:        0x10a1a8d2f - __rust_maybe_catch_panic
  20:        0x1077b24d7 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd194e59927da854d
  21:        0x10a17ccfe - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hacc9598ae4aad64e
  22:        0x10a1a7b3e - std::sys::unix::thread::Thread::new::thread_start::ha775066dcca59bc1
  23:     0x7fff7c8392eb - _pthread_body
  24:     0x7fff7c83c249 - _pthread_start
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.38.0-nightly (04b88a9eb 2019-07-29) running on x86_64-apple-darwin

note: compiler flags: -C opt-level=3 -C panic=abort -C lto -C incremental -C link-arg=--export-table -C link-arg=--export=__heap_base --crate-type cdylib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `node-runtime-wasm`.

To learn more, run the command again with --verbose.
```

**Comment by bkchr** [comment] 2019-07-31 20:23
This is an internal compiler error. What should we do?
If you want to get this solved, please post it into rust repository.
As we can not do anything, I will close this issue.

**Closed by bkchr** 2019-07-31 20:23 UTC

**Comment by kianenigma** [comment] 2019-08-01 07:43
True that it seems to be unrelated.

Can you please:

1- Stash and reset all your changes and confirm that this compiler panic comes IFF you make changes to your codebase. In that case, it might be worth investigating more.

2- as a long shot I would try reinstalling the entire rustc toolchain and LLVM (just because the name is in the error messages. Not solid reason)

**Comment by mattrutherford** [comment] 2019-08-01 09:03
> 1- Stash and reset all your changes and confirm that this compiler panic comes IFF you make changes to your codebase. In that case, it might be worth investigating more.

Yes, have tried with fresh master - and it must be a change in srml module to cause this problem; changes elsewhere in substrate are fine.

> 2- as a long shot I would try reinstalling the entire rustc toolchain and LLVM (just because the name is in the error messages. Not solid reason)

I'll try this, actually seems like it's worth the effort.

FWIW, I opened the issue for visibility to see if anyone else had experienced and also to try and find a workaround, until it's fixed in rustc.

**Comment by bkchr** [comment] 2019-08-01 09:17
If the issue is not opened in the rustc issue tracker, it will probably not be fixed. 

We are already having so many open issues, I don't want to have stuff in here that we can not fix.

**Comment by kianenigma** [comment] 2019-08-01 11:23
> Yes, have tried with fresh master - and it must be a change in srml module to cause this problem; changes elsewhere in substrate are fine.

Then you should also post your diff here. Someone might know what you are doing wrong.

> We are already having so many open issues, I don't want to have stuff in here that we can not fix.

Agreed.

**Comment by bkchr** [comment] 2019-08-01 11:44
@kianenigma This is an internal compiler error. He has not done anything wrong.
