### ISSUE TITLE
snapshot restoration failed: ApplySnapshotFailed & Writing a telemetry log took more than 50ms

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#4676] opened 2020-01-20 07:09 UTC
Beginning of the problem:

```
node_1  | 2020-01-17 16:26:28 Starting consensus session on top of parent 0xc87e729b8f5a13afa57075895aebec35ab4354121f28448479af5015584d8431
node_1  | 2020-01-17 16:26:28 Prepared block for proposing at 658759 [hash: 0x7d4722a618f8db78177db6f777ff2ded5afe21baafc4d682fe492abff3c53b40; parent_hash: 0xc87e…8431; extrinsics: [0xc878…5f78]]
node_1  | 2020-01-17 16:26:28 Pre-sealed block for proposal at 658759. Hash now 0xe2a19aa4fcbd1b2b36668997e271e096a743170f9432d341cdd2a0cf14469cce, previously 0x7d4722a618f8db78177db6f777ff2ded5afe21baafc4d682fe492abff3c53b40.
node_1  | 2020-01-17 16:26:28 Imported #658759 (0xe2a1…9cce)
node_1  | 2020-01-17 16:26:28 Polling the telemetry took more than 200ms
node_1  | 2020-01-17 16:26:29 Idle (1 peers), best: #658759 (0xe2a1…9cce), finalized #658757 (0x1745…3b84), ⬇ 0.1kiB/s ⬆ 0.7kiB/s
node_1  | 2020-01-17 16:26:32 Starting consensus session on top of parent 0xe2a19aa4fcbd1b2b36668997e271e096a743170f9432d341cdd2a0cf14469cce
node_1  | 2020-01-17 16:26:32 Prepared block for proposing at 658760 [hash: 0x34ed15c1a5b22ebbd629fd2a2c90541f0f0e9ab4beec64debbee2050e63622d1; parent_hash: 0xe2a1…9cce; extrinsics: [0x2cc0…7986]]
node_1  | 2020-01-17 16:26:32 Pre-sealed block for proposal at 658760. Hash now 0x0a2ff91cb5205ecaf4cf288838e500c5641c19ab5e8e51c21a3eafe50a1c0f06, previously 0x34ed15c1a5b22ebbd629fd2a2c90541f0f0e9ab4beec64debbee2050e63622d1.
node_1  | 2020-01-17 16:26:32 Imported #658760 (0x0a2f…0f06)
node_1  | 2020-01-17 16:26:32 Polling the telemetry took more than 200ms
node_1  | 2020-01-17 16:26:34 Idle (1 peers), best: #658760 (0x0a2f…0f06), finalized #658759 (0xe2a1…9cce), ⬇ 0.1kiB/s ⬆ 0.7kiB/s
node_1  | 2020-01-17 16:26:36 Starting consensus session on top of parent 0x0a2ff91cb5205ecaf4cf288838e500c5641c19ab5e8e51c21a3eafe50a1c0f06
node_1  | 2020-01-17 16:26:36 Prepared block for proposing at 658761 [hash: 0x2f0ae2ce707fd106acaa2a370e1ed3d5999cfb22e047fe8b8af4183a0029c8b3; parent_hash: 0x0a2f…0f06; extrinsics: [0x2d9d…07cd]]
node_1  | 2020-01-17 16:26:36 Pre-sealed block for proposal at 658761. Hash now 0x38c8b0bd2010b12e00925c81af528db38ec1c9d77c0a6f5a0cdc2f519729773b, previously 0x2f0ae2ce707fd106acaa2a370e1ed3d5999cfb22e047fe8b8af4183a0029c8b3.
node_1  | 2020-01-17 16:26:36 Imported #658761 (0x38c8…773b)
node_1  | 2020-01-17 16:26:36 Polling the telemetry took more than 200ms
node_1  | 2020-01-17 16:26:39 Idle (1 peers), best: #658761 (0x38c8…773b), finalized #658760 (0x0a2f…0f06), ⬇ 83 B/s ⬆ 0.6kiB/s
node_1  | 2020-01-17 16:26:40 snapshot restoration failed: ApplySnapshotFailed
node_1  | 2020-01-17 16:26:40 Unable to fetch epoch data at block 0x38c8b0bd2010b12e00925c81af528db38ec1c9d77c0a6f5a0cdc2f519729773b: InvalidAuthoritiesSet
node_1  | 2020-01-17 16:26:40 Polling the telemetry took more than 200ms
node_1  | 2020-01-17 16:26:44 snapshot restoration failed: ApplySnapshotFailed
node_1  | 2020-01-17 16:26:44 Unable to fetch epoch data at block 0x38c8b0bd2010b12e00925c81af528db38ec1c9d77c0a6f5a0cdc2f519729773b: InvalidAuthoritiesSet
node_1  | 2020-01-17 16:26:44 Polling the telemetry took more than 200ms
node_1  | 2020-01-17 16:26:44 Idle (1 peers), best: #658761 (0x38c8…773b), finalized #658760 (0x0a2f…0f06), ⬇ 38 B/s ⬆ 0.4kiB/s
node_1  | 2020-01-17 16:26:48 snapshot restoration failed: ApplySnapshotFailed
node_1  | 2020-01-17 16:26:48 Unable to fetch epoch data at block 0x38c8b0bd2010b12e00925c81af528db38ec1c9d77c0a6f5a0cdc2f519729773b: InvalidAuthoritiesSet
node_1  | 2020-01-17 16:26:48 Polling the telemetry took more than 200ms
node_1  | 2020-01-17 16:26:49 Idle (1 peers), best: #658761 (0x38c8…773b), finalized #658760 (0x0a2f…0f06), ⬇ 0 ⬆ 0.3kiB/s
node_1  | 2020-01-17 16:26:52 snapshot restoration failed: ApplySnapshotFailed
node_1  | 2020-01-17 16:26:52 Unable to fetch epoch data at block 0x38c8b0bd2010b12e00925c81af528db38ec1c9d77c0a6f5a0cdc2f519729773b: InvalidAuthoritiesSet
node_1  | 2020-01-17 16:26:54 Idle (1 peers), best: #658761 (0x38c8…773b), finalized #658760 (0x0a2f…0f06), ⬇ 0.2kiB/s ⬆ 0.6kiB/s
node_1  | 2020-01-17 16:26:56 snapshot restoration failed: ApplySnapshotFailed
node_1  | 2020-01-17 16:26:56 Unable to fetch epoch data at block 0x38c8b0bd2010b12e00925c81af528db38ec1c9d77c0a6f5a0cdc2f519729773b: InvalidAuthoritiesSet
node_1  | 2020-01-17 16:26:56 Polling the telemetry took more than 200ms
node_1  | 2020-01-17 16:26:59 Idle (1 peers), best: #658761 (0x38c8…773b), finalized #658760 (0x0a2f…0f06), ⬇ 62 B/s ⬆ 0.4kiB/s
node_1  | 2020-01-17 16:27:00 snapshot restoration failed: ApplySnapshotFailed
node_1  | 2020-01-17 16:27:00 Unable to fetch epoch data at block 0x38c8b0bd2010b12e00925c81af528db38ec1c9d77c0a6f5a0cdc2f519729773b: InvalidAuthoritiesSet
```

Eventually the node hangs and not responsible. i.e. RPC calls got timeout.

```
node_1  | 2020-01-20 06:28:04 snapshot restoration failed: ApplySnapshotFailed
node_1  | 2020-01-20 06:28:04 Unable to fetch epoch data at block 0x38c8b0bd2010b12e00925c81af528db38ec1c9d77c0a6f5a0cdc2f519729773b: InvalidAuthoritiesSet
node_1  | 2020-01-20 06:28:06 snapshot restoration failed: ApplySnapshotFailed
node_1  | 2020-01-20 06:28:06 Unknown error: Client(Execution(Other("ApplySnapshotFailed")))
node_1  | 2020-01-20 06:28:06 Idle (1 peers), best: #658761 (0x38c8…773b), finalized #658760 (0x0a2f…0f06), ⬇ 37 B/s ⬆ 0.2kiB/s
node_1  | 2020-01-20 06:28:08 snapshot restoration failed: ApplySnapshotFailed
node_1  | 2020-01-20 06:28:08 Unable to fetch epoch data at block 0x38c8b0bd2010b12e00925c81af528db38ec1c9d77c0a6f5a0cdc2f519729773b: InvalidAuthoritiesSet
node_1  | 2020-01-20 06:28:12 snapshot restoration failed: ApplySnapshotFailed
node_1  | 2020-01-20 06:28:12 Unable to fetch epoch data at block 0x38c8b0bd2010b12e00925c81af528db38ec1c9d77c0a6f5a0cdc2f519729773b: InvalidAuthoritiesSet
node_1  | 2020-01-20 06:28:12 Idle (0 peers), best: #658761 (0x38c8…773b), finalized #658760 (0x0a2f…0f06), ⬇ 8 B/s ⬆ 56 B/s
node_1  | 2020-01-20 06:28:16 snapshot restoration failed: ApplySnapshotFailed
node_1  | 2020-01-20 06:28:16 Unable to fetch epoch data at block 0x38c8b0bd2010b12e00925c81af528db38ec1c9d77c0a6f5a0cdc2f519729773b: InvalidAuthoritiesSet
node_1  | 2020-01-20 06:28:17 Idle (0 peers), best: #658761 (0x38c8…773b), finalized #658760 (0x0a2f…0f06), ⬇ 0.2kiB/s ⬆ 0.2kiB/s
node_1  | 2020-01-20 06:28:20 snapshot restoration failed: ApplySnapshotFailed
node_1  | 2020-01-20 06:28:20 Unable to fetch epoch data at block 0x38c8b0bd2010b12e00925c81af528db38ec1c9d77c0a6f5a0cdc2f519729773b: InvalidAuthoritiesSet
node_1  | 2020-01-20 06:28:22 Idle (1 peers), best: #658761 (0x38c8…773b), finalized #658760 (0x0a2f…0f06), ⬇ 0.4kiB/s ⬆ 0.4kiB/s
node_1  | 2020-01-20 06:28:24 snapshot restoration failed: ApplySnapshotFailed
node_1  | 2020-01-20 06:28:24 Unable to fetch epoch data at block 0x38c8b0bd2010b12e00925c81af528db38ec1c9d77c0a6f5a0cdc2f519729773b: InvalidAuthoritiesSet
node_1  | 2020-01-20 06:28:28 snapshot restoration failed: ApplySnapshotFailed
node_1  | 2020-01-20 06:28:28 Unable to fetch epoch data at block 0x38c8b0bd2010b12e00925c81af528db38ec1c9d77c0a6f5a0cdc2f519729773b: InvalidAuthoritiesSet
node_1  | 2020-01-20 06:28:28 Idle (1 peers), best: #658761 (0x38c8…773b), finalized #658760 (0x0a2f…0f06), ⬇ 95 B/s ⬆ 0.5kiB/s
node_1  | 2020-01-20 06:28:32 snapshot restoration failed: ApplySnapshotFailed
node_1  | 2020-01-20 06:28:32 Unable to fetch epoch data at block 0x38c8b0bd2010b12e00925c81af528db38ec1c9d77c0a6f5a0cdc2f519729773b: InvalidAuthoritiesSet
node_1  | 2020-01-20 06:28:33 Idle (1 peers), best: #658761 (0x38c8…773b), finalized #658760 (0x0a2f…0f06), ⬇ 25 B/s ⬆ 0.5kiB/s
node_1  | 2020-01-20 06:28:36 snapshot restoration failed: ApplySnapshotFailed
node_1  | 2020-01-20 06:28:36 Unable to fetch epoch data at block 0x38c8b0bd2010b12e00925c81af528db38ec1c9d77c0a6f5a0cdc2f519729773b: InvalidAuthoritiesSet
node_1  | 2020-01-20 06:28:40 Polling the telemetry took more than 200ms
node_1  | 2020-01-20 06:30:15 Writing a telemetry log took more than 50ms
node_1  | Encountered an error: broken pipe
node_1  | Enable a logger to see more information.
node_1  | 2020-01-20 06:30:47 Writing a telemetry log took more than 50ms
node_1  | 2020-01-20 06:32:18 Writing a telemetry log took more than 50ms
node_1  | 2020-01-20 06:33:56 Writing a telemetry log took more than 50ms
node_1  | 2020-01-20 06:35:02 Writing a telemetry log took more than 50ms
node_1  | 2020-01-20 06:36:21 Writing a telemetry log took more than 50ms
node_1  | 2020-01-20 06:37:20 Writing a telemetry log took more than 50ms
node_1  | 2020-01-20 06:38:51 Writing a telemetry log took more than 50ms
node_1  | 2020-01-20 06:39:59 Writing a telemetry log took more than 50ms
node_1  | 2020-01-20 06:41:21 Writing a telemetry log took more than 50ms
node_1  | 2020-01-20 06:43:04 Writing a telemetry log took more than 50ms
node_1  | 2020-01-20 06:44:37 Writing a telemetry log took more than 50ms
node_1  | 2020-01-20 06:46:17 Writing a telemetry log took more than 50ms
```

Seems perfectly fine after restart.

Using this version https://github.com/AcalaNetwork/Acala/tree/1ead107e188cdcd4c24e51d6153150c4aff439c6

**Comment by bkchr** [comment] 2020-01-20 09:05
CC @pepyakin

**Comment by pepyakin** [comment] 2020-01-20 13:45
Duplicate of #3780

According to my investigations so far, this is not the source of the problem but rather a symptom. It can happen due to several reasons, mainly running out-of-memory (or reserving too much memory allowed per process) and reaching the maximum number of memory mappings per process (the limit on linux can be checked by executing `sysctl vm.max_map_count`).

Looking at the logs (i.e. `Polling the telemetry took more than 200ms` and `Writing a telemetry log took more than 50ms`) speaks for this.

**Closed by pepyakin** 2020-01-20 13:45 UTC

**Comment by xlc** [comment] 2020-01-20 21:06
Thanks for the explanation @pepyakin. Currently I have `vm.max_map_count = 65530`, is it enough? 

It took 4 days to have this problem, does it indicates some resource leak? Do you recommend any more logging so better diagnostic this issue if it happens again?

**Comment by pepyakin** [comment] 2020-01-20 22:20
65530  - this is default. 

You can use `pmap <pid>` or `cat /proc/<pid>/maps` to check the current (number of) mappings used by the stuck process. That would help. Besides that the resources used by the substrate node (at least VIRT, RES), general memory pressure, `ulimit -a`.

**Comment by xlc** [comment] 2020-01-20 23:10
Oh I forget to say the node is running inside docker if that matters. I have already restarted the node. Will get all the details if it happens again.
