### ISSUE TITLE
CI failed due to timeout

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#2336] opened 2019-04-21 12:11 UTC
> test chain_spec::tests::test_connectivity ... test chain_spec::tests::test_connectivity has been running for over 60 seconds
Pulling docker image gitlab/gitlab-runner-helper:x86_64-4745a6f3 ...
ERROR: Job failed: execution took longer than 1h0m0s seconds

https://gitlab.parity.io/parity/substrate/-/jobs/140613

Triggered by this PR #2331 which is very unlikely break the connectivity test

**Comment by bkchr** [comment] 2019-04-21 18:34
That is just a flaky test.

@tomaka any idea?

**Comment by xlc** [comment] 2019-04-22 22:49
Maybe relates to me making multiple commits in a short amount of time (via GitHub commit suggestion feature) and each commit triggers a new build so multiple tests are running at same time?

**Comment by bkchr** [comment] 2019-04-23 06:48
No, that is just a test that deadlocks sometimes.

**Comment by tomaka** [comment] 2019-04-23 11:50
Might be https://github.com/libp2p/rust-libp2p/issues/1053

**Comment by tomaka** [comment] 2019-04-23 13:23
I clearly don't have time to waste 20 more hours into finding the cause of connectivity issues. I'd rather spend this time continuing the networking changes that I've been wanting to do for 3 months now.

**Comment by folsen** [comment] 2019-06-04 15:51
@xlc we've fixed several of these over the past couple of months, are you running in to any of these anymore?

**Comment by TriplEight** [comment] 2019-06-04 18:57
that could have happened because of busy gitlab-runners, but I'll investigate this test's behaviour.

**Comment by tomaka** [comment] 2019-07-24 11:19
This hasn't happened for a while, so I'm going to close this :+1:

**Closed by tomaka** 2019-07-24 11:19 UTC
Labels: F2-bug 🐜, F4-tests 🎯
