### ISSUE TITLE
Add support for other Hashing algorithms

### ISSUE THREAD

**Issue by fubuloubu** [paritytech/substrate#4113] opened 2019-11-15 23:14 UTC
I looked into what it would take to implement an alternative to the `sr-primitives::traits::BlakeTwo256` hasher. It seems like while attempts were made at making the hashing aglorithm fully configurable, there is a pervasive assumption that Blake2 should be used throughout the codebase (Storage, Consensus, etc.). I could be wrong, but it looks like it would take a significant amount of work to implement an alternative that thoroughly reconfigures a substrate project to the user's desired hashing function.

I was curious if there are plans to make it fully possible to configure the hashing function used across the codebase through a genericized typing, namely the keccak256, sha256, and sha3 algorithms would be helpful.

**Comment by bkchr** [comment] 2019-11-16 07:25
That is basically a duplicate of https://github.com/paritytech/substrate/issues/3624

To give you an info on the status, I already have a local branch where I remove all these `Hash=H256` and `Hasher=Blake2Hasher`. The work was done in the context of another pr. I hope to have this ready in the next days. After this pr is closed, it will require another pr to make the interface between the runtime and the host agnostic to the hash. However, that should be rather easy.

**Closed by bkchr** 2019-11-16 07:25 UTC

**Comment by fubuloubu** [comment] 2019-11-16 13:59
Awesome, thanks for the link!
