### ISSUE TITLE
staking reward event missing

### ISSUE THREAD

**Issue by freehere107** [paritytech/substrate#9602] opened 2021-08-23 02:55 UTC
When subscan index reward event, we found some reward event missing 

e.g.
https://kusama.subscan.io/extrinsic/5750546-1

batch index 16 payout_stakers 

``FyonP9C4fmBgD5KA9Rnu2smxBzbsSgUbSTqq9XmGJG2bm2s`` staking.reward event ``is not sent``

account balance change 

block  5750546 hash 0x5283cbd7c25eeed33c249d954fe44af06eccb4adf4ff5193305e885bea46780d
```
{
  "nonce": 6,
  "refcount": 3,
  "data": {
    "free": "1281559742453",
    "reserved": "0",
    "miscFrozen": "200000000000",
    "feeFrozen": "200000000000"
  }
}
```

block  5750547 hash 0x71fdfa805e3b9ce5e0892cd8e390cfc6ffc90e79b28e4371c8b7230660941a60

```
{
  "nonce": 6,
  "refcount": 3,
  "data": {
    "free": "1312531337738",
    "reserved": "0",
    "miscFrozen": "200000000000",
    "feeFrozen": "200000000000"
  }
}
```

**Comment by bkchr** [comment] 2021-08-23 07:39
CC @kianenigma

**Comment by kianenigma** [comment] 2021-08-23 10:06
not sure what could be the cause. What was the validator's own stash compared to the total backing (`exposure.own / exposure.total` prior to reward)? if this value is too small to fit in `Perbill`, then the validators' payout is zero. This is the code at kusama runtime 2026

https://github.com/paritytech/substrate/blob/668ecade60abe5a644868aefd3d231c9839fe652/frame/staking/src/lib.rs

If you are keen, you can re-execute the same old block with `try-runtime execute-block` sub-command. You need to have a local substrate+polkadot repo that is pointing to the above commit (polkadot is at release 8.26, with substrate dependencies overriden to a local repo pointing to commit `668ecade60abe5a644868aefd3d231c9839fe652`). Then you can add some logs, and re-execute the block to see what happened exactly.

**Comment by AurevoirXavier** [comment] 2021-08-24 11:01
https://github.com/paritytech/substrate/blob/668ecade60abe5a644868aefd3d231c9839fe652/frame/staking/src/lib.rs#L2302-L2303

**Comment by shawntabrizi** [comment] 2021-08-24 13:02
Closing this since this is the answer ^

**Closed by shawntabrizi** 2021-08-24 13:02 UTC
Labels: Z0-unconfirmed

**Comment by freehere107** [comment] 2021-09-07 03:03
@shawntabrizi I found an new issue

https://polkadot.subscan.io/extrinsic/333797-3

lack some nominators reward event

I saved era 1 validator 16DKyH4fggEXeGwCytqM19e9NFGkgR2neZPDJ5ta8BKpPbPK nominators

```json
{
	"data":
	[
		{
			"era": 1,
			"validator_stash": "e693f8c8c6043a5d8c8ed64d56523d157625011947a8a79881987d9e9100963a",
			"nominator_stash": "a6ff9f3390c3e28e47d5eb35081d2bff9ed3a3db244c46b29ed0bd09adc32f2b",
			"bonded": 80000000000000
		},
		{
			"era": 1,
			"validator_stash": "e693f8c8c6043a5d8c8ed64d56523d157625011947a8a79881987d9e9100963a",
			"nominator_stash": "b067ff52f26cc4bfacba52fffdb4e2c316a63a5fd1a833e68b216cd79802d547",
			"bonded": 1900000000000
		},
		{
			"era": 1,
			"validator_stash": "e693f8c8c6043a5d8c8ed64d56523d157625011947a8a79881987d9e9100963a",
			"nominator_stash": "24aee8cd61a0e8cbc769c9ca7a0eb49bca6e8ad0207db2180501755bd546de4a",
			"bonded": 155000000000000
		},
		{
			"era": 1,
			"validator_stash": "e693f8c8c6043a5d8c8ed64d56523d157625011947a8a79881987d9e9100963a",
			"nominator_stash": "ce4e902b421071b4825e6c630d14614e6021f42806546f390d8b61c328d55073",
			"bonded": 2995000000000000
		},
		{
			"era": 1,
			"validator_stash": "e693f8c8c6043a5d8c8ed64d56523d157625011947a8a79881987d9e9100963a",
			"nominator_stash": "4263bb05caff304086fb08790ff345aac33cbef0eeb795be86fe796e9e5dd917",
			"bonded": 45000000000000
		},
		{
			"era": 1,
			"validator_stash": "e693f8c8c6043a5d8c8ed64d56523d157625011947a8a79881987d9e9100963a",
			"nominator_stash": "9008091e2d1fb20e6d6a46c0d66591c9b00b73ea42386c0897dfdd5327c15531",
			"bonded": 99500000000000
		},
		{
			"era": 1,
			"validator_stash": "e693f8c8c6043a5d8c8ed64d56523d157625011947a8a79881987d9e9100963a",
			"nominator_stash": "5075a1c853e34a1d380591c710d35608dead70ea561e4d6a8bb35639514bc305",
			"bonded": 2995000000000000
		},
		{
			"era": 1,
			"validator_stash": "e693f8c8c6043a5d8c8ed64d56523d157625011947a8a79881987d9e9100963a",
			"nominator_stash": "7a56dc6e96af40fefe5799aed949f2c53c7fe497f8d830320656dd6709fbde5b",
			"bonded": 2999999958993516
		},
		{
			"era": 1,
			"validator_stash": "e693f8c8c6043a5d8c8ed64d56523d157625011947a8a79881987d9e9100963a",
			"nominator_stash": "ac58e10e4125165d840d53169e111a4e76487f930d7bda577583f6bbf6db513b",
			"bonded": 19000000000000
		},
		{
			"era": 1,
			"validator_stash": "e693f8c8c6043a5d8c8ed64d56523d157625011947a8a79881987d9e9100963a",
			"nominator_stash": "7ccfc66f0b7e76f786bdcaadccc5171ec82d013ab65e33440fc6c1d92c07d521",
			"bonded": 100000000000000
		},
		{
			"era": 1,
			"validator_stash": "e693f8c8c6043a5d8c8ed64d56523d157625011947a8a79881987d9e9100963a",
			"nominator_stash": "de566e4f0d29c4bfeeb3d23a0a9f923fe62d7fc5bdf8c9afd75506bc8fe69a0e",
			"bonded": 212000000000000
		},
		{
			"era": 1,
			"validator_stash": "e693f8c8c6043a5d8c8ed64d56523d157625011947a8a79881987d9e9100963a",
			"nominator_stash": "843d4e47d482e526ae90e555d384f2f7bd4cdf0fba7d24518f278f5e2d132251",
			"bonded": 24007377737087053
		},
		{
			"era": 1,
			"validator_stash": "e693f8c8c6043a5d8c8ed64d56523d157625011947a8a79881987d9e9100963a",
			"nominator_stash": "28c5c756b5da7978e45b746ab840e8ac27df108750d5e2cbaf310232d3489421",
			"bonded": 34747798123140306
		}
	]
}
```
https://github.com/paritytech/substrate/blob/668ecade60abe5a644868aefd3d231c9839fe652/frame/staking/src/lib.rs#L2346

reward event locks 2 nominators reward event 
nominators pk:
``ce4e902b421071b4825e6c630d14614e6021f42806546f390d8b61c328d55073`` and 
 ``5075a1c853e34a1d380591c710d35608dead70ea561e4d6a8bb35639514bc305``

**Comment by shawntabrizi** [comment] 2021-09-07 05:27
Can you check if those nominators have set the reward destination to `None`:

```
RewardDestination::None => None,
```

This would result in no event.

**Comment by AurevoirXavier** [comment] 2021-09-07 05:32
> Can you check if those nominators have set the reward destination to `None`:
> 
> ```
> RewardDestination::None => None,
> ```
> 
> This would result in no event.

The runtime should correspond to this https://polkadot.subscan.io/extrinsic/0x334ee5ad2692e6e0fa538e2bcaf1f50aca82c6fd7a124e4d4933478fe8f22a5e?event=314201-3.

And there is no `RewardDestination::None` at that time I think.

**Comment by shawntabrizi** [comment] 2021-09-07 05:39
If it is an old runtime, I am not sure I can give a diagnosis easily cause i can only look at the current code.

Here is the logic for the current code:

```
			// We can now make nominator payout:
			if let Some(imbalance) = Self::make_payout(&nominator.who, nominator_reward) {
				// Note: this logic does not count payouts for `RewardDestination::None`.
				nominator_payout_count += 1;
				let e = Event::<T>::Rewarded(nominator.who.clone(), imbalance.peek());
				Self::deposit_event(e);
			}
```

So event is emitted as long as `make_payout` returns `Some`

```
	/// Actually make a payment to a staker. This uses the currency's reward function
	/// to pay the right payee for the given staker account.
	fn make_payout(stash: &T::AccountId, amount: BalanceOf<T>) -> Option<PositiveImbalanceOf<T>> {
		let dest = Self::payee(stash);
		match dest {
			RewardDestination::Controller => Self::bonded(stash)
				.and_then(|controller| Some(T::Currency::deposit_creating(&controller, amount))),
			RewardDestination::Stash => T::Currency::deposit_into_existing(stash, amount).ok(),
			RewardDestination::Staked => Self::bonded(stash)
				.and_then(|c| Self::ledger(&c).map(|l| (c, l)))
				.and_then(|(controller, mut l)| {
					l.active += amount;
					l.total += amount;
					let r = T::Currency::deposit_into_existing(stash, amount).ok();
					Self::update_ledger(&controller, &l);
					r
				}),
			RewardDestination::Account(dest_account) =>
				Some(T::Currency::deposit_creating(&dest_account, amount)),
			RewardDestination::None => None,
		}
	}
```

Here we see that `make_payout` can only return `None` at the bottom, or if `deposit_into_existing` fails.

**Comment by AurevoirXavier** [comment] 2021-09-07 05:44
Yes, we have found these 2 situations which could cause this issue.

@freehere107 Could you export `RewardDestination` data at that time?

**Comment by AurevoirXavier** [comment] 2021-09-07 05:47
Also, are their balances increased after block 333797?

**Comment by freehere107** [comment] 2021-09-07 05:51
> Yes, we have found these 2 situations which could cause this issue.
> 
> @freehere107 Could you export the `RewardDestination` data of these 2 accounts at that time?

Both are reward payee and both are controller

**Comment by freehere107** [comment] 2021-09-07 06:05
> Also, are their balances increased after block 333797?

no change

**Comment by AurevoirXavier** [comment] 2021-09-07 06:09
> > Also, are their balances increased after block 333797?
> 
> no change

Did you check the stash's balances or controller's?

**Comment by freehere107** [comment] 2021-09-07 06:30
> > > Also, are their balances increased after block 333797?
> > 
> > 
> > no change
> 
> Did you check the stash's balances or controller's?

yes, controller account, I query controller accountInfo failed in block 333797, It may be because of a dust account.
so ``deposit_into_existing`` fails

**Comment by AurevoirXavier** [comment] 2021-09-07 06:32
That makes sense and no reward had been dispatched.
