### ISSUE TITLE
Prevent possible RocksDb corruption by `benchmark-storage`

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#10998] opened 2022-03-09 12:38 UTC
The `benchmark-storage` command has a small possibility to corrupt a RocksDb snapshot, hence it should only be used on a backup.  
It would still be better to change the behaviour here, AFAIK a corruption can happen like this:  
1. KV pairs in the storage = [(`a`, `1u8`), (`b`, `2u8`)]
2. The benchmark generates the following random KV pairs [(`a`, `42u8`), (`b`, `1u8`)]
3. The value for `b` collides by chance with the value of the original value for `a`, since both are `1` in this example.
4. The benchmark writes the new values and then in the end cleans them up, in this case this would remove the original value of `a`, hence corrupting the state.

The fix is rather simple I think; basically checking which random values are already present in the Storage before the benchmark was run and then not deleting these.  

NOTE: This can only happen for RocksDb since ParityDb does ref-counting of values.

**Comment by hirschenberger** [comment] 2022-03-09 13:46
May I take over?

**Comment by ggwpez** [comment] 2022-03-09 16:36
@hirschenberger Oh yes sure!  

@cheme Is my summary or the problem/solution correct?

**Comment by cheme** [comment] 2022-03-09 16:55
That's basically it, but what matter is the encoded trie node stored, so it can only corrupt state N-1:

1. Block N  KV pairs in the trie = [(a, 1u8), (b, 2u8)], encoded trie node  in the storage [(H1_0, branch), (H2_0, leaf), (H3_0, leaf)]
2. Block N+1 KV pairs in the trie = [(a, 42u8), (b, 2u8)], encoded trie node in the storage [(H1_1, branch), (H2_1, leaf), (H3_0, leaf)]
3. The benchmark generates the following random KV pairs [(a, 1u8), (b, 1u8)]
4. state after applying bench: KV pairs [(a, 1u8), (b, 1u8)], encoded nodes [(H1_3, branch), (H2_0, leaf), (H3_1, leaf)]
    So we write an encoded node at H2_0 a second time, that is the collision.
    Then when rolling back the change we delete H2_0 and state at N is corrupted.

Also killing the process before rolling back bench changes also corrupt the db.

The fix solution is correct (but it is encoded nodes, not values). The issue is that recording already present node may change the result of the bench. 

Alternate fix, that also ensure no issue if revert is killed, could be to run the test in a new column that is a copy of the state column (the column itself is not that big), but rocksdb will require some migration code just to add this column, that is a bit awkward. Probably the first fix is better.

**Comment by hirschenberger** [comment] 2022-03-09 17:27
So if I understand correctly:

* I get all keys
* Call `storage_hash` on all of them and store the hashes in a blacklist-vec
* Then the bench is running
* Before actually deleting an entry, I also get the kv-hash and check if it is in the blacklist and if true, I do nothing.

**Comment by cheme** [comment] 2022-03-09 17:32
Oh could just execute twice :)

**Comment by ggwpez** [comment] 2022-03-10 11:21
> Oh could just execute twice :) (not commiting the payload and doing the db access for blacklist to remove first)

Okay... In the worst case we can still copy the whole database to a temporary directory, though that is a bit ugly.  

> we would need to check if there is already a encoded node in db (and don't rollback it in next commit if there was).

I think I get what you mean now; the blacklisting would indeed interfere with the benchmark.  
https://github.com/paritytech/substrate/pull/11004 is currently adding a warmup round for the write benchmark, whouch could probably be easily extended to do this blacklist tracking,

**Comment by hirschenberger** [comment] 2022-03-10 11:26
> > Oh could just execute twice :) (not commiting the payload and doing the db access for blacklist to remove first)
> 
> Okay... In the worst case we can still copy the whole database to a temporary directory, though that is a bit ugly.

...and may also end in different results if the temp-dir is on another drive with different IO characteristics.

> > we would need to check if there is already a encoded node in db (and don't rollback it in next commit if there was).
> 
> I think I get what you mean now; the blacklisting would indeed interfere with the benchmark. #11004 is currently adding a warmup round for the write benchmark, whouch could probably be easily extended to do this blacklist tracking,

What do you suggest how we proceed?

**Comment by cheme** [comment] 2022-03-10 12:45
> Okay... In the worst case we can still copy the whole database to a temporary directory, though that is a bit ugly.Okay... In the worst case we can still copy the whole database to a temporary directory, though that is a bit ugly.

Just the state colum (this bench only touch the state column). In this case not need to execute twice.

When I say execute twice it was the blacklist removal scenario, collect blacklist run after. But I realize now that the blacklist run, to be really pedantic would need to run before the warmup.

**Comment by ggwpez** [comment] 2022-03-10 12:48
I prototyped it but is is kinda complicated:  
```rust
// Generate all random values first.
let mut new_values = Vec::new();
for (_, original_v) in kvs.clone().iter() {
	let mut new_v = vec![0; original_v.len()];
	rng.fill_bytes(&mut new_v[..]);
	new_values.push(new_v);
}

// List of Kv pairs that should not be modified by the benchmark
// as to not corrupt the database.
let mut precious = Vec::new();

info!("Extracting precious nodes");
for ((k, _), new_v) in kvs.clone().iter().zip(new_values.clone().iter()) {
	let replace = vec![(k.as_ref(), Some(new_v.as_ref()))];
	let (_, mut stx) = trie.storage_root(replace.iter().cloned(), self.state_version());

	// Look at all keys that we would insert/remove.
	for (mut k, (v, rc)) in stx.drain().into_iter() {
		// TODO put this `if` in a new function please.
		if supports_rc {
			let _prefix = k.drain(0..k.len() - DB_HASH_LEN);
		}
		
		// We only look at insertions since we only remove our own insertions
		// after benchmarking a specific key.
		if rc > 0 {
			// Keys that are already in the DB before our modifications are precious. 
			if let Some(val) = db.get(state_col, k.as_ref()) {
				precious.push((k.clone(), val));
			}
		}
	}

	let tx = convert_tx::<Block>(stx.clone(), true, state_col, supports_rc);
	db.commit(tx).map_err(|e| format!("Writing to the Database: {}", e))?;
	let tx = convert_tx::<Block>(stx.clone(), false, state_col, supports_rc);
	db.commit(tx).map_err(|e| format!("Writing to the Database: {}", e))?;
}

// After the benchmark is done, all keys would need to re-inserted with db.commit.
```

Typing this out makes me realize that it is probably easier to clone the whole column as @cheme said and then restore it at the end.

**Comment by cheme** [comment] 2022-03-10 13:00
Actually I thought of running the bench on the cloned db, so it cannot be corrupted, just dropped at the end. But it can be a bit problematic: there is not access to the db implementation from the method (we onl ysee the db trait), so easy thought would be to instantiate the whole process on the db clone, but then to resolve the state content outside the state column is needed.
I end up, finding the blacklist solution more pragmatic.

Note that in your proto the function should not call `db.commit`, just return the list of existing db value (`precious`) and `new_values` as input fo the actual bench. But you probably forgot to remove the code :)

**Comment by hirschenberger** [comment] 2022-03-11 10:10
Ok, so I'd try to start with @ggwpez 's code but I assume I have to wait till #11004 landed, right?

**Comment by ggwpez** [comment] 2022-03-11 10:24
> Ok, so I'd try to start with @ggwpez 's code but I assume I have to wait till #11004 landed, right?

Yea that is probably a good idea. Should hopefully merge today.

**Comment by hirschenberger** [comment] 2022-03-11 16:27
BTW: How about avoiding collisions at all by replacing kvs that are in the db with a new kv pair that does not collide?

**Comment by ggwpez** [comment] 2022-03-11 16:47
> BTW: How about avoiding collisions at all by replacing kvs that are in the db with a new kv pair that does not collide?

:+1: but I think they still need to be ran through the `storage_root` method before checking if they are present in the DB.  
Personally I thought this issue would be much easier :disappointed: sorry @hirschenberger. I will mention you when there is another good issue.

**Comment by hirschenberger** [comment] 2022-03-11 16:48
Np, I'm currently working on it. Let me see if I can solve it.

**Comment by hirschenberger** [comment] 2022-03-11 17:25
How about this? It may not be the most idiomatic rust code with the loop-label but it saves a bool var. But I can also refactor the inner check to a `fn db_contains(kv) -> bool`


```rust
        // Generate all random values first; Make sure there are no collisions with existing
        // db entries.
        let mut new_values = Vec::with_capacity(kvs.len());
        for (k, original_v) in kvs.iter() {
            'retry: loop {
                let mut new_v = vec![0; original_v.len()];
                rng.fill_bytes(&mut new_v[..]);
                let new_kv = vec![(k.as_ref(), Some(new_v.as_ref()))];
                let (_, mut stx) = trie.storage_root(new_kv.iter().cloned(), self.state_version());
                for (mut k, (_, rc)) in stx.drain().into_iter() {
                    if supports_rc {
                        let _prefix = k.drain(0..k.len() - DB_HASH_LEN);
                    }

                    if rc > 0 {
                        if db.get(state_col, k.as_ref()).is_some() {
                            continue 'retry;
                        }
                    }
                }
                new_values.push(new_v);
                break;
            }
        }
```

**Comment by cheme** [comment] 2022-03-11 17:44
Looks like it's going in the right direction, just the thing you need to store are not 'new_values' but 'existing_values', it's a black list of content that should not be rollback at the very end of the bench in second commit_tx.
Also the same new_v will need to be use in the bench afterward, so they will need to be stored out of the loop.

**Comment by cheme** [comment] 2022-03-11 18:05
if you skip key that collide (so in the first commit_tx), you will change the bench result. But tbh, the collision should be quiet rare.

**Closed** 2022-03-16 16:05 UTC
Labels: I3-annoyance 🦟, P7-nicetohave, Q3-medium
