### ISSUE TITLE
grandpa consensus will not be finalized

### ISSUE THREAD

**Issue by gguoss** [paritytech/substrate#1766] opened 2019-02-12 10:29 UTC
Specify the pruning mode, a number of blocks to keep or 'archive'. Default is 256. More than 256 blocks will cause the grandpa's StoredPendingChange to be pruned, and then the grandpa consensus will not be finalized.

**Comment by arkpar** [comment] 2019-02-12 10:43
The default has been recently changed to 4096. This is an issue though.

**Comment by arkpar** [comment] 2019-02-12 10:51
Duplicate of #1652

**Closed by arkpar** 2019-02-12 10:51 UTC
