### ISSUE TITLE
confusing docs linking

### ISSUE THREAD

**Issue by apopiak** [paritytech/substrate#6154] opened 2020-05-27 09:03 UTC
When following type links in the Rust docs, e.g. clicking on `Signature` in the `Sr25519` variant [here](https://crates.parity.io/sp_runtime/enum.MultiSignature.html#variants), the user is linked to the wrong Rust item, e.g. the
[`sp_runtime::testing::sr25519::Signature`](https://crates.parity.io/sp_runtime/testing/sr25519/struct.Signature.html ) instead of [`sp_core::sr25519::Signature`](https://crates.parity.io/sp_core/sr25519/struct.Signature.html).

**Comment by bkchr** [comment] 2020-05-27 15:34
This looks like a bug in `rustdoc`. We import the correct module, but it seems rustdoc gets confused because we also import the same module in our `testing` module. It would be nice if you could create a reproducible example and post the issue upstream. However, this issue is not Substrate related and thus, I will close it ;)

**Closed by bkchr** 2020-05-27 15:34 UTC
