### ISSUE TITLE
The authority's block forks and reorganizes, and there is a problem with the state.

### ISSUE THREAD

**Issue by gguoss** [paritytech/substrate#2637] opened 2019-05-21 08:42 UTC
When a forkback rollback occurs, the validator will panic when the block just emerging, the state will be inconsistent, and there is no way to repair it, except that the data is resynchronized.

==============================
2019-05-21 01:23:20.287 INFO [runtime|xrml_xsystem] height:228148, blockproducer: 5f423525f65a2b6eb5866a9159dee5edebb00c85e43147bf02ef1921590c4df1 (5EDc5F7D...)|name:buildlinks
2019-05-21 01:23:20.299 INFO Prepared block for proposing at 228148 [hash: 0x013b3784231b17eaa0d2606e7abdd6f67006d3f005c23ca2025e11b6a385aad5; parent_hash: 0x587d…dcc3; extrinsics: [0xa68d…1634, 0x1286…5135, 0x877d…880c]]
2019-05-21 01:23:20.300 INFO Pre-sealed block for proposal at 228148. Hash now 0xc9bc302d194dd76f46660df4f4ddb4fa05b485500ea198e0330ebfbe47ecaf55, previously 0x013b3784231b17eaa0d2606e7abdd6f67006d3f005c23ca2025e11b6a385aad5.
2019-05-21 01:23:20.315 INFO [runtime|xrml_xsystem] height:228148, blockproducer: 5f423525f65a2b6eb5866a9159dee5edebb00c85e43147bf02ef1921590c4df1 (5EDc5F7D...)|name:buildlinks
2019-05-21 01:23:20.317 INFO Imported #228148 (0xc9bc…af55)
2019-05-21 01:23:21.616 INFO Idle (14 peers), best: #228148 (0xc9bc…af55), finalized #228142 (0x2d9a…0f24), ⬇ 7.6kiB/s ⬆ 6.7kiB/s
2019-05-21 01:23:21.994 INFO [runtime|xrml_xsystem] height:228148, blockproducer: 0b257ad398a034bec8e2020bf0d8f8102cdeb8a0ba21455e11d8df9a44636791 (5CKKWyrD...)|name:Amazon
2019-05-21 01:23:21.999 INFO Reorg from #228148,0xc9bc…af55 to #228148,0x523c…ef20, common ancestor #228147,0x587d…dcc3
2019-05-21 01:23:21.1000 INFO Imported #228148 (0x523c…ef20)

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h393751b981ef0a09 (0x563c473dd2df)
   1: std::panicking::rust_panic_with_hook::h7efe5cde925ada1b (0x563c475b3f58)
             at src/libstd/panicking.rs:478
   2: std::panicking::continue_panic_fmt::h39e7c865f7254bbb (0x563c475b39f1)
             at src/libstd/panicking.rs:381
   3: rust_begin_unwind (0x563c475b38d5)
   4: core::panicking::panic_fmt::h2cf06a34c3143265 (0x563c475cddac)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::h35e42733c847a8de (0x563c4646a09d)
   6: <substrate_state_machine::ext::Ext<H,B,T,O> as substrate_state_machine::Externalities<H>>::storage::h8a9eb481f7268af5 (0x563c466884c4)
   7: std::thread::local::LocalKey<T>::with::hf03c34159e32754c (0x563c473c0ad2)
   8: sr_io::read_storage::h1f4d3f3022eb6b14 (0x563c473c02cb)
   9: <srml_system::RandomMaterial<T> as srml_support::storage::hashed::generator::StorageValue<(i8, alloc::vec::Vec<<T as srml_system::Trait>::Hash>)>>::get::hf0545d1f8e375809 (0x563c47132ab5)
  10: srml_system::Module<T>::initialize::hb229a71918620f18 (0x563c4712cf51)
  11: chainx_runtime::xexecutive::Executive<System,Block,Context,Payment,AllModules>::initialize_block::hfdfe39c22f6ff0ec (0x563c471edc33)
  12: substrate_client::runtime_api::runtime_decl_for_Core::initialize_block_native_call_generator::{{closure}}::ha5927f8a5dd49dfc (0x563c4676d0b8)
  13: std::panicking::try::do_call::h076a175b21336e67 (0x563c4680183b)
  14: __rust_maybe_catch_panic (0x563c475b9989)
             at src/libpanic_unwind/lib.rs:85
  15: std::thread::local::LocalKey<T>::with::hcd3d3b9cbf003fec (0x563c467ec9fc)
  16: <substrate_executor::native_executor::NativeExecutor<D> as substrate_state_machine::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call::h7ca2922c0f0b1bd5 (0x563c4679b24b)
  17: substrate_state_machine::StateMachine<H,B,T,O,Exec>::execute_aux::h6857825cfe5cab6f (0x563c4684493d)
  18: substrate_state_machine::StateMachine<H,B,T,O,Exec>::execute_using_consensus_failure_handler::hafa34b1accccb9e2 (0x563c468bccff)
  19: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::h9f3c4b996ce29567 (0x563c46afd7e7)
  20: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::h889d4c027680aa81 (0x563c46984986)
  21: substrate_client::runtime_api::runtime_decl_for_Core::initialize_block_call_api_at::hfd38522b6295ed1b (0x563c464f9114)
  22: substrate_client::runtime_api::Core::initialize_block::h6598d8f11ca8b120 (0x563c46a58905)
  23: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::hdf05e36c766b4c56 (0x563c46b06386)
  24: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::h95985b4285bd0ffc (0x563c46985009)
  25: substrate_offchain_primitives::runtime_decl_for_OffchainWorkerApi::offchain_worker_call_api_at::h3989e901064dd62a (0x563c46b12cf1)
  26: substrate_offchain_primitives::OffchainWorkerApi::offchain_worker_with_context::h44041ca798a19e58 (0x563c46a6c3c6)
  27: substrate_offchain::OffchainWorkers<C,Block>::on_block_imported::h05e84cc535c484ea (0x563c469bb591)
  28: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll::hf84b1f6c59d4f0e8 (0x563c466db1b1)
  29: <futures::future::select::Select<A,B> as futures::future::Future>::poll::hd93798b3e7d08a81 (0x563c4654637b)
  30: futures::future::chain::Chain<A,B,C>::poll::h3ffa31c1e98ba150 (0x563c46a94d58)
  31: futures::task_impl::std::set::h51310ba5a7cb7e45 (0x563c472aa031)
  32: futures::task_impl::Spawn<T>::poll_future_notify::hed4ced7fac6a258e (0x563c472a5985)
  33: std::panicking::try::do_call::hc66564ccd455e604 (0x563c472abdc0)
  34: __rust_maybe_catch_panic (0x563c475b9989)
             at src/libpanic_unwind/lib.rs:85
  35: tokio_threadpool::task::Task::run::he6e140491fbd570f (0x563c472a5b88)
  36: tokio_threadpool::worker::Worker::run_task::h04d203ca541b381d (0x563c472a1584)
  37: tokio_threadpool::worker::Worker::run::h32316878b7a0730d (0x563c472a0a7d)
  38: tokio_trace_core::dispatcher::with_default::h3c1d781d98a93aee (0x563c4728ba36)
  39: std::thread::local::LocalKey<T>::with::h22879d5136114ca6 (0x563c4728b395)
  40: std::thread::local::LocalKey<T>::with::h0daff4824ab8e28f (0x563c4728b25d)
  41: std::thread::local::LocalKey<T>::with::hd048e65d26c91a36 (0x563c4728b593)
  42: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h5ce219ac059c4758 (0x563c4728ef86)
  43: std::thread::local::LocalKey<T>::with::h14a0072ab3f21c55 (0x563c472a90a2)
  44: std::thread::local::LocalKey<T>::with::h699d821d96611d2d (0x563c472a91dd)
  45: std::sys_common::backtrace::__rust_begin_short_backtrace::h5ee06633c6a139f5 (0x563c472a1e40)
  46: std::panicking::try::do_call::h1abddd92ef23d59e (0x563c472abd7b)
  47: __rust_maybe_catch_panic (0x563c475b9989)
             at src/libpanic_unwind/lib.rs:85
  48: core::ops::function::FnOnce::call_once{{vtable.shim}}::h3af84b72f879722d (0x563c472a2eff)
  49: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h74ec1c808eb1d6f6 (0x563c475a138e)
             at /rustc/8dd4aae9a83964cc08505da92d07ec68a3a2341d/src/liballoc/boxed.rs:704
  50: std::sys::unix::thread::Thread::new::thread_start::h5771ac597fbe512e (0x563c475b8c9f)
             at /rustc/8dd4aae9a83964cc08505da92d07ec68a3a2341d/src/liballoc/boxed.rs:704
      std::sys::unix::thread::Thread::new::thread_start::h5771ac597fbe512e
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h5771ac597fbe512e
             at src/libstd/sys/unix/thread.rs:79
  51: start_thread (0x7fba817f56b9)
  52: clone (0x7fba8131541c)
  53: <unknown> (0x0)

**Comment by rphmeier** [comment] 2019-05-21 22:05
cc @arkpar possible state is pruned too early or storage is not fully written somehow?

**Comment by JKingdom** [comment] 2019-05-22 02:06
additional:
we are ChainX team.
In our log, we print the block producer. In this panic, we notice that the panic only happen when the block producer just produce a block, then meet the reorganization block. 
for example,:
|_100_|_101_|_102_|_103_|
     A (reorganize)
     B
               C
when A producer a block 100, then B not receive block 100, and B produce block 100, C follow, than the A receive block 100 from B, reorganize self block, than panic

example:
node "keypool" producer block, then receive same height block from HashQuark, panic
```bash
########  keypool producer the block 257710
2019-05-21 19:09:24.608 INFO [runtime|xrml_xsystem] height:257710, blockproducer: b21245e96adadcd2c1cb2d4fcb19f8ce213fa5d8f8a91de637f44cce9254eb17 (5G6BosKu...)|name:keypool                                            
2019-05-21 19:09:24.616 INFO Prepared block for proposing at 257710 [hash: 0xb435320e7e3cf9ef5c6e9279d285c67d0276c7a22f2b7a831eb32e0042bc482c; parent_hash: 0x9c73¡­b7d4; extrinsics: [0xf611¡­87e0, 0x8989¡­06db, 0x4290¡­e$
21]]                                                                                                                                                                                                                     
2019-05-21 19:09:24.616 INFO Pre-sealed block for proposal at 257710. Hash now 0xa6023c5ccd6a7fdac0d061b84cf8995f24537773ac0c01127b93a7079b1427f2, previously 0xb435320e7e3cf9ef5c6e9279d285c67d0276c7a22f2b7a831eb32e00$
2bc482c.                                                                                                                                                                                                                 
2019-05-21 19:09:24.631 INFO [runtime|xrml_xsystem] height:257710, blockproducer: b21245e96adadcd2c1cb2d4fcb19f8ce213fa5d8f8a91de637f44cce9254eb17 (5G6BosKu...)|name:keypool                                            
2019-05-21 19:09:24.633 INFO Imported #257710 (0xa602¡­27f2)                  
########  then receive the block 257710 from name:HashQuark                                                                                                                                           
2019-05-21 19:09:27.618 INFO [runtime|xrml_xsystem] height:257710, blockproducer: f75d1c241c59e2a6a88efcf239df0eabb229b3697b4c844c788c9c51fcb25d2d (5Hf3LuqE...)|name:HashQuark                 
########  reorganization                         
2019-05-21 19:09:27.623 INFO Reorg from #257710,0xa602¡­27f2 to #257710,0x6cfe¡­6747, common ancestor #257709,0x9c73¡­b7d4                                                                                                  
2019-05-21 19:09:27.623 INFO Imported #257710 (0x6cfe¡­6747)                                                                                                                                                              
2019-05-21 19:09:27.772 WARN Error cleaning up pending extra data requests: UnfinalizedAncesto

######## panic
====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h393751b981ef0a09 (0x55574b64c2df)
   1: std::panicking::rust_panic_with_hook::h7efe5cde925ada1b (0x55574b822f58)
             at src/libstd/panicking.rs:478
   2: std::panicking::continue_panic_fmt::h39e7c865f7254bbb (0x55574b8229f1)
             at src/libstd/panicking.rs:381
   3: rust_begin_unwind (0x55574b8228d5)
```

other example:
node buildlinks producer a block 263345, then receive same block from other node, panic
```bash
2019-05-21 22:44:48.755 INFO Idle (14 peers), best: #263345 (0x1328…8f31), finalized #263341 (0x42eb…4632), ⬇ 7.3kiB/s ⬆ 6.2kiB/s
2019-05-21 22:44:48.882 INFO Starting consensus session on top of parent 0x1328dad6b60cb1d5b6d0c0178252f7fc121df2fb9b87d18266f6e866d7348f31
2019-05-21 22:44:48.907 INFO [runtime|xrml_xsystem] height:263346, blockproducer: 5f423525f65a2b6eb5866a9159dee5edebb00c85e43147bf02ef1921590c4df1 (5EDc5F7D...)|name:buildlinks
2019-05-21 22:44:48.922 INFO Prepared block for proposing at 263346 [hash: 0x2880a856fe784ac6712804ade8f9b3ca440bf8988c52b2f422c595e0b6ddcd75; parent_hash: 0x1328…8f31; extrinsics: [0x55c2…53ea, 0xa91b…63ee, 0x877d…880c, 0x4b85…2f6c, 0xd109…648d]]

######## node buildlinks produce block 263346
2019-05-21 22:44:48.923 INFO Pre-sealed block for proposal at 263346. Hash now 0x9ed7113907c86852f927af2ed1bcd24dbede40e8b78e68a23f42b97a3f169df4, previously 0x2880a856fe784ac6712804ade8f9b3ca440bf8988c52b2f422c595e0b6ddcd75.
2019-05-21 22:44:48.938 INFO [runtime|xrml_xsystem] height:263346, blockproducer: 5f423525f65a2b6eb5866a9159dee5edebb00c85e43147bf02ef1921590c4df1 (5EDc5F7D...)|name:buildlinks
### imported
2019-05-21 22:44:48.942 INFO Imported #263346 (0x9ed7…9df4)

######## and receive same height block 263346 from WTZ-Node
2019-05-21 22:44:51.106 INFO [runtime|xrml_xsystem] height:263346, blockproducer: e9a46e884246d95ef233197af64b9fb159fb53c790a5991f0b7a9710c7313d47 (5HM3rsmD...)|name:WTZ-Node
######## reorg
2019-05-21 22:44:51.108 INFO Reorg from #263346,0x9ed7…9df4 to #263346,0x0082…af6a, common ancestor #263345,0x1328…8f31
2019-05-21 22:44:51.108 INFO Imported #263346 (0x0082…af6a)
###### panic
====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h393751b981ef0a09 (0x56349cfb72df)
   1: std::panicking::rust_panic_with_hook::h7efe5cde925ada1b (0x56349d18df58)
             at src/libstd/panicking.rs:478
   2: std::panicking::continue_panic_fmt::h39e7c865f7254bbb (0x56349d18d9f1)
```

another example:
```bash
2019-05-21 01:23:07.375 INFO [runtime|xrml_xsystem] height:228147, blockproducer: 1dc2a0be7f483619c2808f8e02e862c822569f4115d2c306a3b5ee7363bf6245 (5Cjj4a75...)|name:Google
2019-05-21 01:23:07.377 INFO Imported #228147 (0x587d…dcc3)
2019-05-21 01:23:09.053 WARN Error cleaning up pending extra data requests: UnfinalizedAncestor
2019-05-21 01:23:09.452 WARN Error cleaning up pending extra data requests: UnfinalizedAncestor
2019-05-21 01:23:09.841 WARN Error cleaning up pending extra data requests: UnfinalizedAncestor
2019-05-21 01:23:10.237 WARN Error cleaning up pending extra data requests: UnfinalizedAncestor
2019-05-21 01:23:10.632 WARN Error cleaning up pending extra data requests: UnfinalizedAncestor
2019-05-21 01:23:11.023 WARN Error cleaning up pending extra data requests: UnfinalizedAncestor
2019-05-21 01:23:11.619 INFO Idle (14 peers), best: #228147 (0x587d…dcc3), finalized #228142 (0x2d9a…0f24), ⬇ 17.8kiB/s ⬆ 11.9kiB/s
2019-05-21 01:23:16.616 INFO Idle (14 peers), best: #228147 (0x587d…dcc3), finalized #228142 (0x2d9a…0f24), ⬇ 10.6kiB/s ⬆ 5.1kiB/s
####### buildlinks try to produce block 228148
2019-05-21 01:23:20.263 INFO Starting consensus session on top of parent 0x587df7435b5881d3470e6cdaeed17e6b2dc1c07ca1677357851d2c71eb20dcc3
2019-05-21 01:23:20.287 INFO [runtime|xrml_xsystem] height:228148, blockproducer: 5f423525f65a2b6eb5866a9159dee5edebb00c85e43147bf02ef1921590c4df1 (5EDc5F7D...)|name:buildlinks
2019-05-21 01:23:20.299 INFO Prepared block for proposing at 228148 [hash: 0x013b3784231b17eaa0d2606e7abdd6f67006d3f005c23ca2025e11b6a385aad5; parent_hash: 0x587d…dcc3; extrinsics: [0xa68d…1634, 0x1286…5135, 0x877d…880c]]
2019-05-21 01:23:20.300 INFO Pre-sealed block for proposal at 228148. Hash now 0xc9bc302d194dd76f46660df4f4ddb4fa05b485500ea198e0330ebfbe47ecaf55, previously 0x013b3784231b17eaa0d2606e7abdd6f67006d3f005c23ca2025e11b6a385aad5.
2019-05-21 01:23:20.315 INFO [runtime|xrml_xsystem] height:228148, blockproducer: 5f423525f65a2b6eb5866a9159dee5edebb00c85e43147bf02ef1921590c4df1 (5EDc5F7D...)|name:buildlinks
#### import
2019-05-21 01:23:20.317 INFO Imported #228148 (0xc9bc…af55)
2019-05-21 01:23:21.616 INFO Idle (14 peers), best: #228148 (0xc9bc…af55), finalized #228142 (0x2d9a…0f24), ⬇ 7.6kiB/s ⬆ 6.7kiB/s
####### receive same height block from node Amazon
2019-05-21 01:23:21.994 INFO [runtime|xrml_xsystem] height:228148, blockproducer: 0b257ad398a034bec8e2020bf0d8f8102cdeb8a0ba21455e11d8df9a44636791 (5CKKWyrD...)|name:Amazon
2019-05-21 01:23:21.999 INFO Reorg from #228148,0xc9bc…af55 to #228148,0x523c…ef20, common ancestor #228147,0x587d…dcc3
2019-05-21 01:23:21.1000 INFO Imported #228148 (0x523c…ef20)

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h393751b981ef0a09 (0x563c473dd2df)
   1: std::panicking::rust_panic_with_hook::h7efe5cde925ada1b (0x563c475b3f58)
             at src/libstd/panicking.rs:478
   2: std::panicking::continue_panic_fmt::h39e7c865f7254bbb (0x563c475b39f1)
             at src/libstd/panicking.rs:381
   3: rust_begin_unwind (0x563c475b38d5)
```

**Comment by JKingdom** [comment] 2019-05-22 02:10
and when the reorganization happen in syncing block, the reorganization is normal, not panic
```bash
2019-05-21 01:24:07.344 main-tokio-1 INFO substrate  Imported #228173 (0x2962…211c)
2019-05-21 01:24:08.408 ImportQueueWorker INFO runtime  [runtime|xrml_xsystem] height:228174, blockproducer: 3cdb9064538234cc5c500784b60f45284172252022a505f1026299a31a682056 (5DSVxJoN...)|name:DappPub
2019-05-21 01:24:08.410 main-tokio-0 INFO substrate  Imported #228174 (0x01a9…66dd)
2019-05-21 01:24:08.625 ImportQueueWorker DEBUG runtime  [runtime|xrml_xmining_staking::shifter] [note_offline_validator]: active offline validator noted: "5f423525f65a2b6eb5866a9159dee5edebb00c85e43147bf02ef1921590c4df1 (5EDc5F7D...)(buildlinks)"
2019-05-21 01:24:08.625 ImportQueueWorker INFO runtime  [runtime|xrml_xsystem] height:228172, blockproducer: 04d39ffbc61f5bbc97072a9a7b2ae6cc7c520aedd47512af704cb6d6e29c62d1 (5CB2uzR9...)|name:anson-HK
######## reorganization
2019-05-21 01:24:08.629 main-tokio-0 INFO substrate_cli::informant  Reorg from #228174,0x01a9…66dd to #228172,0xb2cd…4d5e, common ancestor #228171,0x8886…c054
2019-05-21 01:24:08.629 main-tokio-0 INFO substrate  Imported #228172 (0xb2cd…4d5e)
2019-05-21 01:24:10.372 main-tokio-0 INFO substrate_basic_authorship::basic_authorship  Starting consensus session on top of parent 0x01a9988dd0146996707abd626a688829b88494fa7488ae9237d17807c10f66dd
2019-05-21 01:24:10.392 main-tokio-0 INFO runtime  [runtime|xrml_xsystem] height:228175, blockproducer: e1bb5dce598f45732d6f5796adaca4ca261387ed5b5cda96c3c588f256e8205b (5HAgHp5m...)|name:Laocius
2019-05-21 01:24:10.404 main-tokio-0 INFO substrate_basic_authorship::basic_authorship  Prepared block for proposing at 228175 [hash: 0xe8a95ef7f51c1acee773c7eefe02bc17f27b991c35147e98008b264f46165fe1; parent_hash: 0x01a9…66dd; extrinsics: [0x5897…565b, 0x5257…fed3]]
2019-05-21 01:24:10.404 main-tokio-0 INFO substrate_consensus_aura  Pre-sealed block for proposal at 228175. Hash now 0xe88ecc7edf4e939aac61cafcf0f33e76a535b6b53a1af7aef6acc1ca157cd702, previously 0xe8a95ef7f51c1acee773c7eefe02bc17f27b991c35147e98008b264f46165fe1.
2019-05-21 01:24:10.420 main-tokio-0 INFO runtime  [runtime|xrml_xsystem] height:228175, blockproducer: e1bb5dce598f45732d6f5796adaca4ca261387ed5b5cda96c3c588f256e8205b (5HAgHp5m...)|name:Laocius
######## reorganization
2019-05-21 01:24:10.424 main-tokio-1 INFO substrate_cli::informant  Reorg from #228172,0xb2cd…4d5e to #228175,0xe88e…d702, common ancestor #228171,0x8886…c054
2019-05-21 01:24:10.424 main-tokio-1 INFO substrate  Imported #228175 (0xe88e…d702)
2019-05-21 01:24:11.427 main-tokio-1 INFO substrate  Idle (27 peers), best: #228175 (0xe88e…d702), finalized #228167 (0x3724…3fc5), ⬇ 28.5kiB/s ⬆ 27.9kiB/s
2019-05-21 01:24:12.586 ImportQueueWorker INFO runtime  [runtime|xrml_xsystem] height:228176, blockproducer: 7cc6548e44ccdb6ff82b324e3125ce41d8446c4559cf34d495e9be5b8e8e3e30 (5EtJiCxZ...)|name:MathWallet
2019-05-21 01:24:12.642 main-tokio-1 INFO substrate  Imported #228176 (0x36de…8cb9)
2019-05-21 01:24:14.408 ImportQueueWorker INFO runtime  [runtime|xrml_xsystem] height:228177, blockproducer: 98c51995fdc63afbe50b010c71b5cabe14e270d1665e82f958c39bdd5bfb8f9a (5FX1gmod...)|name:Suncius
2019-05-21 01:24:14.426 main-tokio-1 INFO substrate  Imported #228177 (0xe619…d618)
```

**Comment by JKingdom** [comment] 2019-05-22 02:15
Our substrate is base on c52d16441b5d9f0afbd44cedab0525b4e6566bbb

**Comment by arkpar** [comment] 2019-05-22 13:07
Could you reproduce with `-l state-db=trace,forks=trace` and post logs again?

**Comment by JKingdom** [comment] 2019-05-22 13:11
it's hard to reproduce by myself, due to it's random happening. we would try, but may not reproduce.
By the way, I think you guys could force on the flow for the producer product a block, and import the block. in this flow, when receive a same height block, trigger the reorganization.

**Comment by JKingdom** [comment] 2019-05-23 15:58
I think of another import thing!
this panic is 
```bash
====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h393751b981ef0a09 (0x563c473dd2df)
   1: std::panicking::rust_panic_with_hook::h7efe5cde925ada1b (0x563c475b3f58)
             at src/libstd/panicking.rs:478
   2: std::panicking::continue_panic_fmt::h39e7c865f7254bbb (0x563c475b39f1)
             at src/libstd/panicking.rs:381
   3: rust_begin_unwind (0x563c475b38d5)
   4: core::panicking::panic_fmt::h2cf06a34c3143265 (0x563c475cddac)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::h35e42733c847a8de (0x563c4646a09d)
   6: <substrate_state_machine::ext::Ext<H,B,T,O> as substrate_state_machine::Externalities<H>>::storage::h8a9eb481f7268af5 (0x563c466884c4)
   7: std::thread::local::LocalKey<T>::with::hf03c34159e32754c (0x563c473c0ad2)
   8: sr_io::read_storage::h1f4d3f3022eb6b14 (0x563c473c02cb)
   9: <srml_system::RandomMaterial<T> as srml_support::storage::hashed::generator::StorageValue<(i8, alloc::vec::Vec<<T as srml_system::Trait>::Hash>)>>::get::hf0545d1f8e375809 (0x563c47132ab5)
  10: srml_system::Module<T>::initialize::hb229a71918620f18 (0x563c4712cf51)
  11: chainx_runtime::xexecutive::Executive<System,Block,Context,Payment,AllModules>::initialize_block::hfdfe39c22f6ff0ec (0x563c471edc33)
  12: substrate_client::runtime_api::runtime_decl_for_Core::initialize_block_native_call_generator::{{closure}}::ha5927f8a5dd49dfc (0x563c4676d0b8)
  13: std::panicking::try::do_call::h076a175b21336e67 (0x563c4680183b)
  14: __rust_maybe_catch_panic (0x563c475b9989)
             at src/libpanic_unwind/lib.rs:85
  15: std::thread::local::LocalKey<T>::with::hcd3d3b9cbf003fec (0x563c467ec9fc)
  16: <substrate_executor::native_executor::NativeExecutor<D> as substrate_state_machine::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call::h7ca2922c0f0b1bd5 (0x563c4679b24b)
  17: substrate_state_machine::StateMachine<H,B,T,O,Exec>::execute_aux::h6857825cfe5cab6f (0x563c4684493d)
  18: substrate_state_machine::StateMachine<H,B,T,O,Exec>::execute_using_consensus_failure_handler::hafa34b1accccb9e2 (0x563c468bccff)
  19: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::h9f3c4b996ce29567 (0x563c46afd7e7)
  20: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::h889d4c027680aa81 (0x563c46984986)
  21: substrate_client::runtime_api::runtime_decl_for_Core::initialize_block_call_api_at::hfd38522b6295ed1b (0x563c464f9114)
  22: substrate_client::runtime_api::Core::initialize_block::h6598d8f11ca8b120 (0x563c46a58905)
  23: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::hdf05e36c766b4c56 (0x563c46b06386)
  24: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::h95985b4285bd0ffc (0x563c46985009)
  25: substrate_offchain_primitives::runtime_decl_for_OffchainWorkerApi::offchain_worker_call_api_at::h3989e901064dd62a (0x563c46b12cf1)
  26: substrate_offchain_primitives::OffchainWorkerApi::offchain_worker_with_context::h44041ca798a19e58 (0x563c46a6c3c6)
  27: substrate_offchain::OffchainWorkers<C,Block>::on_block_imported::h05e84cc535c484ea (0x563c469bb591)
  28: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll::hf84b1f6c59d4f0e8 (0x563c466db1b1)
  29: <futures::future::select::Select<A,B> as futures::future::Future>::poll::hd93798b3e7d08a81 (0x563c4654637b)
  30: futures::future::chain::Chain<A,B,C>::poll::h3ffa31c1e98ba150 (0x563c46a94d58)
  31: futures::task_impl::std::set::h51310ba5a7cb7e45 (0x563c472aa031)
  32: futures::task_impl::Spawn<T>::poll_future_notify::hed4ced7fac6a258e (0x563c472a5985)
  33: std::panicking::try::do_call::hc66564ccd455e604 (0x563c472abdc0)
  34: __rust_maybe_catch_panic (0x563c475b9989)
             at src/libpanic_unwind/lib.rs:85
  35: tokio_threadpool::task::Task::run::he6e140491fbd570f (0x563c472a5b88)
  36: tokio_threadpool::worker::Worker::run_task::h04d203ca541b381d (0x563c472a1584)
  37: tokio_threadpool::worker::Worker::run::h32316878b7a0730d (0x563c472a0a7d)
  38: tokio_trace_core::dispatcher::with_default::h3c1d781d98a93aee (0x563c4728ba36)
  39: std::thread::local::LocalKey<T>::with::h22879d5136114ca6 (0x563c4728b395)
  40: std::thread::local::LocalKey<T>::with::h0daff4824ab8e28f (0x563c4728b25d)
  41: std::thread::local::LocalKey<T>::with::hd048e65d26c91a36 (0x563c4728b593)
  42: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h5ce219ac059c4758 (0x563c4728ef86)
  43: std::thread::local::LocalKey<T>::with::h14a0072ab3f21c55 (0x563c472a90a2)
  44: std::thread::local::LocalKey<T>::with::h699d821d96611d2d (0x563c472a91dd)
  45: std::sys_common::backtrace::__rust_begin_short_backtrace::h5ee06633c6a139f5 (0x563c472a1e40)
  46: std::panicking::try::do_call::h1abddd92ef23d59e (0x563c472abd7b)
  47: __rust_maybe_catch_panic (0x563c475b9989)
             at src/libpanic_unwind/lib.rs:85
  48: core::ops::function::FnOnce::call_once{{vtable.shim}}::h3af84b72f879722d (0x563c472a2eff)
  49: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h74ec1c808eb1d6f6 (0x563c475a138e)
             at /rustc/8dd4aae9a83964cc08505da92d07ec68a3a2341d/src/liballoc/boxed.rs:704
  50: std::sys::unix::thread::Thread::new::thread_start::h5771ac597fbe512e (0x563c475b8c9f)
             at /rustc/8dd4aae9a83964cc08505da92d07ec68a3a2341d/src/liballoc/boxed.rs:704
      std::sys::unix::thread::Thread::new::thread_start::h5771ac597fbe512e
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h5771ac597fbe512e
             at src/libstd/sys/unix/thread.rs:79
  51: start_thread (0x7fba817f56b9)
  52: clone (0x7fba8131541c)
  53: <unknown> (0x0)

Thread 'main-tokio-3' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0xf8eb2f38dc9b10a06f7ec6f798a85cd33c763d7cf1ecfbff63e3bf9a8ee8cdc4"', src/libcore/result.rs:999
```
**Trie lookup error: Invalid state root**
when look up the state root for this block of this height, this state is not belong to this block.
**Thus, this state is for old block for this height, not reorganized block**
for example
```bash
|100|101|102|
A-> state1 -> this block is reverted for receiving a new block for same height
B->state2
        C
```
**the panic msg print the error state root is state1, not state2!**

**Comment by JKingdom** [comment] 2019-05-23 16:04
@arkpar 
This problem is very urgent for us. we think the problem is forced on the producer product a block, then revert self block, and in an unknown reason, look up the reverted block state root.

**Comment by JKingdom** [comment] 2019-06-01 03:57
we meet this problem again in ChainX mainnet!
we base on substrate d6eba14a55be26e1a4e24a882ff574aa0190aff6

and this problem is first happening when the node is running after a weak, and we didn't meet this problem in early time.
now our database is more than 6GB, in no archive mode. (do not set --pruning)
At now, we suggest our nodes start with `--pruning=archive`, and observe whether this problem would happen again.

**Comment by gavofyork** [comment] 2019-11-28 08:58
Closing due to staleness and recent changes which might help. Please re-report if still a problem.

**Closed by gavofyork** 2019-11-28 08:58 UTC
Labels: F1-panic 😱
