### ISSUE TITLE
Substrate: Alternative consensus engines

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#420] opened 2018-07-25 08:40 UTC
Substrate currently uses only Rhododendron. The consensus algorithm should instead be stored in the `:consensus` key of the database (defaulting to `rho` if it doesn't exist) and substrate should use that algorithm to determine what consensus protocol to use for the given block. Since some consensus algorithms are non-final or require multiple blocks to reach finality, then any block whose state-transition function alters the `:consensus` key to anything other than `rho` will use `rho` to finalise that block as a handoff procedure.

The consensus algorithm is free to require arbitrary other storage keys for its operation.

In principle, in the future, there may be a handoff to `dot`.

**Comment by DemiMarie-parity** [comment] 2019-05-25 00:31
It seems that this has already been fixed.  We already use AuRa and GRANDPA, and BABE is being worked on.

**Comment by DemiMarie-parity** [comment] 2019-05-25 00:32
@gavofyork can this be closed?

**Comment by tomaka** [comment] 2019-07-24 14:17
Triage. This looks like a duplicate of #1304, which contains more details.

**Closed by tomaka** 2019-07-24 14:17 UTC
Labels: F8-enhancement 🎁, Q9-epic
