### ISSUE TITLE
Consider moving client-only and frame-only primitives out of `primitives`

### ISSUE THREAD

**Issue by expenses** [paritytech/substrate#9214] opened 2021-06-28 10:52 UTC
`primitives` is meant to contain shared components.

**Comment by expenses** [comment] 2021-06-28 10:59
Pinging @seunlanlege @gilescope

**Comment by expenses** [comment] 2021-06-28 13:03
- [ ] #9214

**Comment by gilescope** [comment] 2021-06-29 09:10
Will take a crack at this as v similar to yesterday's.

**Comment by bkchr** [comment] 2021-09-07 11:46
Duplicate of: https://github.com/paritytech/substrate/issues/5485

**Closed by bkchr** 2021-09-07 11:46 UTC
Labels: P7-nicetohave
