### ISSUE TITLE
Improve CI to check each individual crate and with various features

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#14616] opened 2023-07-24 02:16 UTC
For Substrate, Polkadot and Cumulus, many pallets have missing features that they cannot check individually. This doesn't always cause issue for Polkadot or system parachains but have break the build for Acala many times.

We should improve the CI to do cargo check of each individual crate and for the one should be build in wasm, check with no std, and for the one with extra features, such as try-runtime and runtime-benchmarking, which with those combinations as well.

Example fixes that I have to do:
https://github.com/paritytech/substrate/pull/6995
https://github.com/paritytech/substrate/pull/5833
https://github.com/paritytech/polkadot/pull/7537

**Comment by xlc** [comment] 2023-07-24 02:17
Oh. I already raised an issue before https://github.com/paritytech/substrate/issues/10357 
I guess I will keep this open and keep open issues until someone looked at my issues.

**Comment by kianenigma** [comment] 2023-07-24 03:39
cc @paritytech-ci

**Comment by bkchr** [comment] 2023-07-24 05:38
Duplicate of #10357

**Closed** 2023-07-24 05:38 UTC
