### ISSUE TITLE
Grandpa validator Deleting db and then synchronizing as authority will affect the stability of the entire network.

### ISSUE THREAD

**Issue by gguoss** [paritytech/substrate#2224] opened 2019-04-08 04:05 UTC
Run multiple authority identity nodes, at a certain height, pick one of them, and delete its db data, starting from the block height of 0 and synchronizing as authority. At this point, the nodes of the entire network will be very unstable, as if receiving a DDOS attack.

**Comment by gguoss** [comment] 2019-04-08 04:13
Is it necessary to increase the block height message that has been finalized into the p2p protocol so that the authority identity node that is not synchronized to the latest finalize block is no longer initiating the grandpa voter.

**Comment by rphmeier** [comment] 2019-04-08 09:43
The problem is mostly about how a node determines when it is synced or not, especially in the presence of malicious block producers and malicious peers. `polite-grandpa` will address the networking bandwidth concerns because such messages from unsynced peers will not be relayed.

**Comment by gavofyork** [comment] 2019-11-28 08:56
(polite grandpa is merged)

**Closed** 2019-11-28 08:56 UTC
Labels: F3-annoyance 🦟
