### ISSUE TITLE
Validator Nodes crash with Essential task grandpa-voter failed. 

### ISSUE THREAD

**Issue by wpank** [paritytech/substrate#6727] opened 2020-07-24 13:00 UTC
More than one Validators in in the Kusama Validator lounge reported their nodes failing with the logs saying something like this:

```
jul 24 11:27:07 XXXXXX polkadot[14640]: 2020-07-24 11:27:07 💤 Idle (53 peers), best: #3308841 (0xbca0…81f4), finalized #3308838 (0x3b5d…54e4), ⬇ 1.5MiB/s
jul 24 11:27:08 XXXXXX polkadot[14640]: 2020-07-24 11:27:08 🙇 You are using the peer ID QmQZEm9395wgF3ztkfqwNgx3yrqsLEECYB3cd7mZDavyxX. This peer ID uses
jul 24 11:27:08 XXXXXX polkadot[14640]: 2020-07-24 11:27:08 🙇 You are using the peer ID QmPVbzttk7DbyMcAoo95PxNtsGAVq98uLivGZhTaB7Yy7M. This peer ID uses
jul 24 11:27:08 XXXXXX polkadot[14640]: 2020-07-24 11:27:08 🙇 You are using the peer ID QmQZEm9395wgF3ztkfqwNgx3yrqsLEECYB3cd7mZDavyxX. This peer ID uses
jul 24 11:27:08 XXXXXX polkadot[14640]: 2020-07-24 11:27:08 🙇 You are using the peer ID QmPVbzttk7DbyMcAoo95PxNtsGAVq98uLivGZhTaB7Yy7M. This peer ID uses
jul 24 11:27:10 XXXXXX polkadot[14640]: 2020-07-24 11:27:10 🔍 Discovered new external address for our node: /ip4/10.0.0.2/tcp/30333/p2p/12D3KooWSqJ3jxMv1K
jul 24 11:27:11 XXXXXX polkadot[14640]: 2020-07-24 11:27:11 🔍 Discovered new external address for our node: /ip4/10.156.1.51/tcp/30333/p2p/12D3KooWSqJ3jxM
jul 24 11:27:11 XXXXXX polkadot[14640]: 2020-07-24 11:27:11 Essential task grandpa-voter failed. Shutting down service.
jul 24 11:27:11 XXXXXX polkadot[14640]: Error: Input("Essential task failed.")
```

**Comment by andresilva** [comment] 2020-07-24 13:28
Pasting my comments from riot:

I just confirmed that this can happen due to the changes introduced in the keystore API for remote signing.
https://github.com/paritytech/substrate/pull/6178/files#diff-233fff7c89a6b4ca96ca4ee31c62088cL385.this would never fail previously.
The GRANDPA voter didn't crash, it failed to sign a message and it deliberately took the system down. I think this is the correct behavior as not being able to sign messages is a critical error, and I think it's better to take the node down rather than pretend it is working. In order to trigger the issue I setup an invalid session key through the RPC API (generated a sr25519 keypair and set it as grandpa key which is ed25519). IMO the root issue is that the key was accepted by the server whereas it should have been rejected, otherwise we only run into the problem whenever we try to sign something.

I have no clue how/if this related to authority discovery. We need more info from the people that have had this error.

**Comment by wpank** [comment] 2020-07-24 13:43
Also some more anecdotes:

- Keys remained the same prior to upgrading
- It _may_ only happen on Kusama
- it _may_ go away when disabling authority discovery

**Comment by andresilva** [comment] 2020-08-16 17:30
I think we can close this now. Seems to be fixed in v0.8.22 and we don't have new reports.

**Closed by andresilva** 2020-08-16 17:30 UTC
Labels: I1-panic 😱, P2-asap

**Comment by WB-Expert5007** [comment] 2022-06-15 06:19
Everyone. Please help me.

When I run my substrate node server by running this command "./target/release/node-template --dev --ws-external --rpc-external", server works well and start generating blocks first. But after few hours, my server is been stopped and also stopped generating blocks automatically. How can I solve this problem? Here is Terminal Error.
![Error](https://user-images.githubusercontent.com/96474901/173756302-69fb44bb-71d8-4acd-8b96-30a53d7e3322.png)
Best Regards.

**Comment by artlotz** [comment] 2022-07-21 17:24
I also had a similar error.

After deleting the chain data in --base-path, it was executed normally.

The command below may help.

`./target/release/node-template purge-chain --base-path /tmp/node01 --chain local -y`

`/tmp/node01` <-- --base-path value used when starting the node

**Comment by bellaj** [comment] 2022-08-21 22:12
Sr25519 instead Ed25519 for generating gp keys you will get this error
