### ISSUE TITLE
Slow memory leak

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#448] opened 2018-07-29 10:22 UTC
Approximately 500KB/minute leaked; could be fairly specific to authority nodes?

**Comment by chevdor** [comment] 2018-07-29 10:52
I am:
- not an authority node
- using a118a85
- I run with default options just providing a name

I do see the issue as well for a while. The increase is slow but steady. Running Polkadot on a VPS with 1GB Memory makes it stop after around 8 hours. There is nothing in the logs but docker either loses it or stops the container. After a restart, all is good again.

![image](https://user-images.githubusercontent.com/738724/43365472-bdfa5808-932d-11e8-9ad4-c61d3fb0bf53.png)

This is not a new issue and I can observe it back at least to 22.7

**Comment by chevdor** [comment] 2018-07-29 11:16
I am running a small test to see if telemetry could be involved but from a few minutes running, it does not seem to be the case.

**Comment by tomaka** [comment] 2018-07-29 11:20
For what it's worth, I also tested yesterday whether peer discovery could be the cause. I disabled everything except connecting to bootstrap nodes and the leak was still present.

**Comment by gavofyork** [comment] 2018-09-27 15:19
looks like this was fixed in the recent networking rework. closing unless/until we get evidence otherwise.

**Comment by gavofyork** [comment] 2018-09-27 19:06
Looks like this is still here. Running a `master` branch node steadily uses more memory started around 70mb and now at 116mb after 4-5 hours.

**Comment by rphmeier** [comment] 2018-11-27 16:01
@arkpar did you get any insight on this?

**Comment by arkpar** [comment] 2018-11-29 08:10
I've used memory profiler to check a node minting blocks for a few hours. There are no leaks. It took a couple of hours for rocksdb cache to warm up though. The only issue with the test is that the node was only connected to a single peer and there were no disconnects. So I did non really check for any leaks that might be caused by libp2p reconnections. That would require a test network.

**Comment by pepyakin** [comment] 2018-11-29 15:09
This is consistent with my observations as well.

**Comment by chevdor** [comment] 2018-12-03 09:00
I have been collecting some stats for a few days and here is the result. Sure it does not shows the origin of the leak but it confirms it is still there. I am especially curious what the last spike can be.

What you see is the Crash Override container. It runs 24/7 and restarts daily at the moment (mainly due to that leak). Due to the restart, I expect a spike in p2p comm when the node starts. The rest should be rather stable.

![image](https://user-images.githubusercontent.com/738724/49363316-a15b7480-f6e1-11e8-9b7a-23dcaceef09a.png)

**Comment by chevdor** [comment] 2018-12-03 12:52
Hi Ben,

I am using the following version `polkadot 0.2.17-6ff5488-x86_64-linux-gnu`.
Your explanation makes sense but the spikes are probably not the entire problem.

I understand @arkpar statement about warming up so I am not too worries about the initial memory ramp up. However, I see only spikes going up (memory is not freed) and the trend is also toward an increase without any noticeable decrease.

I don't have a profiler at hand (yet). What I can do for now (and this is hopefully helpful to confirming one theory or another), is to let the node run longer and potentially give the node more time to free some memory.

**Comment by tomaka** [comment] 2018-12-03 13:01
0.2.17 is unfortunately very far away from the master branch.

**Comment by chevdor** [comment] 2018-12-03 14:14
Is there a newer version that can be used on PoC-2 with changes that could help with this issue?

**Comment by gnunicorn** [comment] 2018-12-12 18:06
can not reproduce this anymore since we added rocksdb and now can limit the db cache. closing.

**Closed by gnunicorn** 2018-12-12 18:06 UTC
Labels: F2-bug
