### ISSUE TITLE
Consensus session fails with "Unreachable" error with substate/node-template

### ISSUE THREAD

**Issue by laboon** [paritytech/substrate#2729] opened 2019-05-29 23:54 UTC
## Description

When the default consensus mechanism starts (after two nodes are connected) using --chain=local with node-template, an "Unreachable" error occurs.  The consensus mechanism restarts but continues to fail in this manner.

## To Reproduce

Start Alice node in one terminal:

```
 $ ./target/debug/node-template   --chain=local   --key //Alice --port 30333   --validator
```

Start Bob node in another (modifying IP, node identifier, etc. to fit your computer)

```
 $ ./target/debug/node-template  --base-path /tmp/bob --chain=local  --key //Bob --port 30334   --telemetry-url ws://telemetry.polkadot.io:1024   --validator   --name BobsNode   --bootnodes /ip4/192.168.1.156/tcp/30333/p2p/QmR32LQ8PFdBk2qxC7ugLBUCaw3J1NKuRucHBJ8dU27Vr6
```
View output for either.

## Expected Behavior

Blocks are produced.

## Observed Behavior

Repeated consensus errors - see below.

## Output

```
2019-05-29 19:45:43 Substrate Node
2019-05-29 19:45:43   version 2.0.0-58c3bbc4-x86_64-macos
2019-05-29 19:45:43   by Anonymous, 2017, 2018
2019-05-29 19:45:43 Chain specification: Local Testnet
2019-05-29 19:45:43 Node name: BobsNode
2019-05-29 19:45:43 Roles: AUTHORITY
2019-05-29 19:45:43 Highest known block at #0
2019-05-29 19:45:43 Using default protocol ID "sup" because none is configured in the chain specs
2019-05-29 19:45:43 Local node identity is: QmNTXxG37QtYLRzf1vnadiHqfLp4aQNBD7AvNVhAUK74EC
2019-05-29 19:45:43 Unable to listen on 127.0.0.1:9944
2019-05-29 19:45:43 Unable to bind server to 127.0.0.1:9944. Trying random port.
2019-05-29 19:45:43 Listening for new connections on 127.0.0.1:49274.
2019-05-29 19:45:43 Using authority key 5Cdw3BqUmFEdnEGQi62vk6E27XsL22R1A51Xea5xqU7xTDCc
2019-05-29 19:45:44 Discovered new external address for our node: /ip4/192.168.1.156/tcp/30334/p2p/QmNTXxG37QtYLRzf1vnadiHqfLp4aQNBD7AvNVhAUK74EC
2019-05-29 19:45:48 Idle (1 peers), best: #0 (0x4ce0…00cf), finalized #0 (0x4ce0…00cf), ⬇ 0.6kiB/s ⬆ 0.6kiB/s
2019-05-29 19:45:50 Starting consensus session on top of parent 0x4ce0bb4f5bb475285c22bb65efe3440cfaa2b66916fcf83444f1cb3b3f8300cf
src/libcore/option.rs
1036
5
2019-05-29 19:45:50 Encountered consensus error: ClientImport("Error(Inner(Execution(Wasmi(Trap(Trap { kind: Unreachable })))))")
2019-05-29 19:45:50 Authorship task terminated unexpectedly. Restarting
```

**Comment by JoshOrndorff** [comment] 2019-05-30 00:19
Same happens when just running with `--dev`

**Comment by JoshOrndorff** [comment] 2019-05-30 01:50
Happens on the full substrate node in addition to the node-template

**Comment by DemiMarie-parity** [comment] 2019-06-01 01:23
Duplicate of #2738.

**Closed by DemiMarie-parity** 2019-06-01 01:23 UTC
Labels: Z7-duplicate

**Comment by bo-liu** [comment] 2019-10-07 14:52
> ## Description
> When the default consensus mechanism starts (after two nodes are connected) using --chain=local with node-template, an "Unreachable" error occurs. The consensus mechanism restarts but continues to fail in this manner.
> 

Did you use node-template to start a private blockchain?  Do you know how to finalize blocks if using node-template? Thanks!
