### ISSUE TITLE
support for custom transports for telemetry

### ISSUE THREAD

**Issue by dvc94ch** [paritytech/substrate#6669] opened 2020-07-16 01:57 UTC
We have a light client embedded in an android/ios application. There doesn't seem to be an effective way of reporting telemetry data in the ui. For example we would like to report the sync status of the light client on startup and notify the user when sync is complete. So what we need is something that exposes `Stream<Item = TelemetryMessage>`.

**Comment by tomaka** [comment] 2020-07-20 08:40
Telemetry data isn't supposed to be reported in the UI.
If your objective is to notify the user when the sync is complete, I don't think that should be related to the telemetry.

**Comment by bkchr** [comment] 2020-07-20 08:45
Sort of duplicate of: https://github.com/paritytech/substrate/issues/5727

In the end you just want the same functionality as described in this issue, but probably not as rpc call.

**Closed by bkchr** 2020-07-20 08:45 UTC
