### ISSUE TITLE
Auxiliary storage is not cleared on reorg

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/substrate#10441] opened 2021-12-07 17:56 UTC
As `AuxStore` is global, in BABE weight for block that was initially imported, but eventually got pruned, remains in the storage forever.

Arguably minor issue, but still annoying and should probably be fixed.

**Comment by bkchr** [comment] 2021-12-07 18:18
As I already explained yesterday, `AuxStore` is not fork aware or anything. It is just a "dumb" store.

**Comment by nazar-pc** [comment] 2021-12-07 18:19
Right, and that is the reason why it needs to be cleared up "manually" or it is stuck in storage forever.

**Comment by bkchr** [comment] 2021-12-07 18:28
Ahh sorry, I was confused by your title.

Then this is a duplicate of: https://github.com/paritytech/substrate/issues/8692

**Closed by bkchr** 2021-12-07 18:28 UTC
