### ISSUE TITLE
sp-runtime 11.0.0 no longer compiles to wasm

### ISSUE THREAD

**Issue by silicology1** [paritytech/substrate#13087] opened 2023-01-06 11:18 UTC
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

New version of sp-runtime 11.0.0 does not compile to wasm in yew. Last compiled version is sp-runtime 7.0.0 Gives error
 

```
Checking sp-externalities v0.15.0
error: cannot find macro `thread_local` in this scope
  --> /home/amiya/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-externalities-0.15.0/src/scope_limited.rs:22:1
   |
22 | environmental::environmental!(ext: trait Externalities);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `thread_local` is in scope, but it is an attribute: `#[thread_local]`
   = note: this error originates in the macro `$crate::thread_local_impl` which comes from the expansion of the macro `environmental::environmental` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0425]: cannot find value `GLOBAL` in this scope
  --> /home/amiya/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-externalities-0.15.0/src/scope_limited.rs:22:1
   |
22 | environmental::environmental!(ext: trait Externalities);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
   |
   = note: this error originates in the macro `$crate::environmental` which comes from the expansion of the macro `environmental::environmental` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0425`.
error: could not compile `sp-externalities` due to 3 previous errors
```

**Comment by bkchr** [comment] 2023-01-06 12:58
Please show your code. Do you have the features set correctly?

**Comment by amiyatulu** [comment] 2023-01-06 14:37
What features to use? I used following dependencies

sp-runtime = { version = "11.0.0", default-features = false  }
sp-keyring = { version = "11.0.0", default-features = false}
sp-core = { version = "10.0.0", default-features = false}


With sp-keyring it gives error:

```
The following warnings were emitted during compilation:

warning: src/helpers.c:1:10: fatal error: 'setjmp.h' file not found
warning: #include <setjmp.h>
warning:          ^~~~~~~~~~
warning: 1 error generated.

error: failed to run custom build command for `wasmtime-runtime v1.0.2`

Caused by:
  process didn't exit successfully: `/home/amiya/Documents/workspace/shivarthu/working_directory/shivarthu-client/target/debug/build/wasmtime-runtime-59c827d61f6baca1/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=src/helpers.c
  TARGET = Some("wasm32-unknown-unknown")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_wasm32-unknown-unknown
  CC_wasm32-unknown-unknown = None
  cargo:rerun-if-env-changed=CC_wasm32_unknown_unknown
  CC_wasm32_unknown_unknown = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CFLAGS_wasm32-unknown-unknown
  CFLAGS_wasm32-unknown-unknown = None
  cargo:rerun-if-env-changed=CFLAGS_wasm32_unknown_unknown
  CFLAGS_wasm32_unknown_unknown = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  running: "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=wasm32-unknown-unknown" "-Wall" "-Wextra" "-DCFG_TARGET_OS_unknown" "-DCFG_TARGET_ARCH_wasm32" "-o" "/home/amiya/Documents/workspace/shivarthu/working_directory/shivarthu-client/target/wasm32-unknown-unknown/debug/build/wasmtime-runtime-3157b005f786c020/out/src/helpers.o" "-c" "src/helpers.c"
  cargo:warning=src/helpers.c:1:10: fatal error: 'setjmp.h' file not found
  cargo:warning=#include <setjmp.h>
  cargo:warning=         ^~~~~~~~~~
  cargo:warning=1 error generated.
  exit status: 1

  --- stderr


  error occurred: Command "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=wasm32-unknown-unknown" "-Wall" "-Wextra" "-DCFG_TARGET_OS_unknown" "-DCFG_TARGET_ARCH_wasm32" "-o" "/home/amiya/Documents/workspace/shivarthu/working_directory/shivarthu-client/target/wasm32-unknown-unknown/debug/build/wasmtime-runtime-3157b005f786c020/out/src/helpers.o" "-c" "src/helpers.c" with args "clang" did not execute successfully (status code exit status: 1).


```

**Comment by bkchr** [comment] 2023-01-07 09:23
I mean the crates are compiling fine for everybody. Now it fails to find a header for wasmtime. You should check your build env on why it fails. Not really a Substrate issue.

**Comment by kylezs** [comment] 2023-01-07 09:58
^ It is a features issue, I've hit the same error before. @amiyatulu also check that those crates are in the `std = []` under the `[features]` section of the toml. It's something to do with that.

It would be nice if there was better error reporting here though, this error is pretty misleading, I wasted some time trying to compile with different `clang` versions etc. but it's resolved by setting features correctly. It's also not always obvious which is incorrectly set compiling a runtime with a lot of dependencies, I had to solve it by bisecting the runtime until found the erroneous or missing feature.

**Comment by amiyatulu** [comment] 2023-01-07 11:48
Please note I am using the package in yew.rs frontend rather than substrate runtime. It is working fine with 7.0.0

The error didn't disappeared with 

```
[dependencies]
yew = { version = "0.20.0", features = ["csr"] }
sp-keyring = { version = "11.0.0", default-features = false }
sp-core = { version = "10.0.0", default-features = false }
sp-runtime = { version = "11.0.0", default-features = false  }


[features]
default = ["std"]
std = [
	"codec/std",
	"sp-core/std",
        "sp-runtime/std",
]
```

**Comment by bkchr** [comment] 2023-01-07 13:51
Keyring is not no_std compatible. This is very likely the reason why this stuff is compiled. Remove the dep from your crate.

**Comment by amiyatulu** [comment] 2023-01-08 13:11
Error exists even if I remove sp-keyring.

**Comment by ggwpez** [comment] 2023-01-08 16:26
Please provide the source code, including the `Cargo.toml`, otherwise I cannot reproduce this.

**Comment by amiyatulu** [comment] 2023-01-09 14:54
There is the reproducible source code: https://github.com/amiyatulu/yew_test
Thanks.

**Comment by bkchr** [comment] 2023-01-09 15:46
The problem is that `subxt` is pulling in `sp-runtime` without disabling any features. This pulls then in `wasmtime` etc. Looking at `subxt` wasm support it looks like it is more hacked than a real solution. The Substrate crates all are expecting to be compiled with `default-features = false` when they are compiled for `wasm32-unknown-unknown`.  There isn't that much that we can do. I propose that you open again an issue in subxt (I have seen your old issue).

CC @jsdw

**Comment by jsdw** [comment] 2023-01-10 14:49
The issue I faced is that setting `default-features = false` on the Substrate crates we used in Subxt leads to:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/james/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-io-12.0.0/src/lib.rs:22:35
   |
22 | #![cfg_attr(not(feature = "std"), feature(alloc_error_handler))]
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0152]: found duplicate lang item `panic_impl`
    --> /Users/james/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-io-12.0.0/src/lib.rs:1642:1
     |
1642 | pub fn panic(info: &core::panic::PanicInfo) -> ! {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: the lang item is first defined in crate `std` (which `tracing` depends on)
     = note: first definition in `std` loaded from /Users/james/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libstd-d3369aa87063c1d1.rlib
     = note: second definition in the local crate (`sp_io`)

error[E0152]: found duplicate lang item `oom`
    --> /Users/james/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-io-12.0.0/src/lib.rs:1658:1
     |
1658 | pub fn oom(_: core::alloc::Layout) -> ! {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: the lang item is first defined in crate `std` (which `tracing` depends on)
     = note: first definition in `std` loaded from /Users/james/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libstd-d3369aa87063c1d1.rlib
     = note: second definition in the local crate (`sp_io`)
```
So, it seems like we need nightly Rust at least. If we try building with nightly we get just:

```
error[E0152]: found duplicate lang item `panic_impl`
    --> /Users/james/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-io-12.0.0/src/lib.rs:1642:1
     |
1642 | pub fn panic(info: &core::panic::PanicInfo) -> ! {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: the lang item is first defined in crate `std` (which `tracing` depends on)
     = note: first definition in `std` loaded from /Users/james/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libstd-a643c5931c4d12de.rlib
     = note: second definition in the local crate (`sp_io`)
```

Down to one; that's promising! So If I add `sp-io = { version = "12.0.0", default-features = false, features = ["disable_panic_handler", "disable_oom", "disable_allocator"] }` to enable some features we seem to get rid of that error, but now we get:

```
error[E0432]: unresolved import `sp_core::Pair`
  --> subxt/src/tx/signer.rs:36:9
   |
36 |     use sp_core::Pair as PairT;
   |         ^^^^^^^^^^^^^^^^^^^^^^ no `Pair` in the root
```

Ah, so that's behind the `full_crypto` feature in `sp_core`, so I'll enable that but then I hit a build error on `secp256k1-sys v0.6.1` which contains:

```
[secp256k1-sys v0.6.1](cargo:warning=error: unable to create target: 'No available targets are compatible with triple "wasm32-unknown-unknown"')
```

So perhaps `full_crypto` and WASM don't play well together?

Annnnyway, what I ended up doing last week when I ran into this WASM compile issue in Subxt was to strip down the Substrate deps we use and hide them behind a feature flag, so that now you have two choices:
1. if you want the `PairSigner` stuff that Subxt provides (which is based on that `Pair` trait and relies on Substrate deps), you'll need to enable the "substrate-compat" feature in Subxt (which is enabled by default actually), or 
2. if you want to compile Subxt to WASM you'll need to set `default-features = false` on it and then Subxt should now happily compile to WASM (and be a couple of hundred deps lighter in the process), but won't include any facility to sign transactions yet (ie no `PairSigner`)

I have an idea to add some basic Signing stuff to Subxt itself so that we'll be able to compile to WASM on stable Rust and have some basic signing impl without needing the Substrate deps. In the meantime, Subxt defines a `Signer` trait, and it's perfeclty possible today to implement your own arbitrary signing logic that is WASM friendly if you want.

I hope that all helps!

**Comment by bkchr** [comment] 2023-01-10 14:56
> The issue I faced is that setting `default-features = false` on the Substrate crates we used in Subxt leads to:

This basically boils down to the following old issue: https://github.com/paritytech/substrate/issues/5547

**Closed as completed** 2023-01-11 14:01 UTC
Labels: J2-unconfirmed
