### ISSUE TITLE
Random peer disconnecting

### ISSUE THREAD

**Issue by arkpar** [paritytech/substrate#1335] opened 2018-12-27 22:32 UTC
Setup a local network with two peers and make one sync off the other. Sometimes the connection is dropped for no good reason. 
Sync log on peer 1
```
2018-12-27 23:21:21 tokio-runtime-worker-2 TRACE sync  Requesting blocks from 0, (3329 to 3457)
2018-12-27 23:21:21 tokio-runtime-worker-6 TRACE sync  BlockResponse 26 from 0 with 128 blocks (3329..3456)
2018-12-27 23:21:21 tokio-runtime-worker-6 TRACE sync  Updating peer 0 info, ours=3456, common=3328, their best=73673
2018-12-27 23:21:21 tokio-runtime-worker-6 TRACE sync  Too many blocks in the queue.
2018-12-27 23:21:21 tokio-runtime-worker-6 TRACE sync  Disconnecting 0: PeerId(QmS8PMVvyZA6NHaqyyKpjVwo7vh2JAHK21pU9jj2im9pL3) through Listener { listen_addr: "/ip4/0.0.0.0/tcp/30333", send_back_addr: "/ip4/127.0.0.1/tcp/54559" }
2018-12-27 23:21:21 tokio-runtime-worker-9 ERROR libp2p_yamux  connection error: decode error: i/o error: I/O error: Connection reset by peer (os error 54)
```

On peer 2:
```
2018-12-27 23:21:21 tokio-runtime-worker-8 TRACE sync  BlockRequest 26 from 2: from Number(3329) to None max Some(128)
2018-12-27 23:21:21 tokio-runtime-worker-8 TRACE sync  Sending BlockResponse with 128 blocks
2018-12-27 23:21:21 tokio-runtime-worker-10 TRACE sync  Disconnecting 2: PeerId(QmU6d2ASoGTdvaQSSqKQyj9KY1PbpHMZWPbSFuhCHYfCsp) through Listener { listen_addr: "/ip4/0.0.0.0/tcp/30306", send_back_addr: "/ip4/127.0.0.1/tcp/54537" }
```

**Comment by xlc** [comment] 2018-12-28 03:05
I have similar issue.

I have 3 nodes network all running as validators in the cloud, and the fourth node from my local machine trying to join the network.

For some reason it keep dropping connection to boot nodes. It imported few blocks, drop the connection, and reconnects, and repeat. It can import blocks but never catch up to latest block.


```
2018-12-28 15:50:19 Generated a new keypair: a2aebc537a1b8696bd0ef46856c81c2fbb4d185601e60e9ff295c585fc398f53 (5Fk1XDdY...)
2018-12-28 15:50:20 Initialising Genesis block/state (state: 0xbc75…5026, header-hash: 0xdd02…ba81)
2018-12-28 15:50:21 Loaded block-time = 6 seconds from genesis on first-launch
2018-12-28 15:50:21 Loading GRANDPA authorities from genesis on what appears to be first startup.
2018-12-28 15:50:21 Best block: #0
2018-12-28 15:50:21 Local node address is: /ip4/0.0.0.0/tcp/30333/p2p/QmcPNvr4zg3YCxwruQAFTUAkVX9MMsMgdDRbqFpUes8AbR
2018-12-28 15:50:21 Idle (0 peers), best: #0 (0xdd02…ba81)
2018-12-28 15:50:25 New external node address: /ip4/10.2.46.0/tcp/30333/p2p/QmcPNvr4zg3YCxwruQAFTUAkVX9MMsMgdDRbqFpUes8AbR
2018-12-28 15:50:25 New external node address: /ip4/10.2.63.0/tcp/30333/p2p/QmcPNvr4zg3YCxwruQAFTUAkVX9MMsMgdDRbqFpUes8AbR
2018-12-28 15:50:26 Idle (3 peers), best: #1 (0x3396…62d4)
2018-12-28 15:50:31 Idle (3 peers), best: #7 (0x2903…6d07)
2018-12-28 15:50:36 Idle (3 peers), best: #12 (0xad4b…40ff)
2018-12-28 15:50:41 Idle (3 peers), best: #18 (0xef10…393f)
2018-12-28 15:50:45 Purposefully dropping 1 ; reason: Useless("Verification failed: Header 0x32f40feeeae9325005f50adda72915ad9f2877b50f946373c0f33ccca0ddca31 rejected: too far in the future")
2018-12-28 15:50:45 Dropped PeerId(QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN)
2018-12-28 15:50:45 Purposefully dropping 1 ; reason: Useless("Verification failed: Could not fetch authorities at 0x32f40feeeae9325005f50adda72915ad9f2877b50f946373c0f33ccca0ddca31: Error(UnknownBlock(\"Hash(0x32f40feeeae9325005f50adda72915ad9f2877b50f946373c0f33ccca0ddca31)\"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })")
2018-12-28 15:50:45 Purposefully dropping 2 ; reason: Useless("Verification failed: Could not fetch authorities at 0x7f99f5044ddfef4c9b0a09df7d963f89c59d70d7fd997c97bddb6a5e6bc4135c: Error(UnknownBlock(\"Hash(0x7f99f5044ddfef4c9b0a09df7d963f89c59d70d7fd997c97bddb6a5e6bc4135c)\"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })")
2018-12-28 15:50:45 Dropped PeerId(QmXiB3jqqn2rpiKU7k1h7NJYeBg8WNSx9DiTRKz9ti2KSK)
2018-12-28 15:50:45 Purposefully dropping 0 ; reason: Useless("Verification failed: Could not fetch authorities at 0xc3c9239a3a307d0f8a719db1277a1c0fe5e889d85fba804e16015f3b154793b2: Error(UnknownBlock(\"Hash(0xc3c9239a3a307d0f8a719db1277a1c0fe5e889d85fba804e16015f3b154793b2)\"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })")
2018-12-28 15:50:45 Dropped PeerId(QmYcHeEWuqtr6Gb5EbK7zEhnaCm5p6vA2kWcVjFKbhApaC)
2018-12-28 15:50:46 Idle (0 peers), best: #22 (0x494e…e495)
2018-12-28 15:50:51 Idle (1 peers), best: #22 (0x494e…e495)
2018-12-28 15:50:56 Idle (1 peers), best: #23 (0x32f4…ca31)
2018-12-28 15:50:57 Purposefully dropping 3 ; reason: Useless("Verification failed: Header 0xc3c9239a3a307d0f8a719db1277a1c0fe5e889d85fba804e16015f3b154793b2 rejected: too far in the future")
2018-12-28 15:50:57 Dropped PeerId(QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN)
2018-12-28 15:51:01 Idle (0 peers), best: #24 (0x7f99…135c)
2018-12-28 15:51:06 Idle (1 peers), best: #24 (0x7f99…135c)
2018-12-28 15:51:08 Purposefully dropping 4 ; reason: Useless("Verification failed: Header 0x5b26ae201b4bf6f780877e040a20abd69f6999854ff1d53d28d154f7b6e5cb88 rejected: too far in the future")
2018-12-28 15:51:08 Dropped PeerId(QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN)
2018-12-28 15:51:11 Idle (0 peers), best: #26 (0xab49…8674)
2018-12-28 15:51:13 New external node address: /ip4/10.2.30.0/tcp/30333/p2p/QmcPNvr4zg3YCxwruQAFTUAkVX9MMsMgdDRbqFpUes8AbR
2018-12-28 15:51:16 Idle (1 peers), best: #26 (0xab49…8674)
2018-12-28 15:51:19 Purposefully dropping 5 ; reason: Useless("Verification failed: Header 0xf0b1ba7886a70e44d39943495e90b2acf108fb77180f2f506efe5ab0b9554d2a rejected: too far in the future")
2018-12-28 15:51:19 Dropped PeerId(QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN)
2018-12-28 15:51:21 Idle (0 peers), best: #28 (0xf410…53b2)
2018-12-28 15:51:26 Idle (1 peers), best: #28 (0xf410…53b2)
2018-12-28 15:51:29 New external node address: /ip4/10.2.5.0/tcp/30333/p2p/QmcPNvr4zg3YCxwruQAFTUAkVX9MMsMgdDRbqFpUes8AbR
2018-12-28 15:51:31 Purposefully dropping 6 ; reason: Useless("Verification failed: Header 0xeabe65e085ff0476019b8a0ead5ac128b95464b2c694cd3332edde9bf0710d4a rejected: too far in the future")
2018-12-28 15:51:31 Dropped PeerId(QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN)
2018-12-28 15:51:31 Idle (2 peers), best: #30 (0xce73…80d5)
2018-12-28 15:51:34 Purposefully dropping 7 ; reason: Useless("Verification failed: Could not fetch authorities at 0x75646690cbbaf56e79363c38eb75a0e458ef26f79a7b94e130245f2139fba6d1: Error(UnknownBlock(\"Hash(0x75646690cbbaf56e79363c38eb75a0e458ef26f79a7b94e130245f2139fba6d1)\"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })")
2018-12-28 15:51:34 Dropped PeerId(QmYcHeEWuqtr6Gb5EbK7zEhnaCm5p6vA2kWcVjFKbhApaC)
2018-12-28 15:51:36 Idle (2 peers), best: #30 (0xce73…80d5)
2018-12-28 15:51:41 Purposefully dropping 9 ; reason: Useless("Verification failed: Header 0xda7da6cf13a85c6336da48c8148159ef71658187437065f7f07077264ee70079 rejected: too far in the future")
2018-12-28 15:51:41 Dropped PeerId(QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN)
2018-12-28 15:51:41 Idle (1 peers), best: #31 (0xeabe…0d4a)
2018-12-28 15:51:46 Purposefully dropping 8 ; reason: Useless("Verification failed: Could not fetch authorities at 0x8d08ba24a8d0c4666bda04a2026c650c5073b31854ef751bbca60668aa4a1740: Error(UnknownBlock(\"Hash(0x8d08ba24a8d0c4666bda04a2026c650c5073b31854ef751bbca60668aa4a1740)\"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })")
2018-12-28 15:51:46 Dropped PeerId(QmXiB3jqqn2rpiKU7k1h7NJYeBg8WNSx9DiTRKz9ti2KSK)
2018-12-28 15:51:46 Idle (1 peers), best: #31 (0xeabe…0d4a)
2018-12-28 15:51:51 Idle (1 peers), best: #31 (0xeabe…0d4a)
2018-12-28 15:51:55 Purposefully dropping 10 ; reason: Useless("Verification failed: Header 0x5b7066a6c7bffa3530a9399127b56e97c54b7165e1b00114ca3ba8d8ccfc098c rejected: too far in the future")
2018-12-28 15:51:55 Dropped PeerId(QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN)
2018-12-28 15:51:56 Idle (1 peers), best: #34 (0x7564…a6d1)
2018-12-28 15:51:57 Purposefully dropping 11 ; reason: Useless("Verification failed: Could not fetch authorities at 0x3dab0551fed25d4f58e52c5482e7f09098f6cdba61baf40337927da1b73f8746: Error(UnknownBlock(\"Hash(0x3dab0551fed25d4f58e52c5482e7f09098f6cdba61baf40337927da1b73f8746)\"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })")
2018-12-28 15:51:57 Dropped PeerId(QmXiB3jqqn2rpiKU7k1h7NJYeBg8WNSx9DiTRKz9ti2KSK)
2018-12-28 15:52:01 Idle (2 peers), best: #34 (0x7564…a6d1)
2018-12-28 15:52:02 Purposefully dropping 12 ; reason: Useless("Verification failed: Header 0x8d08ba24a8d0c4666bda04a2026c650c5073b31854ef751bbca60668aa4a1740 rejected: too far in the future")
2018-12-28 15:52:02 Dropped PeerId(QmYcHeEWuqtr6Gb5EbK7zEhnaCm5p6vA2kWcVjFKbhApaC)
2018-12-28 15:52:03 New external node address: /ip4/10.2.45.0/tcp/30333/p2p/QmcPNvr4zg3YCxwruQAFTUAkVX9MMsMgdDRbqFpUes8AbR
2018-12-28 15:52:04 Purposefully dropping 13 ; reason: Useless("Verification failed: Header 0x8d08ba24a8d0c4666bda04a2026c650c5073b31854ef751bbca60668aa4a1740 rejected: too far in the future")
2018-12-28 15:52:04 Dropped PeerId(QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN)
2018-12-28 15:52:06 Idle (1 peers), best: #35 (0x5b70…098c)
2018-12-28 15:52:07 Purposefully dropping 14 ; reason: Useless("Verification failed: Header 0xcf448c83aaf0c0b9d568ac4e52d57f204a98a35b422efe62423f0cf1c1aa1fa3 rejected: too far in the future")
2018-12-28 15:52:07 Dropped PeerId(QmXiB3jqqn2rpiKU7k1h7NJYeBg8WNSx9DiTRKz9ti2KSK)
2018-12-28 15:52:11 Idle (1 peers), best: #36 (0x8d08…1740)
2018-12-28 15:52:15 Purposefully dropping 15 ; reason: Useless("Verification failed: Header 0x3dab0551fed25d4f58e52c5482e7f09098f6cdba61baf40337927da1b73f8746 rejected: too far in the future")
2018-12-28 15:52:15 Dropped PeerId(QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN)
2018-12-28 15:52:16 Idle (0 peers), best: #37 (0xcf44…1fa3)
2018-12-28 15:52:21 Idle (1 peers), best: #37 (0xcf44…1fa3)
2018-12-28 15:52:26 Purposefully dropping 16 ; reason: Useless("Verification failed: Header 0x62840fbf1481d5ed90ca75518d42e64a24710079cfc6f25695bf88fd7767aa2f rejected: too far in the future")
2018-12-28 15:52:26 Dropped PeerId(QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN)
2018-12-28 15:52:26 Idle (0 peers), best: #39 (0x3b41…f32d)
2018-12-28 15:52:31 Idle (2 peers), best: #39 (0x3b41…f32d)
2018-12-28 15:52:35 Purposefully dropping 17 ; reason: Useless("Verification failed: Header 0xea8bf8e9a03cbd84b1a5f027af2fbddc5eb7b6e81feee30b2ec433bd0ed46b51 rejected: too far in the future")
2018-12-28 15:52:35 Dropped PeerId(QmXiB3jqqn2rpiKU7k1h7NJYeBg8WNSx9DiTRKz9ti2KSK)
2018-12-28 15:52:36 Idle (1 peers), best: #40 (0x6284…aa2f)
2018-12-28 15:52:37 Purposefully dropping 18 ; reason: Useless("Verification failed: Header 0x190635d583d0ce0e70bdb5871df7182da351db6506d66bee2a7c7ee9f51d2cef rejected: too far in the future")
2018-12-28 15:52:37 Dropped PeerId(QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN)
2018-12-28 15:52:40 New external node address: /ip4/10.2.78.0/tcp/30333/p2p/QmcPNvr4zg3YCxwruQAFTUAkVX9MMsMgdDRbqFpUes8AbR
2018-12-28 15:52:41 Idle (1 peers), best: #41 (0xea8b…6b51)
2018-12-28 15:52:44 Purposefully dropping 19 ; reason: Useless("Verification failed: Header 0x8082942ff1192c41b244bc91834cb657cc21cc50059d1d17a0ee911737ee2d0f rejected: too far in the future")
2018-12-28 15:52:44 Dropped PeerId(QmXiB3jqqn2rpiKU7k1h7NJYeBg8WNSx9DiTRKz9ti2KSK)
2018-12-28 15:52:46 Purposefully dropping 20 ; reason: Useless("Verification failed: Header 0x8082942ff1192c41b244bc91834cb657cc21cc50059d1d17a0ee911737ee2d0f rejected: too far in the future")
2018-12-28 15:52:46 Dropped PeerId(QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN)
2018-12-28 15:52:46 Idle (1 peers), best: #42 (0x1906…2cef)
2018-12-28 15:52:49 New external node address: /ip4/10.2.5.1/tcp/30333/p2p/QmcPNvr4zg3YCxwruQAFTUAkVX9MMsMgdDRbqFpUes8AbR
2018-12-28 15:52:50 Purposefully dropping 21 ; reason: Useless("Verification failed: Header 0xe8e7fdd1a824a567250f162ccbfbc9f4c36e498d0f1259cec340397129f6a59e rejected: too far in the future")
2018-12-28 15:52:50 Dropped PeerId(QmYcHeEWuqtr6Gb5EbK7zEhnaCm5p6vA2kWcVjFKbhApaC)
2018-12-28 15:52:51 Idle (1 peers), best: #43 (0x8082…2d0f)
2018-12-28 15:52:55 Purposefully dropping 23 ; reason: Useless("Verification failed: Header 0xe11decdad29f8a0aa4cdff98b7e7c5c71b756b9b3d5a887069bf6c9c5acde467 rejected: too far in the future")
2018-12-28 15:52:55 Dropped PeerId(QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN)
2018-12-28 15:52:56 Idle (0 peers), best: #44 (0xe8e7…a59e)
2018-12-28 15:53:01 Idle (1 peers), best: #44 (0xe8e7…a59e)
2018-12-28 15:53:04 Purposefully dropping 24 ; reason: Useless("Verification failed: Header 0x9b7e059b5503ff844b0ffba571325becdabd136a6f90cc87752871c016195140 rejected: too far in the future")
2018-12-28 15:53:04 Dropped PeerId(QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN)
2018-12-28 15:53:04 Purposefully dropping 24 ; reason: Useless("Verification failed: Could not fetch authorities at 0xbd05679aa65e09da7cf51217b2b7af872c86037a91097b7f744338668ffd81d5: Error(UnknownBlock(\"Hash(0xbd05679aa65e09da7cf51217b2b7af872c86037a91097b7f744338668ffd81d5)\"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })")
2018-12-28 15:53:06 Idle (0 peers), best: #45 (0xe11d…e467)
2018-12-28 15:53:11 Idle (1 peers), best: #45 (0xe11d…e467)
2018-12-28 15:53:15 Purposefully dropping 25 ; reason: Useless("Verification failed: Header 0x540b80c47e765a437b306db59c982157765e5d87de7b91e5a790784a2cd43a57 rejected: too far in the future")
2018-12-28 15:53:15 Dropped PeerId(QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN)
2018-12-28 15:53:16 Purposefully dropping 26 ; reason: Useless("Verification failed: Header 0x540b80c47e765a437b306db59c982157765e5d87de7b91e5a790784a2cd43a57 rejected: too far in the future")
2018-12-28 15:53:16 Dropped PeerId(QmYcHeEWuqtr6Gb5EbK7zEhnaCm5p6vA2kWcVjFKbhApaC)
2018-12-28 15:53:16 Idle (0 peers), best: #47 (0x0451…a00e)
2018-12-28 15:53:21 New external node address: /ip4/10.2.102.0/tcp/30333/p2p/QmcPNvr4zg3YCxwruQAFTUAkVX9MMsMgdDRbqFpUes8AbR
2018-12-28 15:53:21 Idle (2 peers), best: #47 (0x0451…a00e)
2018-12-28 15:53:26 Purposefully dropping 27 ; reason: Useless("Verification failed: Header 0xa98a89f9f85cf3062c744478d35020da4bc0a9d27cba9a9dc3c90710af94a132 rejected: too far in the future")
2018-12-28 15:53:26 Dropped PeerId(QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN)
2018-12-28 15:53:26 Idle (1 peers), best: #49 (0xbd05…81d5)
2018-12-28 15:53:27 Purposefully dropping 28 ; reason: Useless("Verification failed: Header 0xa98a89f9f85cf3062c744478d35020da4bc0a9d27cba9a9dc3c90710af94a132 rejected: too far in the future")

```

**Comment by gavofyork** [comment] 2019-01-09 12:31
@tomaka please assign someone else if there's a better candidate for sorting this

**Comment by tomaka** [comment] 2019-01-09 14:45
The underlying issue seems to be "Could not fetch authorities":

```
2018-12-28 16:05:34 ImportQueue TRACE sync  Starting import of 1 blocks  (175)
2018-12-28 16:05:34 ImportQueue TRACE sync  Verifying 175(0x7a5e…341d) from 2 failed: Could not fetch authorities at 0xef9999678aa2e8b677bb14d0851bae522e2f4c4d24db35371f1dd29abe8165b9: Error(UnknownBlock("Hash(0xef9999678aa2e8b677bb14d0851bae522e2f4c4d24db35371f1dd29abe8165b9)"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
2018-12-28 16:05:34 ImportQueue TRACE sync  Useless peer 2, Verification failed: Could not fetch authorities at 0xef9999678aa2e8b677bb14d0851bae522e2f4c4d24db35371f1dd29abe8165b9: Error(UnknownBlock("Hash(0xef9999678aa2e8b677bb14d0851bae522e2f4c4d24db35371f1dd29abe8165b9)"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
2018-12-28 16:05:34 ImportQueue INFO substrate_network::io  Purposefully dropping 2 ; reason: Useless("Verification failed: Could not fetch authorities at 0xef9999678aa2e8b677bb14d0851bae522e2f4c4d24db35371f1dd29abe8165b9: Error(UnknownBlock(\"Hash(0xef9999678aa2e8b677bb14d0851bae522e2f4c4d24db35371f1dd29abe8165b9)\"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })")
```

I can take a look as I need to become more familiar with this code, but someone else can probably fix it faster.

**Comment by arkpar** [comment] 2019-01-10 08:48
My original report had nothing to do with fetching authorities.  @xlc Has a different issue.

**Comment by tomaka** [comment] 2019-01-10 16:21
I could reproduce a few times on the `master` branch, but couldn't reproduce after #1386.
After #1386, the fetching authorities error was way more common though.

**Comment by tomaka** [comment] 2019-02-04 11:09
The underlying problem is the behaviour to adopt when two nodes connect to each other simultaneously.

If we dial a remote and immediately start sending packets on that connection, and at the same time the remote dials our local node and immediately starts sending packets on their connection, there's inevitably some kind of mess happening.

Right now, in order to simplify the usage, libp2p enforces that there's only one simultaneous connection to each peer (the sync layer of Substrate isn't capable of handling multiple connections at the moment anyway).

If two nodes dial each simultaneously, when the first connection gets open the API of libp2p will report it and the connection will start being used. Then when the second connection is actually open, the two peers agree on one connection to drop (the node with the lowest ID keeps its outgoing connection), and if it is the existing one, then the API of libp2p reports that the unique exposed connection has been closed. It will then report that it has been reopened.

The messages in the logs reflect that situation.

This is also, for a slightly different reason, why the tests in #1634 fail at the moment. We start making a discovery RPC query on a connection, but then the connection gets closed because of a duplicate, and we never receive the result of the query.

**Comment by tomaka** [comment] 2019-02-04 11:10
That's why this issue is critical: it only happens on a local network, where the lag is 0.

**Comment by gavofyork** [comment] 2019-02-04 14:57
Well, I'd like to close it one way or another. If it's predictable and well understood, maybe we can change the logs to ensure it's clear that the thing we're dropping is fine because it's redundant? Or if it's not certain that it's redundant, maybe we can identify it and handle this situation more gracefully?

**Comment by tomaka** [comment] 2019-02-04 17:44
> If it's predictable and well understood, maybe we can change the logs to ensure it's clear that the thing we're dropping is fine because it's redundant?

I'd go with this option, however it's blocked on https://github.com/libp2p/rust-libp2p/issues/844.

**Comment by gavofyork** [comment] 2019-02-06 08:44
ok - i'll delay to next milestone as we wait for upstream.

**Comment by kenhuang** [comment] 2019-03-20 22:56
We also encounter this error message in the recent version of the substrate, local node running in release mode with `--pruning=archive`, all validator node also start with `--pruning=archive`.

Every time restart local node, is able to sync further to the new block number, but stop with `too far in the future` msg.

Let me know if you need more debug logs.

![Screen Shot 2019-03-21 at 11 52 42 AM](https://user-images.githubusercontent.com/205194/54724400-e8f20780-4bcf-11e9-91c3-0d4b645ba30a.png)


```
2019-03-21 11:50:53 Node name: heartbreaking-legs-6939
2019-03-21 11:50:53 Roles: FULL
2019-03-21 11:50:53 Best block: #30
2019-03-21 11:50:53 Local node address is: /ip4/0.0.0.0/tcp/30333/p2p/QmUvmUyDhfUph6T8ZVi4vSpZoBu1q3YXEFTfS4rF4eFSEx
2019-03-21 11:50:53 Kademlia random query has yielded empty results
2019-03-21 11:50:53 Listening for new connections on 127.0.0.1:9944.
2019-03-21 11:50:53 Dropping 1 because "Verification failed: Header 0x2a63e2698cfadba66c6fd5cc316a0a62916f3d5f227cf3bbe4f04573b6527493 rejected: too far in the future"
2019-03-21 11:50:58 Idle (0 peers), best: #35 (0x3852…eaca), finalized #20 (0xffa5…dc1c), ⬇ 0.9kiB/s ⬆ 0.6kiB/s
2019-03-21 11:51:03 Idle (0 peers), best: #35 (0x3852…eaca), finalized #20 (0xffa5…dc1c), ⬇ 55 B/s ⬆ 46 B/s
2019-03-21 11:51:08 Idle (0 peers), best: #35 (0x3852…eaca), finalized #20 (0xffa5…dc1c), ⬇ 0.1kiB/s ⬆ 0.1kiB/s
2019-03-21 11:51:13 Idle (0 peers), best: #35 (0x3852…eaca), finalized #20 (0xffa5…dc1c), ⬇ 0.2kiB/s ⬆ 0.2kiB/s
2019-03-21 11:51:17 Dropping 3 because "Verification failed: Header 0xb7718f8d661add3b1d0abd6ffcad2c236817d2403c72e566854c75a73cac4d83 rejected: too far in the future"
2019-03-21 11:51:18 Idle (1 peers), best: #38 (0xefa8…4f96), finalized #35 (0x3852…eaca), ⬇ 1.4kiB/s ⬆ 1.1kiB/s
2019-03-21 11:51:23 Idle (1 peers), best: #38 (0xefa8…4f96), finalized #37 (0xa90c…3a99), ⬇ 0.7kiB/s ⬆ 0.3kiB/s
2019-03-21 11:51:24 Imported #39 (0xb771…4d83)
2019-03-21 11:51:24 Dropping 2 because "Verification failed: Header 0xae013913f117d74d4002f1ea4aaaa749bc15ce661f720207c230a380c91fdf76 rejected: too far in the future"
2019-03-21 11:51:28 Idle (0 peers), best: #39 (0xb771…4d83), finalized #37 (0xa90c…3a99), ⬇ 0.3kiB/s ⬆ 0.1kiB/s
2019-03-21 11:51:33 Idle (0 peers), best: #39 (0xb771…4d83), finalized #37 (0xa90c…3a99), ⬇ 0.4kiB/s ⬆ 0.4kiB/s
2019-03-21 11:51:38 Idle (0 peers), best: #39 (0xb771…4d83), finalized #37 (0xa90c…3a99), ⬇ 0 ⬆ 0

```

**Comment by arkpar** [comment] 2019-03-21 08:54
@kenhuang Make sure your system clock is synced
https://time.is/

**Comment by gavofyork** [comment] 2019-03-27 17:20
Will reopen if all the new networking refactoring doesn't solve it.

**Closed** 2019-03-27 17:20 UTC
Labels: F2-bug 🐜

**Comment by bellaj** [comment] 2022-08-22 20:37
A synchronization issue would cause such an error

check in both peers the sync time using `timedatectl` If there is a time lag between them 
run
`systemctl status systemd-timesyncd.service
`
if the service is disabled enable it

`systemctl start systemd-timesyncd.service
`
