### ISSUE TITLE
Transactions not being queued

### ISSUE THREAD

**Issue by maxsam4** [paritytech/substrate#2309] opened 2019-04-17 11:09 UTC
If you create a transaction for block N and submit it but block N gets mined before your transaction can be included OR there are 257 transactions lined up already for block N, your transaction will fail with an error.

Ideally, the transaction should get queued and included in the next block, N + 1 rather than throwing an error.

This is an extended issue of #2308 
Please refer to that Issue for reproduction script and error details.

**Comment by rphmeier** [comment] 2019-04-17 13:12
cc @tomusdrw

**Comment by tomusdrw** [comment] 2019-04-17 13:22
Duplicate of #2308, that's the same issue and a limitation of the runtime not the pool. Whether it's a bug is also not certain imho.

**Closed by tomusdrw** 2019-04-17 13:22 UTC
Labels: F2-bug 🐜, Z0-unconfirmed
