### ISSUE TITLE
Bump libsecp256k1 to 0.5.0

### ISSUE THREAD

**Issue by s3krit** [paritytech/substrate#9383] opened 2021-07-19 14:40 UTC
To resolve https://rustsec.org/advisories/RUSTSEC-2021-0076.html we should bump libsecp256k1 to v0.5.0.
cc @sorpaas 

https://docs.rs/libsecp256k1/0.5.0/libsecp256k1/index.html

**Comment by bkchr** [comment] 2021-07-19 19:56
Duplicate of https://github.com/paritytech/substrate/issues/9356

**Closed by bkchr** 2021-07-19 19:56 UTC
