### ISSUE TITLE
Move justification import to the import queue

### ISSUE THREAD

**Issue by andresilva** [paritytech/substrate#1482] opened 2019-01-18 15:55 UTC
#1410 introduces the ability to request and import justifications from the network. These are currently imported synchronously as they're received from the network, and should instead be imported asynchronously in the import queue. 

https://github.com/paritytech/substrate/blob/ea3d06a9fc232be6c31afc73718a3ecca13fd6ce/core/network/src/protocol.rs#L420-L425

**Comment by gterzian** [comment] 2019-01-21 07:34
This might be something that could fit well in with https://github.com/paritytech/substrate/pull/1327(soon to be merged), as well as the pending https://github.com/paritytech/substrate/pull/1327(which would be ready for review after a rebase once the first one merges). 

the call to `import_queue.import_justification` could be replaced by sending a message to the import-qeue, with the result sent back in message to protocol. 

@andresilva Have you started working on this already? Would it be possible to wait for these other two to merge?

**Comment by gterzian** [comment] 2019-01-24 12:16
I've added a commit dealing with this at https://github.com/paritytech/substrate/pull/1327/commits/6f897a9b4388eaa883d9007b579cd8a415d6a51a(https://github.com/paritytech/substrate/pull/1327)

In some ways it shows how the channel based approach makes it trivial to make such an operation async...

**Comment by tomaka** [comment] 2019-05-05 12:26
Whenever we receive block in the network, we block the protocols thread for 30+ seconds in debug mode and ~1.5 seconds in release mode. Additionally, since the channel between the network thread and the protocols thread only has capacity for 4 elements, this also entirely blocks the network thread for this duration. And since the informant is waiting for events from the protocols thread, this also blocks the informant.

**Comment by tomaka** [comment] 2019-05-05 12:36
I'm currently rewriting the threading story of the `network` crate, but I'm moving a bit blindly and I'm not sure whether my changes will cover this issue.

**Comment by tomaka** [comment] 2019-05-05 13:07
This is most likely also the reason why `Ctrl+C` takes a lot of time.

**Comment by gterzian** [comment] 2019-05-06 05:44
You could try to increase the buffer of both these channels, or make them unbounded to see if that makes a difference:

1. https://github.com/paritytech/substrate/blob/2e2bcab0d6e1d2d0f699efe0c8be0b7dcab45708/core/consensus/common/src/import_queue.rs#L445

2. https://github.com/paritytech/substrate/blob/2e2bcab0d6e1d2d0f699efe0c8be0b7dcab45708/core/consensus/common/src/import_queue.rs#L256

However they probably should be bounded at some level in the light of https://github.com/paritytech/substrate/issues/1832

**Comment by andresilva** [comment] 2019-05-07 11:14
@gterzian I wonder if justification import should also be moved to the worker since verifying the justification is a bit expensive.

**Comment by gterzian** [comment] 2019-05-08 07:05
Yes that is a good idea, and we need to think it through a little bit in the light of the following:
1. The channel to the import worker is bounded, and probably should be(?). So if we add the justification import to the worker, and the worker ends up being "more busy", then the import queue will eventually also block on the send to the worker. 
2. Maybe we should have a worker for the justification import, and one for the block import, using each their own bounded channel?
3. The thing is now we already in a way use the import queue as the "justification import worker", separate from the block import worker. So using a third thread would only matter, it would seem, if the current problem is that the import queue is too slow as a "router" of messages to the import worker(and a potential justification import worker). So if the problem is that the import queue is too busy importing justification, and the channel in the meantime fills up, while the import worker is idle, then adding a third thread and a second channel might free up the import queue to act as a faster "router" indeed.
4. The issue might also well be that the "blocking" experienced is simply the channel to the import worker filling up, and then the entire system running as fast as we can import blocks. This is potentially a good thing, in the sense that it's the intent of using bounded channels and limiting opportunities for DOS.

@tomaka On which branch did you experience did you note the problem?

**Comment by tomaka** [comment] 2019-05-08 07:41
> @tomaka On which branch did you note the problem?

Master for the past few months. I've been talking about this issue in the substrate Riot channel a few times, but I hadn't dug into it until recently.

**Comment by andresilva** [comment] 2019-05-08 10:40
I think in this case the reason for the blocking is 4), although 3) could also be a reason for blocking the "router" that's why I suggested moving justification import to the worker. What do you think about making the channel from `BasicQueue` -> `BlockImporter` unbounded, this would make sure that the rest of the system doesn't block when pushing work to the queue. We could then also increase the capacity of the channel from `BlockImporter` to `BlockImportWorker` (not sure how much but imo 4 is too low given that we'll be handling block import requests from several peers). And this is also the place where we should handle back-pressure in the future.

**Comment by gterzian** [comment] 2019-05-08 10:57
> What do you think about making the channel from BasicQueue -> BlockImporter unbounded

I think the problem with making one part of the "pipeline" unbounded, is that that part is then simply going to provide a buffer for the other parts, so we might as well make everything unbounded. 

Why not make everything unbounded? Perhaps the "we've getting too many block import messages" could be handled more specifically, either via the peerset, or another mechanism that would involve network?

**Comment by tomaka** [comment] 2019-07-24 13:44
Done in #2856

**Closed by tomaka** 2019-07-24 13:44 UTC
Labels: F7-optimisation ⏱, M4-core
