### ISSUE TITLE
Substrate fails to start

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#2715] opened 2019-05-29 10:17 UTC
After clearing my database, Substrate fails to start:

```
2019-05-29 11:50:46 Substrate Node
2019-05-29 11:50:46   version 2.0.0-76e03c7d-x86_64-linux-gnu
2019-05-29 11:50:46   by Parity Technologies, 2017-2019
2019-05-29 11:50:46 Chain specification: Flaming Fir
2019-05-29 11:50:46 Node name: bumpy-ticket-2672
2019-05-29 11:50:46 Roles: FULL
2019-05-29 11:50:47 Generated a new keypair: 3fefc6c5bafb7443c1ff1d9ac6ad513869b65944d580728533472babc9538d60 (5DWY6tfa...)
2019-05-29 11:50:48 Initializing Genesis block/state (state: 0x4ac9…4dec, header-hash: 0xe1aa…65e6)
Error starting the node: Client(VersionInvalid)

Input("Client(VersionInvalid)")
```

Here is a backtrace, which I generated by replacing returning the error with panicking:

```
   8: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::runtime_version::h9e7949242e9c387f (0x5605f2f13ee4)
             at /home/pierre/Projets/substrate-2/core/client/src/call_executor.rs:299
   9: substrate_client::client::Client<B,E,Block,RA>::runtime_version_at::h60a0bf0d18dc4d11 (0x5605f2860a96)
             at /home/pierre/Projets/substrate-2/core/client/src/client.rs:405
  10: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::runtime_version_at::h54d5512bb16fdc02 (0x5605f284baa4)
             at /home/pierre/Projets/substrate-2/core/client/src/client.rs:1389
  11: <node_runtime::RuntimeApiImpl<C> as substrate_client::runtime_api::ApiExt<<node_runtime::Runtime as sr_primitives::traits::GetNodeBlockType>::NodeBlock>>::runtime_version_at::hf7325d506ed4ab38 (0x5605f2f37157)
             at /home/pierre/Projets/substrate-2/node/runtime/src/lib.rs:254
  12: substrate_client::runtime_api::ApiExt::has_api::h4acd78932b39c4a1 (0x5605f2f26675)
             at /home/pierre/Projets/substrate-2/core/client/src/runtime_api.rs:87
  13: substrate_consensus_aura::authorities::{{closure}}::h45100cd01584e889 (0x5605f3ae119a)
             at /home/pierre/Projets/substrate-2/core/consensus/aura/src/lib.rs:761
  14: core::option::Option<T>::or_else::hae3494ec816c9960 (0x5605f29c9891)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/option.rs:714
  15: substrate_consensus_aura::authorities::ha0ecfbe5f25d37c9 (0x5605f3ae1027)
             at /home/pierre/Projets/substrate-2/core/consensus/aura/src/lib.rs:756
  16: <substrate_consensus_aura::AuraVerifier<C,E,P> as substrate_consensus_common::Authorities<B>>::authorities::h05f0ce593aae4125 (0x5605f3ad6100)
             at /home/pierre/Projets/substrate-2/core/consensus/aura/src/lib.rs:714
  17: <substrate_consensus_aura::AuraVerifier<C,E,P> as substrate_consensus_common::import_queue::Verifier<B>>::verify::h441749fbcab46e49 (0x5605f3adcfad)
             at /home/pierre/Projets/substrate-2/core/consensus/aura/src/lib.rs:625
  18: substrate_consensus_common::import_queue::import_single_block::he66490fd08af9bb5 (0x5605f382208a)
             at /home/pierre/Projets/substrate-2/core/consensus/common/src/import_queue.rs:907
  19: substrate_consensus_common::import_queue::import_many_blocks::h7deb0f09fc3b5678 (0x5605f381d9f6)
             at /home/pierre/Projets/substrate-2/core/consensus/common/src/import_queue.rs:836
  20: substrate_consensus_common::import_queue::BlockImportWorker<B,V>::import_a_batch_of_blocks::h0eba1dbbe7b24ac7 (0x5605f382c9c6)
             at /home/pierre/Projets/substrate-2/core/consensus/common/src/import_queue.rs:577
  21: substrate_consensus_common::import_queue::BlockImportWorker<B,V>::new::{{closure}}::h8e308472509ae1cc (0x5605f382dbca)
             at /home/pierre/Projets/substrate-2/core/consensus/common/src/import_queue.rs:552
  22: std::sys_common::backtrace::__rust_begin_short_backtrace::he2b5ef75112da9e2 (0x5605f3043c72)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/sys_common/backtrace.rs:136
  23: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hc0fcd03586ce9aea (0x5605f2dbeac0)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/thread/mod.rs:470
  24: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h56cc85493029a282 (0x5605f34277b0)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panic.rs:309
  25: std::panicking::try::do_call::h021fd9257e8c7dbf (0x5605f3777246)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:293
  26: __rust_maybe_catch_panic (0x5605f5c752a9)
             at src/libpanic_unwind/lib.rs:87
  27: std::panicking::try::h92faea75a67dc639 (0x5605f37751af)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:272
  28: std::panic::catch_unwind::h75aad83050254155 (0x5605f3427cd2)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panic.rs:388
  29: std::thread::Builder::spawn_unchecked::{{closure}}::hf95842370bea628d (0x5605f2dbe829)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/thread/mod.rs:469
  30: core::ops::function::FnOnce::call_once{{vtable.shim}}::hb3eb10229e38c528 (0x5605f2b7abf3)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/ops/function.rs:231
  31: call_once<(),FnBox<()>> (0x5605f5c5d22e)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
  32: call_once<(),alloc::boxed::Box<FnBox<()>>> (0x5605f5c7460f)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
      start_thread
             at src/libstd/sys_common/thread.rs:14
      thread_start
             at src/libstd/sys/unix/thread.rs:80
  33: start_thread (0x7efd7eb6e5a1)
  34: __clone (0x7efd7ea81162)
  35: <unknown> (0x0)
```

It's obviously some sort of race condition that apparently only happens on this laptop.

**Comment by arkpar** [comment] 2019-05-29 11:40
Why do you think this is a race condition?
Looks like some recent changes broke runtime compatibility.
```
main TRACE executor  Invalid code presented to executor (Wasmi(Instantiation("Export ext_storage_changes_root has different signature Signature { params: [I32, I32, I64, I32], return_type: Some(I32) }")))
```

**Comment by arkpar** [comment] 2019-05-29 11:45
Caused by #2666

**Comment by tomaka** [comment] 2019-05-29 11:51
> Why do you think this is a race condition?

The network sync tests show me the same error, but only on this machine. On both CI and my machine at home these tests pass.

**Comment by arkpar** [comment] 2019-05-31 06:15
Since the network will be reset there's no need to do compatibility fix for this.

**Closed by arkpar** 2019-05-31 06:15 UTC
Labels: F2-bug 🐜

**Comment by rezaprimasatya** [comment] 2019-06-11 07:57
Got same issue.
I have reset the network but still got the same issue.

<img width="1440" alt="Screen Shot 2019-06-11 at 14 55 50" src="https://user-images.githubusercontent.com/4263809/59253803-30c97d80-8c59-11e9-9456-5a4ba5ead81b.png">

**Comment by bkchr** [comment] 2019-06-11 08:17
@rezaprimasatya you misunderstood this, with "reset network`, we mean to reset the Flaming Fir network to support the breaking changes of master. There is not that much you can do at the moment, besides starting your own local network.

**Comment by rezaprimasatya** [comment] 2019-06-11 08:30
@bkchr apologise and thanks for your explanation.
Waiting for the update
