### ISSUE TITLE
Thread 'main-tokio-' panicked at 'supplied instant is later than self'

### ISSUE THREAD

**Issue by drewstone** [paritytech/substrate#4949] opened 2020-02-17 10:57 UTC
Edgeware node crashes on recent update to substrate: https://github.com/hicommonwealth/edgeware-node/issues/137

**Comment by bkchr** [comment] 2020-02-17 11:25
@tomaka the linked issue contains a back trace that shows that the node crashes in libp2p.

**Comment by tomaka** [comment] 2020-02-17 12:23
> in libp2p

(in sc-network)

We don't perform any arithmetics on `Instant`s in `LegacyProto::poll`.
Is that with the Substrate master branch? I suppose that it's in release (where the backtrace isn't necessarily exact)?

**Comment by drewstone** [comment] 2020-02-17 15:06
@tomaka correct its in a release, it was substrate master from last week.

**Comment by tomaka** [comment] 2020-02-17 15:13
I looked at all the subtractions in `legacy_proto.rs`. There were only two, and they could indeed panic. I opened #4951. I'm not sure it fixes the issue, but it is very likely.

What is weird to me is that both you and @pepyakin noticed this issue approximately at the same time, even though it never happened before, and we haven't touched this code at all recently.

**Comment by JoshOrndorff** [comment] 2020-04-01 13:34
We're still encountering this issue on the node template at v2.0.0-alpha.5. [This tag](https://github.com/substrate-developer-hub/substrate-node-template/releases/tag/v2.0.0-alpha.5) specifically.

It doesn't happen every time, and seems to happen most often with a `--dev` node. The Substrate version used in this node template was released a month after #4951 was merged and contains those changes.

Here is the complete backtrace https://gist.github.com/JoshOrndorff/c2ea0eb613798a17f5a27287ef587955

**Comment by gnunicorn** [comment] 2020-04-01 14:27
@JoshOrndorff yes, same bug, different part of the code base it seems. While the older report was for libp2p, yours [shows this to be in the authorship module](https://gist.github.com/JoshOrndorff/c2ea0eb613798a17f5a27287ef587955#file-backtrace-L18), where this happens:
```rust
futures_timer::Delay::new((deadline - (self.now)()) / 8),
```

**Comment by JoshOrndorff** [comment] 2020-04-01 14:42
After a `cargo clean` and rebuild with `cargo build --release` I can no longer reproduce the panic.

I guess this issue should be closed because it is so hard to reproduce.

**Closed** 2020-04-02 10:38 UTC
Labels: F2-bug 🐜
