### ISSUE TITLE
Node must remember peers from previous runs

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/substrate#11853] opened 2022-07-17 15:53 UTC
Right now there is no persistence of known peers in Substrate's networking. This is a problem though because every time on node restart it'll reach out to the same bootstrap nodes over and over again, which is a point of centralization. It gets a bit better if node didn't have a long downtime and other peers will try to reconnect back to it, but overall it is something that needs to be fixed.

Something like collecting dialable peers and selecting a random subset of them on restart with bootstrap nodes as a fallback only would be a good start I think.

**Comment by bkchr** [comment] 2022-07-17 22:58
Duplicate of: https://github.com/paritytech/substrate/issues/4750

**Closed by bkchr** 2022-07-17 22:58 UTC
