### ISSUE TITLE
Database dead after restart

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#826] opened 2018-09-27 16:59 UTC
To reproduce:

```
cargo run
sleep 20
killall substrate
cargo run
```

It will no longer sync.

**Comment by gavofyork** [comment] 2018-09-27 17:01
Example output:

```
➜  substrate git:(gav-ss58inbft) ./target/release/substrate --name "♋<fe0f>  Sixty-nine ♋<fe0f>"  b/
2018-09-27 17:34:22 Substrate Node
2018-09-27 17:34:22   version 0.1.0-619b4d47-x86_64-macos
2018-09-27 17:34:22   by Parity Technologies, 2017, 2018
2018-09-27 17:34:22 Chain specification: BBQ Birch
2018-09-27 17:34:22 Node name: ♋️  Sixty-nine ♋️
2018-09-27 17:34:22 Roles: FULL
2018-09-27 17:34:22 Best block: #0
2018-09-27 17:34:22 Local node address is: /ip4/0.0.0.0/tcp/30333/p2p/QmcLjmkXkV7ALM28trVmR2M8xAQ4Sa9zpSbsedm9f8g99R
2018-09-27 17:34:22 Idle (0 peers), best: #0 (0x0000…dc79)
2018-09-27 17:34:27 Idle (0 peers), best: #0 (0x0000…dc79)
2018-09-27 17:34:29 New external node address: /ip4/77.208.28.122/tcp/30333/p2p/QmcLjmkXkV7ALM28trVmR2M8xAQ4Sa9zpSbsedm9f8g99R
2018-09-27 17:34:32 Syncing, target=#1002 (4 peers), best: #0 (0x0000…dc79)
2018-09-27 17:34:37 Syncing 15.8 bps, target=#1003 (4 peers), best: #79 (0x4fad…0614)
2018-09-27 17:34:42 Idle (4 peers), best: #199 (0x8cdb…f58d)
2018-09-27 17:34:47 Idle (5 peers), best: #340 (0xf621…4bec)
2018-09-27 17:34:52 Idle (5 peers), best: #470 (0x01ce…d877)
2018-09-27 17:34:57 Idle (5 peers), best: #607 (0x0238…4faf)
2018-09-27 17:35:02 Idle (5 peers), best: #743 (0xd7f0…b7a0)
2018-09-27 17:35:07 Idle (5 peers), best: #881 (0x71ab…f80a)
2018-09-27 17:35:12 Imported #1003 (0xd1c7…7636)
2018-09-27 17:35:12 Imported #1005 (0x5e26…f8e5)
2018-09-27 17:35:12 Idle (5 peers), best: #1007 (0xd8ff…b67f)
2018-09-27 17:35:12 Imported #1008 (0xd504…ccf7)
2018-09-27 17:35:12 Imported #1009 (0x6037…2eeb)
2018-09-27 17:35:15 Imported #1010 (0xdbcc…148f)
2018-09-27 17:35:17 Idle (5 peers), best: #1010 (0xdbcc…148f)
2018-09-27 17:35:17 Imported #1011 (0xc180…380f)
2018-09-27 17:35:22 Idle (5 peers), best: #1011 (0xc180…380f)
2018-09-27 17:35:22 Imported #1012 (0x117e…47bc)
2018-09-27 17:35:26 Imported #1013 (0xef51…3ab5)
2018-09-27 17:35:27 Idle (5 peers), best: #1013 (0xef51…3ab5)
2018-09-27 17:35:32 Idle (5 peers), best: #1013 (0xef51…3ab5)
2018-09-27 17:35:32 Imported #1014 (0x2660…c5c4)
2018-09-27 17:35:37 Idle (5 peers), best: #1014 (0x2660…c5c4)
2018-09-27 17:35:38 Imported #1015 (0xf877…ac10)
^C%                                                                                                                                                                                                                                                           ➜  substrate git:(gav-ss58inbft) ./target/release/substrate --name "♋<fe0f>  Sixty-nine ♋<fe0f>"
2018-09-27 17:35:41 Substrate Node
2018-09-27 17:35:41   version 0.1.0-619b4d47-x86_64-macos
2018-09-27 17:35:41   by Parity Technologies, 2017, 2018
2018-09-27 17:35:41 Chain specification: BBQ Birch
2018-09-27 17:35:41 Node name: ♋️  Sixty-nine ♋️
2018-09-27 17:35:41 Roles: FULL
2018-09-27 17:35:41 Best block: #0
2018-09-27 17:35:41 Local node address is: /ip4/0.0.0.0/tcp/30333/p2p/QmcLjmkXkV7ALM28trVmR2M8xAQ4Sa9zpSbsedm9f8g99R
2018-09-27 17:35:42 Idle (0 peers), best: #0 (0x0000…dc79)
2018-09-27 17:35:45 New external node address: /ip4/77.208.28.122/tcp/30333/p2p/QmcLjmkXkV7ALM28trVmR2M8xAQ4Sa9zpSbsedm9f8g99R
2018-09-27 17:35:47 Syncing, target=#1016 (2 peers), best: #0 (0x0000…dc79)
2018-09-27 17:35:52 Syncing, target=#1017 (5 peers), best: #0 (0x0000…dc79)
2018-09-27 17:35:57 Syncing, target=#1018 (5 peers), best: #0 (0x0000…dc79)
2018-09-27 17:36:02 Syncing, target=#1019 (5 peers), best: #0 (0x0000…dc79)
2018-09-27 17:36:07 Syncing, target=#1019 (5 peers), best: #0 (0x0000…dc79)
2018-09-27 17:36:12 Syncing, target=#1021 (5 peers), best: #0 (0x0000…dc79)
2018-09-27 17:36:17 Syncing, target=#1022 (5 peers), best: #0 (0x0000…dc79)
2018-09-27 17:36:22 Syncing, target=#1023 (5 peers), best: #0 (0x0000…dc79)
```

**Comment by snd** [comment] 2018-09-27 19:09
reproduced. traced it down to meta not being read correctly on restart (best_number = 0). fixed in https://github.com/paritytech/substrate/pull/827. my bad. i got confused because `columns::HEADER` gets passed into `read_meta` and thought it was a mistake. it's a bit inconsistent with the other `read_*` functions which get all  columns they access passed as arguments rather than being hardcoded as for `read_meta`. ended up breaking the exact thing i was trying to fix

**Closed** 2018-09-27 19:43 UTC
Labels: F0-consensus
