### ISSUE TITLE
endless tries to connect to yourself

### ISSUE THREAD

**Issue by algys** [paritytech/substrate#1211] opened 2018-12-04 21:47 UTC
If the node receives a network address pointing to itself(e.g. `"/ip4/127.0.0.1/tcp/30333/p2p/QmZEFcNvWmqjx8r8R2mSnXtQsShgRVG1R2MH9tWNbvxHDr"`), then occurs endless connection attempts.

Potentially, this can cause unnecessary load on the node and a cutting down of performance.

Simple way to reproduce:
 - add `"/ip4/127.0.0.1/tcp/30333/p2p/QmZEFcNvWmqjx8r8R2mSnXtQsShgRVG1R2MH9tWNbvxHDr"` to boot nodes in config 
- run node `RUST_LOG=debug cargo run -- --dev --chain local`

Then in the logs you can see repeated connection attempts:
`libp2p_core::upgrade::apply  Successfully applied negotiated protocol`

and lines about fails:
`sub-libp2p  Rejected connection to/from ourself: Listener { listen_addr: "/ip4/0.0.0.0/tcp/30333", send_back_addr: "/ip4/127.0.0.1/tcp/36242" }`

**Comment by rphmeier** [comment] 2018-12-04 22:32
cc @tomaka @dvdplm

**Comment by tomaka** [comment] 2018-12-05 10:35
> Potentially, this can cause unnecessary load on the node and a cutting down of performance.

What is supposed to happen right now (although I haven't tested) is that when we try to connect to ourself, the connection is rejected and a delay of 2 seconds is put in place. Two seconds later we try again and fail. Then 4 seconds later. Then 8 seconds later. This happens until the reputation of the node falls to 0, after which the delay is something like two hours.

On a long-running node, we will briefly try to connect to ourselves every two hours and get immediately rejected, which I think is ok.

However this is mostly the protection-against-spoofing system in action, and there is indeed the underlying problem which is that nodes report `127.0.0.1` as their IP address. The fact that we are generic over the concept of a multiaddress makes everything a bit difficult in this regard.

**Comment by tomaka** [comment] 2018-12-05 10:37
We cannot just add something like `if ip == 127.0.0.1 { skip }`, otherwise nodes on the same machine could no longer communicate with each other.

**Comment by rphmeier** [comment] 2018-12-05 14:57
@tomaka is there perhaps an exception for bootnodes in the exponential backoff?

**Comment by BoogerWooger** [comment] 2018-12-06 11:06
> We cannot just add something like `if ip == 127.0.0.1 { skip }`, otherwise nodes on the same machine could no longer communicate with each other.

maybe `if ip == 127.0.0.1 && port ==<currently_listening_port>` ?

**Comment by tomaka** [comment] 2019-07-24 14:00
Closing for two reasons:

- Duplicate of #2208 
- We now automatically refuse dialing our own `PeerId` without even trying.

**Closed by tomaka** 2019-07-24 14:00 UTC
Labels: F7-footprint 👣
