### ISSUE TITLE
Allow full and light client on-disk databases to co-exist

### ISSUE THREAD

**Issue by expenses** [paritytech/substrate#6880] opened 2020-08-12 10:59 UTC
This is a nice small issue to give the light client some love. If you run the full node for a bit, then a light node with `--light`, you get the following error:
```rust
Error: Service(Client(Backend("Unexpected database type. Expected: light")))
```

It's easy enough to change the paths where the databases are put, it might be best to put the full db in `/db/full/` and the light db in `/db/light`.

**Comment by expenses** [comment] 2020-08-12 12:27
It's also important to consider that moving the path of the full db means that you have to add code that migrates from the old path.

**Comment by expenses** [comment] 2020-08-17 11:50
>It's easy enough to change the paths where the databases are put, it might be best to put the full db in /db/full/ and the light db in /db/light.

(Pinging to get a consensus) @seunlanlege @rakanalh @danforbes @gnunicorn I believe this would be the best way to things, anyone else have an opinion?

**Comment by rakanalh** [comment] 2020-08-17 12:27
I think this is worth doing as i imagine there would be use cases where one would want to switch between the two.

**Comment by seunlanlege** [comment] 2020-08-17 13:52
+1

**Comment by niklasad1** [comment] 2020-08-25 12:28
Sounds good to me, however, duplicate of https://github.com/paritytech/substrate/issues/2204 but the description is better in this issue so feel free to close https://github.com/paritytech/substrate/issues/2204

**Comment by hirschenberger** [comment] 2021-04-18 10:19
I'm currently working on this and different database roles are stored in the corresponding subdirectories as discussed above.

But how should we deal with existing databases to avoid users to resync their state. I suggest migrating to the new structure by: 

* checking for the existence of the said dir and if they don't exist 
* check if the current role matches the database role
* create the new dir
* move the existing data to the new dir.

Is it possible to move a ParityDb and RocksDb by just moving the files?

**Comment by bkchr** [comment] 2021-04-19 21:47
> Is it possible to move a ParityDb and RocksDb by just moving the files?

Yes

**Comment by hirschenberger** [comment] 2021-05-24 07:05
Can I have a review please?

**Comment by hirschenberger** [comment] 2021-07-07 17:13
I just need a review.

**Comment by hirschenberger** [comment] 2021-09-01 05:41
#9645 is waiting for a review.

**Closed** 2021-09-07 13:31 UTC
Labels: P5-sometimesoon, Q0-trivial
