### ISSUE TITLE
libp2p warnings on Kusama - New inbound substream to PeerId(XXX) exceeds inbound substream limit.

### ISSUE THREAD

**Issue by tdimitrov** [paritytech/substrate#13266] opened 2023-01-29 09:09 UTC
During an oncall shift the following warning was flooding the logs on Kusama nodes:
```
2023-01-29 10:26:23 | 2023-01-29 08:26:23.804  WARN tokio-runtime-worker libp2p_kad::handler: New inbound substream to PeerId("12D3KooWEFGpfavsT8q2pRYkcRnZzLziwNnmH3ZG4wpw8BZgU5QR") exceeds inbound substream limit. No older substream waiting to be reused. Dropping new substream. |  
-- | -- | --
```
This was happening for multiple peer ids - e.g. `12D3KooWEFGpfavsT8q2pRYkcRnZzLziwNnmH3ZG4wpw8BZgU5QR`, `12D3KooWFqu6bF3qjZmNmMwAfwuBCRcJVyKDGAfJXt1LrnYQ4xew`.

Link to logs: https://grafana.parity-mgmt.parity.io/goto/a5IXMzAVk?orgId=1

**Comment by tdimitrov** [comment] 2023-01-29 12:39
A relevant discussion: https://github.com/libp2p/rust-libp2p/discussions/2957

**Comment by bkchr** [comment] 2023-01-29 16:24
Duplicate of https://github.com/paritytech/polkadot/issues/6174

**Closed by bkchr** 2023-01-29 16:24 UTC
