### ISSUE TITLE
The benchmark result of pallet-grandpa does not match WeightInfo trait

### ISSUE THREAD

**Issue by jiguantong** [paritytech/substrate#11835] opened 2022-07-14 02:47 UTC
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Version: 4.0.0-dev

### Benchmark result [benchmarking.rs](https://github.com/paritytech/substrate/blob/master/frame/grandpa/src/benchmarking.rs#L26)
```rust
/// Weight functions for `pallet_grandpa`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_grandpa::WeightInfo for WeightInfo<T> {
	fn check_equivocation_proof(x: u32, ) -> Weight {
		(62_998_000 as Weight)
			// Standard Error: 8_580_000
			.saturating_add((14_227_000 as Weight).saturating_mul(x as Weight))
	}
	// Storage: Grandpa Stalled (r:0 w:1)
	fn note_stalled() -> Weight {
		(2_364_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}
```
### `pallet_grandpa::WeightInfo` [trait](https://github.com/paritytech/substrate/blob/master/frame/grandpa/src/lib.rs#L358)
```rust
pub trait WeightInfo {
	fn report_equivocation(validator_count: u32) -> Weight;
	fn note_stalled() -> Weight;
}
``` 
### Build error
```shell
  error[E0407]: method `check_equivocation_proof` is not a member of trait `pallet_grandpa::WeightInfo`
    --> /home/workspace/darwinia-git/darwinia-common/node/runtime/pangolin/src/weights/pallet_grandpa.rs:58:2
     |
  58 | /     fn check_equivocation_proof(x: u32, ) -> Weight {
  59 | |         (62_998_000 as Weight)
  60 | |             // Standard Error: 8_580_000
  61 | |             .saturating_add((14_227_000 as Weight).saturating_mul(x as Weight))
  62 | |     }
     | |_____^ not a member of trait `pallet_grandpa::WeightInfo`

  error[E0046]: not all trait items implemented, missing: `report_equivocation`
    --> /home/workspace/darwinia-git/darwinia-common/node/runtime/pangolin/src/weights/pallet_grandpa.rs:57:1
     |
  57 | impl<T: frame_system::Config> pallet_grandpa::WeightInfo for WeightInfo<T> {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `report_equivocation` in implementation
     |
     = help: implement the missing item: `fn report_equivocation(_: u32) -> u64 { todo!() }`

  Some errors have detailed explanations: E0046, E0407.
  For more information about an error, try `rustc --explain E0046`.
  error: could not compile `pangolin-runtime` due to 2 previous errors
```

### Steps to reproduce

1. Benchmark for pallet_grandpa
2. Update weight for pallet_grandpa
3. Build

**Comment by ggwpez** [comment] 2022-07-14 08:24
Some pallets do not have automatic benchmarking. It is tracked in https://github.com/paritytech/substrate/issues/10780.  
This is also a duplicate of https://github.com/paritytech/substrate/issues/7383.  

The reason here is that the offences pallet is interlinked very tightly, and that needs benchmarks first.  
It is quite complicated but doable (see https://github.com/paritytech/substrate/issues/10781).

**Closed by ggwpez** 2022-07-14 08:24 UTC
Labels: Z0-unconfirmed
