### ISSUE TITLE
WasmExecutor heap memory leaking

### ISSUE THREAD

**Issue by sorpaas** [paritytech/substrate#927] opened 2018-10-18 09:44 UTC
Currently in Wasm executor, for many operations, we call `this.heap.allocate`, but the memory is never properly deallocated. The heap implementation right now also lack a deallocator.

This probably won't leak memory in main process, but it may be a bottleneck for huge wasm runtime.

**Comment by pepyakin** [comment] 2018-10-18 09:46
Duplicate of #300

**Closed by pepyakin** 2018-10-18 09:46 UTC
Labels: F5-task
