### ISSUE TITLE
Duplicate ReapedAccount events

### ISSUE THREAD

**Issue by emielvanderhoek** [paritytech/substrate#4457] opened 2019-12-19 12:04 UTC
There have been many instances of duplicate ReapedAccount events.
Example: https://polkascan.io/pre/kusama-cc3/block/291663#events

EventIndex 3: https://polkascan.io/pre/kusama-cc3/event/291663-3
EventIndex 5: https://polkascan.io/pre/kusama-cc3/event/291663-5
Both reap account: Dw6NYMJmwu5EHqN126j5AjHLCrz3kcJo6Cx2NJ72WaLmHxA

If an account is already reaped it should not be reaped again. I'd expect only 1 event per account.

**Comment by shawntabrizi** [comment] 2019-12-19 13:46
Duplicate of https://github.com/paritytech/substrate/issues/4402

**Closed by shawntabrizi** 2019-12-19 13:46 UTC
