### ISSUE TITLE
client/network-gossip: Receive message from unregistered peer

### ISSUE THREAD

**Issue by mxinden** [paritytech/substrate#6331] opened 2020-06-11 13:14 UTC
Some Substrate based nodes repeatedly log ["Got message from unregistered peer"](https://github.com/paritytech/substrate/blob/master/client/network-gossip/src/state_machine.rs#L323) on stderr.

The log line implies that the node received a message from a remote peer that the node is not currently connected to. `NotificationStreamOpened`, `NotificationsReceived` and `NotificationStreamClosed` are send via a single ordered channel which contradicts the logged error.

**Comment by tomaka** [comment] 2020-06-18 11:22
This is most likely a duplicate of #5592 but we should leave it open and close when we know it's fixed.

**Comment by tomaka** [comment] 2021-01-28 10:43
"Got message from unregistered peer" doesn't seem to happen anymore. Closing.

**Closed by tomaka** 2021-01-28 10:43 UTC
Labels: I2-bug 🐜, P5-sometimesoon
