### ISSUE TITLE
[question] transactions

### ISSUE THREAD

**Issue by puffanddmx** [paritytech/substrate#7264] opened 2020-10-06 02:37 UTC
Hello

Is there a function like the following Ethereum in the substrate?
Can I get information on a specific transaction through a substrate call? We did not find the document well, so we will contact you.

eth.getTransaction(transactionHash)

**Comment by bkchr** [comment] 2020-10-06 07:18
Sounds like a duplicate of: https://github.com/paritytech/substrate/issues/6705 ?

**Comment by puffanddmx** [comment] 2020-10-06 11:39
thanks!

**Closed** 2020-10-06 14:49 UTC
Labels: Z0-unconfirmed
