### ISSUE TITLE
panic when Ctrl C while importing blocks

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#1220] opened 2018-12-05 22:23 UTC
```2018-12-06 10:38:13 Syncing  0.4 bps, target=#13308 (3 peers), best: #2582 (0xca08…bc11)
2018-12-06 10:38:18 Syncing  0.4 bps, target=#13309 (3 peers), best: #2584 (0x9c59…69ab)
2018-12-06 10:38:23 Syncing  0.4 bps, target=#13310 (3 peers), best: #2586 (0xe552…e3cb)
2018-12-06 10:38:28 Syncing  0.2 bps, target=#13310 (3 peers), best: #2587 (0x6dbd…41e1)
^C^C
====================

stack backtrace:
   0:        0x107d22bb4 - backtrace::backtrace::trace::h36a4245422c5a2b9
                        at /Users/bryanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:        0x107d1d94c - backtrace::capture::Backtrace::new_unresolved::haf71169c2b8c1707
                        at /Users/bryanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:        0x107d1d8ae - backtrace::capture::Backtrace::new::h0082937f34249384
                        at /Users/bryanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:63
   3:        0x10594c177 - substrate_cli::panic_hook::panic_hook::hd517eb33c63b8fb4
                        at /Users/bryanchen/.cargo/git/checkouts/substrate-79104a8293a5645e/2adebf3/core/cli/src/panic_hook.rs:51
   4:        0x105955098 - core::ops::function::Fn::call::h2e411bb78ea33ccf
                        at /rustc/f1e2fa8f0469aac1ea69dd5b6164e1d198d57934/src/libcore/ops/function.rs:78
   5:        0x107d6a651 - std::panicking::rust_panic_with_hook::hd3777a4d39cc89aa
                        at /rustc/f1e2fa8f0469aac1ea69dd5b6164e1d198d57934/src/libstd/panicking.rs:480
   6:        0x107860bd7 - std::panicking::begin_panic::hdb4440dcc310223a
                        at /rustc/f1e2fa8f0469aac1ea69dd5b6164e1d198d57934/src/libstd/panicking.rs:410
   7:        0x10785bdcb - <slog_scope::NoGlobalLoggerSet as slog::Drain>::log::h44a4989a72894dd9
                        at /Users/bryanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.0.1/lib.rs:123
   8:        0x105552557 - <alloc::sync::Arc<D> as slog::Drain>::log::hef92511c5b14cf5d
                        at /Users/bryanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.4.1/src/lib.rs:1690
   9:        0x104ef9b72 - <slog::Logger<D>>::log::hff213b5d39552c28
                        at /Users/bryanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.4.1/src/lib.rs:1204
  10:        0x10536d471 - <substrate_client::client::Client<B, E, Block, RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::{{closure}}::h8f0ee77a192930db
                        at /Users/bryanchen/projects/blockchain/blockchain-node/<::slog::slog_log macros>:4
  11:        0x10545f0e8 - slog_scope::with_logger::{{closure}}::h012d9222faf84c4c
                        at /Users/bryanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.0.1/lib.rs:215
  12:        0x104e8fd1d - <std::thread::local::LocalKey<T>>::try_with::hb6a116f0e62b70d3
                        at /rustc/f1e2fa8f0469aac1ea69dd5b6164e1d198d57934/src/libstd/thread/local.rs:309
  13:        0x104e8d76f - <std::thread::local::LocalKey<T>>::with::h9dee881752df99a1
                        at /rustc/f1e2fa8f0469aac1ea69dd5b6164e1d198d57934/src/libstd/thread/local.rs:255
  14:        0x10545eed1 - slog_scope::with_logger::hcda5b6847f749a53
                        at /Users/bryanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.0.1/lib.rs:211
  15:        0x10536b9e5 - <substrate_client::client::Client<B, E, Block, RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h3afed9624e158a5f
                        at /Users/bryanchen/projects/blockchain/blockchain-node/<::substrate_telemetry::telemetry macros>:2
  16:        0x1054a7a5a - <substrate_finality_grandpa::GrandpaBlockImport<B, E, Block, RA, PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h7640b5d1d97ff1be
                        at /Users/bryanchen/.cargo/git/checkouts/substrate-79104a8293a5645e/2adebf3/core/finality-grandpa/src/lib.rs:666
  17:        0x1051ffc3c - substrate_network::import_queue::import_single_block::h30d68dceb6c169d3
                        at /Users/bryanchen/.cargo/git/checkouts/substrate-79104a8293a5645e/2adebf3/core/network/src/import_queue.rs:446
  18:        0x1051fab8d - substrate_network::import_queue::import_many_blocks::h94b11ffe8a318d06
                        at /Users/bryanchen/.cargo/git/checkouts/substrate-79104a8293a5645e/2adebf3/core/network/src/import_queue.rs:379
  19:        0x1051f904b - substrate_network::import_queue::import_thread::hf179ffaf74cc2748
                        at /Users/bryanchen/.cargo/git/checkouts/substrate-79104a8293a5645e/2adebf3/core/network/src/import_queue.rs:244
  20:        0x1051f7282 - <substrate_network::import_queue::BasicQueue<B, V> as substrate_network::import_queue::ImportQueue<B>>::start::{{closure}}::hec2a158f68d0b033
                        at /Users/bryanchen/.cargo/git/checkouts/substrate-79104a8293a5645e/2adebf3/core/network/src/import_queue.rs:150
  21:        0x1051f42d2 - std::sys_common::backtrace::__rust_begin_short_backtrace::he4a7bc9b077fbf6a
                        at /rustc/f1e2fa8f0469aac1ea69dd5b6164e1d198d57934/src/libstd/sys_common/backtrace.rs:136
  22:        0x1055007c2 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::ha13f8649a96afd07
                        at /rustc/f1e2fa8f0469aac1ea69dd5b6164e1d198d57934/src/libstd/thread/mod.rs:477
  23:        0x105502262 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he7f942ef65886594
                        at /rustc/f1e2fa8f0469aac1ea69dd5b6164e1d198d57934/src/libstd/panic.rs:319
  24:        0x105217f36 - std::panicking::try::do_call::h4b6bd07f573b845d
                        at /rustc/f1e2fa8f0469aac1ea69dd5b6164e1d198d57934/src/libstd/panicking.rs:310
  25:        0x107d7a36e - ___rust_maybe_catch_panic
                        at /rustc/f1e2fa8f0469aac1ea69dd5b6164e1d198d57934/src/libpanic_unwind/lib.rs:102
  26:        0x105217860 - std::panicking::try::h68f9032814ea383f
                        at /rustc/f1e2fa8f0469aac1ea69dd5b6164e1d198d57934/src/libstd/panicking.rs:289
  27:        0x105502382 - std::panic::catch_unwind::h268c5658fb22c642
                        at /rustc/f1e2fa8f0469aac1ea69dd5b6164e1d198d57934/src/libstd/panic.rs:398
  28:        0x1054ff7e9 - std::thread::Builder::spawn_unchecked::{{closure}}::h18a20fb0caa49808
                        at /rustc/f1e2fa8f0469aac1ea69dd5b6164e1d198d57934/src/libstd/thread/mod.rs:476
  29:        0x105500d27 - <F as alloc::boxed::FnBox<A>>::call_box::h3f454ffd271fa987
                        at /rustc/f1e2fa8f0469aac1ea69dd5b6164e1d198d57934/src/liballoc/boxed.rs:673
  30:        0x107d6e24b - std::sys::unix::thread::Thread::new::thread_start::h01062e735dc5a638
                        at /rustc/f1e2fa8f0469aac1ea69dd5b6164e1d198d57934/src/libstd/sys_common/thread.rs:24
  31:     0x7fff5c62b338 - __pthread_body
  32:     0x7fff5c62e2a6 - __pthread_start

Thread 'ImportQueue' panicked at 'slog-scope: No logger set. Use `slog_scope::set_global_logger` or `slog_scope::scope`.', /Users/bryanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.0.1/lib.rs:123
```

Error message is from here

https://github.com/slog-rs/scope/blob/b8964a0d7204e9fee1190335b09862e09338a39e/lib.rs#L124

I am using substrate-node-template that modified to use latest substrate

**Comment by gavofyork** [comment] 2018-12-18 16:33
Probably a duplicate of #1206

**Closed by gavofyork** 2018-12-18 16:33 UTC
