### ISSUE TITLE
How to diagnostic grandpa issue?

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#5094] opened 2020-03-02 02:21 UTC
When grandpa stalls, it is not easy to figure out what's wrong even with `-l afg=trace` enabled.

I want to see:
- who are the voters
- the votes from each voters

For both completed round and current round. Currently the logs doesn't include much information about current round.

This is the log helps me. (I edited the code in cargo github registry locally to include those additional information)

> DEBUG afg  Round 1: precommits: 7/6/8 weight, 7/8 actual, [(Public(21b5a771b99ef0f059c476502c018c4b817fb0e48858e95a238850d2b7828556 (5CpuQ9Uj...)), Precommit { target_hash: 0x803f88fefd791df512cf7e7b4b36d2bb65f2375616e36e478e9f8a57e2cb48d2, target_number: 32609 }), (Public(2b5d678c58558507a974c6f149392b5a62cf1f76146a3210da451a220050f734 (5D3ZfR2N...)), Precommit { target_hash: 0x803f88fefd791df512cf7e7b4b36d2bb65f2375616e36e478e9f8a57e2cb48d2, target_number: 32609 }), (Public(533f3664876407fac9385416269f6c120b7c1807d6cee96f30066fb69cf99bb1 (5DwrcK1H...)), Precommit { target_hash: 0x803f88fefd791df512cf7e7b4b36d2bb65f2375616e36e478e9f8a57e2cb48d2, target_number: 32609 }), (Public(5c9ce55e9133eaea0831a403c7619fd3e5bb1dedb0cb631f948718f89d61c2cf (5EA8sSFk...)), Precommit { target_hash: 0x803f88fefd791df512cf7e7b4b36d2bb65f2375616e36e478e9f8a57e2cb48d2, target_number: 32609 }), (Public(77f3c27e98da7849ed0749e1dea449321a4a5a36a1dccf3f08fc0ab3af24c62e (5Emyy3wq...)), Precommit { target_hash: 0x803f88fefd791df512cf7e7b4b36d2bb65f2375616e36e478e9f8a57e2cb48d2, target_number: 32609 }), (Public(934ff7c3ad46d033a02cdf9788592eda74706d1f56dcd61359968f603e49ad7a (5FPrekJQ...)), Precommit { target_hash: 0x803f88fefd791df512cf7e7b4b36d2bb65f2375616e36e478e9f8a57e2cb48d2, target_number: 32609 }), (Public(c152550c03201bff2bc62d10c827f58509f8d8e3d977040dc17e1bf869cab305 (5GSBZEwY...)), Precommit { target_hash: 0x803f88fefd791df512cf7e7b4b36d2bb65f2375616e36e478e9f8a57e2cb48d2, target_number: 32609 })]

This is especially useful to diagnostic issue caused by validator participating babe but not grandpa.

**Comment by bkchr** [comment] 2020-03-02 07:07
Duplicate of https://github.com/paritytech/substrate/issues/4921

**Closed by bkchr** 2020-03-02 07:07 UTC
